/* City defense purchases are permanent, bounded, and committed atomically. */
(function(root){
  'use strict';
  function state(m,town){var raw=(m.cityDefenses268||{})[town]||{},barriers=[];for(var i=0;i<8;i++)barriers.push(level((raw.barriers||[])[i]));return {turret:level(raw.turret),hq:level(raw.hq),barriers:barriers,role:raw.role==='heavy'?'heavy':'rapid'};}
  function level(n){return Math.max(0,Math.min(3,Math.floor(Number(n)||0)));}
  function cap(m){return Math.min(3,1+Math.floor((Math.max(1,Number(m.hq)||1)-1)/2));}
  function quote(m,town,key){var s=state(m,town),index=/^barrier[0-7]$/.test(key)?Number(key.slice(7)):-1,valid=key==='turret'||key==='hq'||index>=0,n=key==='turret'?s.turret:key==='hq'?s.hq:s.barriers[index],next=(n||0)+1;return {valid:valid,level:n||0,next:next,cap:cap(m),credits:next*(index>=0?150:key==='turret'?500:400),materials:next*(index>=0?30:40),stone:next*(index>=0?20:key==='hq'?60:0),index:index};}
  function buy(m,town,key,save){var q=quote(m,town,key),d=m.settlement204;if(!q.valid||!d||!town)return {ok:false,message:'City defense unavailable.'};if(q.level>=q.cap)return {ok:false,message:q.cap===3?'Maximum level reached.':'Upgrade HQ to level '+(q.cap*2+1)+' to unlock the next defense level.'};if(m.credits<q.credits||d.materials<q.materials||d.stone<q.stone)return {ok:false,message:'Not enough resources.'};var previous=m.cityDefenses268,credits=m.credits,materials=d.materials,stone=d.stone,s=state(m,town);if(q.index>=0)s.barriers[q.index]++;else s[key]++;m.cityDefenses268=Object.assign({},previous);m.cityDefenses268[town]=s;m.credits-=q.credits;d.materials-=q.materials;d.stone-=q.stone;var saved=false;try{saved=save()===true;}catch(e){}if(!saved){m.credits=credits;d.materials=materials;d.stone=stone;if(previous===undefined)delete m.cityDefenses268;else m.cityDefenses268=previous;return {ok:false,message:'Could not save. No resources spent. Try again.'};}return {ok:true,message:'Saved for this city. Restored fully on every retry.'};}
  function role(m,town,value,save){if(value!=='rapid'&&value!=='heavy')return false;var previous=m.cityDefenses268,s=state(m,town);s.role=value;m.cityDefenses268=Object.assign({},previous);m.cityDefenses268[town]=s;var ok=false;try{ok=save()===true;}catch(e){}if(!ok){if(previous===undefined)delete m.cityDefenses268;else m.cityDefenses268=previous;}return ok;}
  function apply(m,r){if(!r.starTown||!m.settlement204)return;var s=state(m,r.starTown);if(!r.prepBase268)r.prepBase268={damage:r.turret.damage,rate:r.turret.rate,boss:r.turretBossDamage||0,armor:r.turretArmoredDamage||0,hq:r.hq.maxHp,barriers:r.lanes.map(function(l){return l.barricade.maxHp;})};var b=r.prepBase268;r.turret.damage=b.damage*(1+s.turret*.25)*(s.role==='heavy'?1.5:.8);r.turret.rate=b.rate*(s.role==='heavy'?.75:1.4);r.turretBossDamage=b.boss+(s.role==='heavy'?.25:0);r.turretArmoredDamage=b.armor+(s.role==='heavy'?.25:0);r.hq.hp=r.hq.maxHp=Math.round(b.hq*(1+s.hq*.25));r.lanes.forEach(function(l,i){l.barricade.hp=l.barricade.maxHp=Math.round(b.barriers[i]*(1+s.barriers[i]*.4));});}
  function count(m,town){var s=state(m,town);return s.turret+s.hq+s.barriers.reduce(function(a,b){return a+b;},0);}
  root.LSCDefensePreparation={state:state,quote:quote,buy:buy,role:role,apply:apply,cap:cap,count:count};
})(typeof window!=='undefined'?window:globalThis);
