(function(root){
 'use strict';
 var towns=[{id:1,x:5,y:0},{id:2,x:5,y:5},{id:3,x:-5,y:4},{id:4,x:-5,y:-5},{id:5,x:10,y:0},{id:6,x:10,y:7}],tiles={};
 function key(x,y){return x+','+y;}
 function tile(id){return tiles[id];}
 for(var y=-10;y<=10;y++)for(var x=-10;x<=12;x++){var id=key(x,y),town=towns.find(function(t){return t.x===x&&t.y===y;}),terrain=x===7?'water':x===6||x===8?'bank':(Math.abs(x*3+y*7)%9<2?'hill':'plain');tiles[id]={id:id,x:x,y:y,terrain:terrain,town:town&&town.id};}
 tiles['1,0'].terrain='plain';tiles['0,1'].terrain='hill';
 var defs={farm:{name:'Farm',credits:100,materials:20,capacity:4,seconds:20},workshop:{name:'Workshop',credits:150,materials:30,capacity:4,seconds:25},house:{name:'Housing',credits:100,materials:30,capacity:0,seconds:20},road:{name:'Road',credits:5,materials:2,capacity:0,seconds:10},bridge:{name:'Bridge',credits:30,materials:10,capacity:0,seconds:20}};
 function s(m){return m.settlement204;}
 function clone(v){return JSON.parse(JSON.stringify(v));}
 function neighbors(id){var t=tile(id)||{x:0,y:0};return [[1,0],[-1,0],[0,1],[0,-1]].map(function(d){return key(t.x+d[0],t.y+d[1]);});}
 function reveal(d,id,r){var t=tile(id);if(!t)return;for(var y=-r;y<=r;y++)for(var x=-r;x<=r;x++){var k=key(t.x+x,t.y+y);if(tile(k))d.visible[k]=true;}}
 function network(m){var d=s(m),set=new Set(['0,0']),q=['0,0'];for(var i=0;i<q.length;i++)neighbors(q[i]).forEach(function(id){if(d.roads[id]&&!set.has(id)){set.add(id);q.push(id);}});return set;}
 function connected(m,id){var n=network(m);return n.has(id)||neighbors(id).some(function(k){return n.has(k);});}
 function workers(m){var d=s(m),assigned=Object.keys(d.buildings).reduce(function(n,k){return n+d.buildings[k].workers;},0),scouts=d.scout?2:0,builders=d.job?2:0;return {total:d.population,assigned:assigned,scouts:scouts,builders:builders,available:d.population-assigned-scouts-builders};}
 function housing(m){return 12+Object.keys(s(m).buildings).reduce(function(n,k){return n+(s(m).buildings[k].kind==='house'?4:0);},0);}
 function income(m){return 2+towns.reduce(function(n,t){return n+(s(m).welcomed[t.id]&&network(m).has(key(t.x,t.y))?2*stars(t.id):0);},0);}
 function stars(n){return n<=3?1:n<=4?2:3;}
 function combat(n){return n<=3?n:1+(stars(n)-1)*5;}
 function rates(m){var d=s(m),food=0,materials=0;Object.keys(d.buildings).forEach(function(id){var b=d.buildings[id];if(!connected(m,id))return;if(b.kind==='farm')food+=b.workers*3;if(b.kind==='workshop')materials+=b.workers*2;});return {food:food-d.population*.25,materials:materials*(d.tools?1.2:1),credits:income(m)};}
 function accrue(m,minutes){var d=s(m),r=rates(m),fed=minutes;if(r.food<0)fed=Math.min(minutes,d.food/-r.food);else if(d.food<=0&&r.food===0)fed=0;d.food=Math.max(0,d.food+r.food*minutes);d.materials+=r.materials*(fed+(minutes-fed)*.5);var cr=(d.creditCarry||0)+r.credits*minutes;m.credits+=Math.floor(cr);d.creditCarry=cr-Math.floor(cr);}
 function finishEvents(m,at){var d=s(m);if(d.scout&&d.scout.end<=at){reveal(d,d.scout.target,3);d.scout=null;d.scouted=true;d.notice='Scouts returned. New terrain revealed; 2 workers available.';}if(d.job&&d.job.end<=at){var j=d.job;j.path.forEach(function(id){d.cleared[id]=true;if(j.kind==='road'||j.kind==='bridge')d.roads[id]=true;else d.buildings[id]={kind:j.kind,workers:0};});d.job=null;d.notice=defs[j.kind].name+' complete. Builders are available.';}}
 function advance(m,now){var d=s(m);now=Math.max(d.at,now);var end=Math.min(now,d.at+480*60000),at=d.at;while(at<end){var next=end;[d.scout,d.job].forEach(function(j){if(j&&j.end>at)next=Math.min(next,j.end);});accrue(m,(next-at)/60000);at=next;finishEvents(m,at);}finishEvents(m,now);d.at=now;}
 function transact(m,save,fn,now){var old=s(m),credits=m.credits;m.settlement204=clone(old);try{advance(m,now===undefined?Date.now():now);var message=fn(s(m));if(save()!==true)throw Error('Save failed. No action was committed.');return {ok:true,message:message||s(m).notice};}catch(e){m.settlement204=old;m.credits=credits;return {ok:false,message:e.message};}}
 function initialize(m,save,now){if(s(m))return {ok:true};var oldStar=m.starTowns,oldCredits=m.credits,d={version:204,population:12,food:120,materials:120,buildings:{'1,0':{kind:'farm',workers:0},'0,1':{kind:'workshop',workers:0}},roads:{'0,0':true,'1,0':true,'0,1':true},cleared:{},visible:{},defended:{},welcomed:{},scout:null,job:null,at:now===undefined?Date.now():now,notice:'Assign 2 workers to the farm to feed your settlement.'};for(var y=-1;y<=1;y++)for(var x=-1;x<=1;x++)d.cleared[key(x,y)]=true;reveal(d,'0,0',2);m.settlement204=d;m.starTowns={progress:{},secured:{},towers:{},incomeAt:d.at,opening202:true};m.credits+=2000;try{if(save()!==true)throw Error('Save failed');return {ok:true};}catch(e){delete m.settlement204;m.credits=oldCredits;if(oldStar===undefined)delete m.starTowns;else m.starTowns=oldStar;return {ok:false,message:'Could not initialize settlement. Save unchanged.'};}}
 function action(m,save,kind,payload,now){payload=payload||{};return transact(m,save,function(d){var id=payload.id,t=tile(id),b=d.buildings[id],w=workers(m);
  if(kind==='assign'){if(!b||!defs[b.kind].capacity)throw Error('Select a production building.');var count=Number(payload.count);if(!Number.isInteger(count)||count<0||count>defs[b.kind].capacity)throw Error('Invalid assignment.');if(count-b.workers>w.available)throw Error('No available workers. Reassign workers or wait for expeditions/builders.');b.workers=count;return count+' workers assigned.';}
  if(kind==='clear'){if(!t||!d.visible[id]||t.terrain==='water'||d.cleared[id]||!neighbors(id).some(function(k){return d.cleared[k];}))throw Error('Clear revealed land beside accessible territory.');d.cleared[id]=true;if(!t.town&&(Math.abs(t.x*13+t.y*7)%17===0)){d.materials+=10;m.credits+=50;return 'Supply discovery: +10 Materials, +50 Credits.';}return 'Land accessible. No Credits spent.';}
  if(kind==='scout'){if(d.scout)throw Error('One expedition is already away.');if(w.available<2||d.food<20)throw Error('Scouting requires 2 available workers and 20 Food.');if(!t||!d.visible[id]||!neighbors(id).some(function(k){return tile(k)&&!d.visible[k];}))throw Error('Choose a revealed tile at the fog boundary.');d.food-=20;d.scout={target:id,end:d.at+60000};return 'Scouts deployed for 60 seconds. Two workers reserved.';}
  if(kind==='build'){var type=payload.type,def=defs[type],path=payload.path||[id];if(!def||d.job||w.available<2)throw Error('Construction needs 2 available workers and an empty project slot.');if(!Array.isArray(path)||!path.length||path.length>40||new Set(path).size!==path.length)throw Error('Invalid route.');var route=type==='road'||type==='bridge',net=network(m);if(!route&&path.length!==1)throw Error('One building per square.');path.forEach(function(k,i){var tt=tile(k);if(!tt||!d.visible[k])throw Error('Scout this site first.');if(route){if(d.roads[k])throw Error('This route includes an existing road.');if(i?neighbors(path[i-1]).indexOf(k)<0:!neighbors(k).some(function(n){return net.has(n);}))throw Error('Start beside the connected road network and trace adjacent squares.');if(type==='road'&&tt.terrain==='water')throw Error('Water requires a bridge.');if(type==='bridge'&&tt.terrain!=='water')throw Error('Bridges require water.');}else{if(!d.cleared[k]||tt.town||k==='0,0'||d.buildings[k])throw Error('Choose empty, cleared land.');if(type==='farm'&&tt.terrain!=='plain'&&tt.terrain!=='bank'||type==='workshop'&&tt.terrain!=='hill'||tt.terrain==='water')throw Error('Farm: plain/bank. Workshop: hills. Housing: land.');}});var cr=def.credits*path.length,mat=def.materials*path.length;if(m.credits<cr||d.materials<mat)throw Error('Not enough Credits or Materials.');m.credits-=cr;d.materials-=mat;d.job={kind:type,path:path.slice(),end:d.at+def.seconds*1000};return 'Construction started. Two builders assigned.';}
  if(kind==='welcome'){var town=towns.find(function(t){return t.id===payload.town;});if(!town||!d.defended[town.id]||d.welcomed[town.id]||!network(m).has(key(town.x,town.y)))throw Error('Defend the town and connect its road first.');if(housing(m)<d.population+4||d.food<20)throw Error('Need 4 vacant housing spaces and 20 Food.');d.food-=20;d.population+=4;d.welcomed[town.id]=true;return '+4 survivors joined. Assign your new workers.';}
  if(kind==='demolish'){if(id==='0,0'||!b&&!d.roads[id])throw Error('Select a building or road.');if(d.job)throw Error('Finish construction before demolition.');if(b&&b.kind==='house'&&housing(m)-4<d.population)throw Error('Build replacement housing first.');var refund=b?Math.floor(defs[b.kind].materials/2):Math.floor((t.terrain==='water'?defs.bridge:defs.road).materials/2);if(b)delete d.buildings[id];else delete d.roads[id];d.materials+=refund;return 'Removed. +'+refund+' Materials returned; workers released. Roads may need reconnecting.';}
  if(kind==='research'){if(d.tools)throw Error('Already researched.');if(m.credits<200||d.materials<30)throw Error('Requires 200 Credits and 30 Materials.');m.credits-=200;d.materials-=30;d.tools=true;return 'Better Tools: workshop output +20%.';}
  throw Error('Unknown action.');
 },now);}
 function ready(m,n){var t=towns.find(function(t){return t.id===n;});return !!(s(m)&&t&&s(m).visible[key(t.x,t.y)]&&!s(m).defended[n]);}
 function win(m,n){if(!ready(m,n))return false;advance(m,Date.now());s(m).defended[n]=true;s(m).notice='Town defended. Connect its road and provide housing to welcome 4 survivors.';return true;}
 function objective(m){var d=s(m);if((d.buildings['1,0']||{}).workers<2&&!d.scouted)return {id:'1,0',text:'Feed your people · assign 2 farm workers'};if(!d.scouted)return {id:'2,0',text:d.scout?'Scouts away · build housing while they explore':'Explore the frontier · send 2 scouts'};if(!d.defended[1])return {id:'5,0',text:'Survivors discovered · defend Brookhaven'};if(!network(m).has('5,0'))return {id:'5,0',text:'Connect Brookhaven · build its road'};if(!d.welcomed[1])return {id:'5,0',text:'Welcome survivors · 4 housing spaces + 20 Food'};return {id:null,text:'Expand your settlement · choose the next discovery'};}
 root.LSCSettlement={initialize:initialize,action:action,tick:function(m,save,now){return transact(m,save,function(){},now);},advance:advance,ready:ready,win:win,objective:objective,workers:workers,housing:housing,rates:rates,income:income,connected:connected,network:network,defs:defs,tiles:tiles,tile:tile,towns:towns,stars:stars,combat:combat};
})(typeof window!=='undefined'?window:globalThis);
