(function(root){
 'use strict';
 // Keep the 204 save key and map coordinates; upgrade the rules in place.
 var old=root.LSCSettlement,tiles=old.tiles,defs=old.defs;
 defs.tower={name:'Scouting Tower',credits:180,materials:60,capacity:0,seconds:60};
 function towerArea(m,id){var t=tiles[id];if(!t)return [];return Object.keys(tiles).filter(function(k){return Math.max(Math.abs(tiles[k].x-t.x),Math.abs(tiles[k].y-t.y))<=8;});}
 function projectFinished(m,p){var d=s(m);p.path.slice(p.done||0).forEach(function(k){d.cleared[k]=true;if(['connection','road','bridge'].indexOf(p.kind)>=0)d.roads[k]=true;else d.buildings[k]={kind:p.kind,workers:0};});}
 function plannedWorld(m){var copy=clone(m),d=s(copy);if(d.job)projectFinished(copy,d.job);d.job=null;(d.queue||[]).forEach(function(q){projectFinished(copy,q.project);});d.queue=[];return copy;}
 function startQueue(m){var d=s(m);if(d.job||!d.queue||!d.queue.length)return;var q=d.queue[0];try{var p=plan(m,q.kind,q.payload);p.crew=crewCheck(m,q.crew,'job');if(!p.crew)throw Error('Waiting for workers.');if(p.credits>q.credits||p.materials>q.materials)throw Error('Route changed. Cancel and plan this project again.');m.credits+=q.credits-p.credits;d.materials+=q.materials-p.materials;p.done=0;p.progress=0;d.queue.shift();d.job=p;d.queueNotice='';emit(m,p.path[0],'Queued project started · '+p.crew+' workers');}catch(e){d.queueNotice=e.message;}}
 var knowledge=[
  {id:'tools',name:'Better Tools',credits:200,materials:30,work:120,requires:[],effect:'+20% workshop Materials output'},
  {id:'survey',name:'Field Surveying',credits:100,materials:25,work:180,requires:['tools'],effect:'+25% scout work speed; surveys reveal radius 4 instead of 3'},
  {id:'logistics',name:'Organized Construction',credits:150,materials:40,work:240,requires:['tools'],effect:'+20% construction and village connection work speed'},
  {id:'stores',name:'Village Storehouses',credits:200,materials:60,work:300,requires:['logistics'],village:1,effect:'+300 Food and Materials storage capacity'}
 ];
 function learned(m,id){return id==='tools'?!!s(m).tools:!!(s(m).knowledge&&s(m).knowledge[id]);}
 function researchState(m,id){var n=knowledge.find(function(n){return n.id===id;});if(!n)return {ok:false,message:'Unknown knowledge.'};if(learned(m,id))return {ok:false,message:'Acquired'};var missing=n.requires.filter(function(k){return !learned(m,k);});if(missing.length)return {ok:false,message:'Requires '+missing.map(function(k){return knowledge.find(function(n){return n.id===k;}).name;}).join(', ')};if(n.village&&!active(m,n.village))return {ok:false,message:'Integrate and connect '+town(n.village).name};if(s(m).study)return {ok:false,message:'Finish or resume the current research first.'};return {ok:true,node:n};}
 var towns=[
  {id:1,x:5,y:0,name:'Brookhaven',specialty:'A safe foothold',benefit:'4 residents and +2 Credits/min'},
  {id:2,x:5,y:5,name:'Millfield',specialty:'Agriculture',benefit:'Connected farms produce 10% more Food'},
  {id:3,x:-5,y:4,name:'Ironridge',specialty:'Industry',benefit:'Connected workshops produce 10% more Materials'},
  {id:4,x:-5,y:-5,name:'Highwatch',specialty:'Exploration',benefit:'Scouting crews work 15% faster'},
  {id:5,x:10,y:0,name:'Stoneford',specialty:'Construction',benefit:'Construction crews work 10% faster'},
  {id:6,x:10,y:7,name:'Port Mercer',specialty:'Trade',benefit:'+4 extra Credits/min'}
 ];
 function s(m){return m.settlement204;} function clone(v){return JSON.parse(JSON.stringify(v));}
 function key(x,y){return x+','+y;} function tile(id){return tiles[id];}
 function town(n){return towns.find(function(t){return t.id===Number(n);});}
 function neighbors(id){var t=tile(id);return t?[[1,0],[0,1],[-1,0],[0,-1]].map(function(v){return key(t.x+v[0],t.y+v[1]);}).filter(tile):[];}
 function network(m){var d=s(m),set=new Set(['0,0']),q=['0,0'];for(var i=0;i<q.length;i++)neighbors(q[i]).forEach(function(k){if(d.roads[k]&&!set.has(k)){set.add(k);q.push(k);}});return set;}
 function connected(m,id){var net=network(m);return net.has(id)||neighbors(id).some(function(k){return net.has(k);});}
 function active(m,n){var t=town(n);return !!(s(m).welcomed[n]&&network(m).has(key(t.x,t.y)));}
 function stars(n){return old.stars(n);} function combat(n){return old.combat(n);}
 function housing(m){return old.housing(m);} function storage(m){return 500+(housing(m)-12)*25+(learned(m,'stores')?300:0);}
 function capacity(m,kind){return Object.keys(s(m).buildings).reduce(function(n,k){var b=s(m).buildings[k];return n+(b.kind===kind&&connected(m,k)?defs[kind].capacity:0);},0);}
 function foodMinimum(m){return s(m).protectFood?Math.min(capacity(m,'farm'),Math.ceil((s(m).population*.25+1)/(3*(active(m,2)?1.1:1)))):0;}
 function workers(m){var d=s(m),assigned=Object.keys(d.buildings).reduce(function(n,k){return n+d.buildings[k].workers;},0),scouts=d.scout?d.scout.crew:0,builders=d.job?d.job.crew:0,scholars=d.study?d.study.crew:0;return {total:d.population,assigned:assigned,scouts:scouts,builders:builders,scholars:scholars,available:d.population-assigned-scouts-builders-scholars};}
 function rebalance(m){var d=s(m),free=d.population-(d.job?d.job.crew:0)-(d.scout?d.scout.crew:0)-(d.study?d.study.crew:0);Object.keys(d.buildings).forEach(function(k){d.buildings[k].workers=0;});
  ['farm','workshop'].forEach(function(kind){var target=Math.min(free,Math.max(d.targets[kind]||0,kind==='farm'?foodMinimum(m):0));if(kind==='workshop'&&d.materials>=storage(m))target=0;Object.keys(d.buildings).sort().forEach(function(k){var b=d.buildings[k];if(b.kind!==kind||!connected(m,k))return;var n=Math.min(target,defs[kind].capacity);b.workers=n;target-=n;free-=n;});});
 }
 function income(m){return 2+towns.reduce(function(n,t){return n+(active(m,t.id)?2*stars(t.id)+(t.id===6?4:0):0);},0);}
 function rates(m){var d=s(m),food=0,materials=0;Object.keys(d.buildings).forEach(function(k){var b=d.buildings[k];if(!connected(m,k))return;if(b.kind==='farm')food+=b.workers*3;if(b.kind==='workshop')materials+=b.workers*2;});return {food:food*(active(m,2)?1.1:1)-d.population*.25,materials:materials*(d.tools?1.2:1)*(active(m,3)?1.1:1),credits:income(m)};}
 function economy(m){var d=s(m),r=rates(m),cap=storage(m),consumption=d.population*.25;return {capacity:cap,foodGross:r.food+consumption,foodUse:consumption,foodNet:d.food>=cap?Math.min(0,r.food):d.food<=0?Math.max(0,r.food):r.food,materialsNet:d.materials>=cap?0:r.materials*(d.food<=0&&r.food<=0?.5:1),foodFull:d.food>=cap,materialsFull:d.materials>=cap,shortage:d.food<=0&&r.food<=0};}
 function speed(m,job){if(!job||!job.crew)return 0;return Math.pow(job.crew,.9)*(job.kind==='study'?1:job.kind==='scout'?(active(m,4)?1.15:1)*(learned(m,'survey')?1.25:1):(active(m,5)?1.1:1)*(learned(m,'logistics')?1.2:1));}
 function remaining(job){if(!job)return 0;return job.work.slice(job.done||0).reduce(function(a,b){return a+b;},0)-(job.progress||0);}
 function eta(m,job){var v=speed(m,job);return v?Math.ceil(remaining(job)/v):null;}
 function emit(m,id,text){var d=s(m);d.notice=text;d.event={id:id,text:text,at:d.at};}
 function reveal(m,id,r){var t=tile(id),d=s(m);for(var y=-r;y<=r;y++)for(var x=-r;x<=r;x++){var k=key(t.x+x,t.y+y);if(tile(k))d.visible[k]=true;}}
 function accrue(m,seconds){var d=s(m),r=rates(m),minutes=seconds/60,fed=minutes;if(r.food<0)fed=Math.min(minutes,d.food/-r.food);else if(d.food<=0&&r.food===0)fed=0;var cap=storage(m);d.food=Math.max(0,Math.min(Math.max(cap,d.food),d.food+r.food*minutes));d.materials=Math.min(Math.max(cap,d.materials),d.materials+r.materials*(fed+(minutes-fed)*.5));var cr=(d.creditCarry||0)+r.credits*minutes;m.credits+=Math.floor(cr);d.creditCarry=cr-Math.floor(cr);}
 function finish(m,type){var d=s(m),j=d[type];if(!j)return;var index=j.done||0;
  if(type==='study'){if(j.progress+1e-6>=j.work[0]){d.knowledge=d.knowledge||{};d.knowledge[j.node]=true;if(j.node==='tools')d.tools=true;d.study=null;var n=knowledge.find(function(n){return n.id===j.node;});emit(m,'0,0',n.name+' acquired');d.notice=n.name+': '+n.effect+'. Researchers returned to the workforce.';}return;}
  if(type==='scout'){if(!j.revealed&&j.progress>=j.revealAt){reveal(m,j.target,learned(m,'survey')?4:3);j.revealed=true;d.scouted=true;emit(m,j.target,'Area surveyed. Scouts are returning.');}if(j.progress+1e-6>=j.work[0]){d.scout=null;emit(m,j.target,'Scouts returned. Crew available for reassignment.');}}
  else if(j.progress+1e-6>=j.work[index]){var id=j.path[index];d.cleared[id]=true;if(j.kind==='connection'||j.kind==='road'||j.kind==='bridge')d.roads[id]=true;else d.buildings[id]={kind:j.kind,workers:0};var unveiled=0;if(j.kind==='tower'){towerArea(m,id).forEach(function(k){if(!d.visible[k])unveiled++;d.visible[k]=true;});}j.progress=0;j.done=index+1;if(j.done>=j.path.length){d.job=null;emit(m,id,j.kind==='tower'?'Tower surveyed: '+unveiled+' new tiles':(j.kind==='connection'?'Village connection':defs[j.kind].name)+' complete. Crew released.');}}
 }
 function advance(m,now){var d=s(m);now=Math.max(d.at,Number(now)||d.at);var limit=Math.min(now,d.at+8*3600000);startQueue(m);rebalance(m);
  while(d.at+0.001<limit){var seconds=(limit-d.at)/1000;['job','scout','study'].forEach(function(type){var j=d[type],v=speed(m,j);if(v){var edge=j.work[j.done||0];if(type==='scout'&&!j.revealed)edge=j.revealAt;seconds=Math.min(seconds,Math.max(0,(edge-j.progress)/v));}});
   if(seconds>0){accrue(m,seconds);['job','scout','study'].forEach(function(type){var j=d[type];if(j)j.progress+=seconds*speed(m,j);});d.at+=seconds*1000;}
   var before=JSON.stringify([d.job,d.scout,d.study]);finish(m,'scout');finish(m,'job');finish(m,'study');startQueue(m);rebalance(m);if(seconds===0&&before===JSON.stringify([d.job,d.scout,d.study]))break;
  }d.at=now;
 }
 function initialize(m,save,now){now=now===undefined?Date.now():now;var existed=!!s(m),snapshot=clone(m);if(!existed){var result=old.initialize(m,function(){return true;},now);if(!result.ok)return result;}
  if(s(m).version>=205)return {ok:true};var d=s(m);d.targets={farm:0,workshop:0};Object.keys(d.buildings).forEach(function(k){var b=d.buildings[k];if(d.targets[b.kind]!==undefined)d.targets[b.kind]+=b.workers||0;});if(!existed)d.targets={farm:2,workshop:4};d.protectFood=true;d.defaultCrew=4;d.version=205;
  ['job','scout'].forEach(function(type){var j=d[type];if(!j)return;var seconds=Math.max(.1,(j.end-d.at)/1000);if(type==='scout')d.scout={kind:'scout',crew:2,path:['0,0',j.target],target:j.target,work:[seconds*Math.pow(2,.9)],done:0,progress:0,revealAt:seconds*Math.pow(2,.9)*.7,revealed:false};else d.job={kind:j.kind,crew:2,path:j.path,work:j.path.map(function(){return seconds*Math.pow(2,.9)/j.path.length;}),done:0,progress:0};});rebalance(m);d.notice='205: production targets distribute workers automatically. Existing resources and projects are preserved.';
  try{if(save()!==true)throw Error('save');return {ok:true};}catch(e){Object.keys(m).forEach(function(k){delete m[k];});Object.assign(m,snapshot);return {ok:false,message:'Upgrade could not save. Campaign unchanged.'};}
 }
 function transact(m,save,fn,now){var snapshot=clone(s(m)),credits=m.credits;try{advance(m,now===undefined?Date.now():now);var text=fn(s(m));startQueue(m);rebalance(m);if(text)s(m).notice=text;if(save()!==true)throw Error('Save failed. Changes were rolled back.');return {ok:true,message:text||s(m).notice};}catch(e){m.settlement204=snapshot;m.credits=credits;return {ok:false,message:e.message};}}
 // Dijkstra route: known squares only; bridge costs discourage unnecessary water crossings.
 function route(m,target,scouting){var d=s(m),net=network(m),dist={},prev={},open=[];net.forEach(function(k){dist[k]=0;prev[k]=null;open.push(k);});
  while(open.length){open.sort(function(a,b){return dist[a]-dist[b];});var k=open.shift();if(k===target){var result=[];while(k!==null){result.unshift(k);k=prev[k];}return result;}
   neighbors(k).forEach(function(n){var t=tile(n);if(!d.visible[n]||scouting&&t.terrain==='water'&&!d.roads[n]||!scouting&&d.buildings[n]&&!d.roads[n])return;var cost=dist[k]+(d.roads[n]?0.01:t.terrain==='water'?5:1);if(dist[n]===undefined||cost<dist[n]){dist[n]=cost;prev[n]=k;if(open.indexOf(n)<0)open.push(n);}});
  }return [];
 }
 function crewCheck(m,count,type){count=Number(count);if(!Number.isInteger(count)||count<0||count>6)throw Error('Choose 0–6 workers.');var d=s(m),reserved=['job','scout','study'].reduce(function(n,k){return n+(k!==type&&d[k]?d[k].crew:0);},0),budget=d.population-reserved-foodMinimum(m);if(count>budget)throw Error('Not enough workers after protecting Food and the other crew.');return count;}
 function plan(m,kind,payload){payload=payload||{};var d=s(m),path=payload.path||[payload.id],origin='0,0',cr=0,mat=0,work=[],target=payload.id;
  if(kind==='connection'){var t=town(payload.town);if(!t||!d.visible[key(t.x,t.y)])throw Error('Discover a village first.');target=key(t.x,t.y);var full=route(m,target,false);if(full.length<2)throw Error(network(m).has(target)?'Village is already connected.':'No revealed route. Scout a land route or water crossing.');origin=full[0];path=full.slice(1);if(!path.length)throw Error('Village is already connected.');}
  if(kind==='scout'){if(!tile(target)||!d.visible[target]||!neighbors(target).some(function(k){return !d.visible[k];}))throw Error('Choose a revealed tile beside unknown territory.');path=route(m,target,true);if(!path.length)throw Error('Scouts need a known land route or a completed bridge.');var travel=Math.max(1,path.length-1)*20,total=travel*2+60;return {kind:'scout',path:path,target:target,work:[total],revealAt:travel+60,food:20,credits:0,materials:0};}
  if(!defs[kind]&&kind!=='connection')throw Error('Unknown project.');if(!path.length||path.length>60||new Set(path).size!==path.length)throw Error('Choose a valid route or site.');var roads=['connection','road','bridge'].indexOf(kind)>=0,net=network(m);
  path.forEach(function(k,i){var tt=tile(k);if(!tt||!d.visible[k])throw Error('Scout the site first.');if(roads){if((d.roads[k]||d.buildings[k])&&!(kind==='connection'&&d.roads[k]))throw Error('Route crosses an existing road or building.');if(i?neighbors(path[i-1]).indexOf(k)<0:!neighbors(k).some(function(n){return net.has(n);}))throw Error('Route must extend from your connected roads.');if(kind==='road'&&tt.terrain==='water'||kind==='bridge'&&tt.terrain!=='water')throw Error('Use Bridge for water or Connect Village for a mixed route.');var def=tt.terrain==='water'?defs.bridge:defs.road;if(d.roads[k]){work.push(.001);return;}cr+=def.credits;mat+=def.materials;work.push(kind==='connection'&&payload.town===1&&!d.welcomed[1]?30:tt.terrain==='water'?150:100);if(i===0&&kind!=='connection')origin=neighbors(k).find(function(n){return net.has(n);});}
   else {if(path.length!==1)throw Error('Select one building site.');if(k==='0,0'||tt.town)throw Error('This square belongs to HQ or a village.');if(d.buildings[k])throw Error('A building already occupies this square.');if(!d.cleared[k])throw Error('Clear this tile before building here.');if(kind==='farm'&&tt.terrain!=='plain'&&tt.terrain!=='bank')throw Error('Farms need plains or riverbanks.');if(kind==='workshop'&&tt.terrain!=='hill')throw Error('Workshops need hills.');if(tt.terrain==='water')throw Error('Buildings need land. Use a bridge to cross water.');if(kind==='tower'){if(!learned(m,'survey'))throw Error('Research Field Surveying first.');if(tt.terrain!=='hill')throw Error('Scouting Towers require a hill.');if(d.roads[k])throw Error('This hill contains a road. Choose a hill beside the road.');if(!connected(m,k))throw Error('Connect a road beside this hill first.');}cr=defs[kind].credits;mat=defs[kind].materials;work.push(defs[kind].seconds*Math.pow(2,.9));}}
  );return {kind:kind,path:path,origin:origin,target:target,town:payload.town,work:work,credits:cr,materials:mat};
 }
 function placement(m,kind,id,path){try{m=plannedWorld(m);if(s(m).job&&s(m).job.path.slice(s(m).job.done||0).indexOf(id)>=0)throw Error('Site reserved by construction.');var road=kind==='road'||kind==='bridge',route=road&&path&&path.length?(path.indexOf(id)>=0?path:path.concat(id)):[id];plan(m,kind,{id:id,path:route});return {ok:true};}catch(e){return {ok:false,message:e.message};}}
 function researchPreview(m,id,count){try{var state=researchState(m,id);if(!state.ok)return state;var crew=crewCheck(m,count,'study');if(!crew)throw Error('Assign at least one researcher.');var copy=clone(m);s(copy).study={crew:crew};rebalance(copy);return {ok:true,seconds:Math.ceil(state.node.work/Math.pow(crew,.9)),before:economy(m),after:economy(copy)};}catch(e){return {ok:false,message:e.message};}}
 function preview(m,kind,payload,count){try{if(kind!=='scout')m=plannedWorld(m);var p=plan(m,kind,payload),crew=crewCheck(m,count,kind==='scout'?'scout':'job');if(!crew)throw Error('Assign at least one worker to start.');p.crew=crew;p.done=0;p.progress=0;var copy=clone(m),before=rates(m);s(copy)[kind==='scout'?'scout':'job']=p;rebalance(copy);var after=rates(copy);return {ok:true,project:p,seconds:eta(copy,p),before:before,after:after,available:workers(m).available};}catch(e){return {ok:false,message:e.message};}}
 function action(m,save,kind,payload,now){payload=payload||{};return transact(m,save,function(d){var id=payload.id,t=tile(id),b=d.buildings[id];
  if(kind==='target'){if(['farm','workshop'].indexOf(payload.kind)<0)throw Error('Unknown production target.');var n=Number(payload.count);if(!Number.isInteger(n)||n<0||n>d.population)throw Error('Target must be between zero and population.');d.targets[payload.kind]=n;return 'Staffing target saved. Available crews fill production automatically.';}
  if(kind==='protect'){d.protectFood=!!payload.enabled;return 'Food protection '+(d.protectFood?'enabled.':'disabled. Watch your Food balance.');}
  if(kind==='crew'){var type=payload.type;if(['job','scout','study'].indexOf(type)<0||!d[type])throw Error('No active crew.');d[type].crew=crewCheck(m,payload.count,type);d.defaultCrew=Math.max(1,d[type].crew);return d[type].crew?'Crew reassigned; production adjusted.':'Crew recalled. Work is paused and progress preserved.';}
  if(kind==='build'||kind==='connection'||kind==='scout'){var type=kind==='scout'?'scout':'job',queued=type==='job'&&(d.job||(d.queue||[]).length),source=queued?plannedWorld(m):m;if(type==='scout'&&d.scout)throw Error('Finish or resume the existing expedition.');if(queued&&(d.queue||[]).length>=3)throw Error('Construction queue is full (3 waiting projects).');var projectKind=kind==='build'?payload.type:kind,p=plan(source,projectKind,payload);p.crew=crewCheck(source,payload.crew||d.defaultCrew||2,type);if(!p.crew)throw Error('Assign workers.');if(m.credits<p.credits||d.materials<p.materials||d.food<(p.food||0))throw Error('Not enough resources.');m.credits-=p.credits;d.materials-=p.materials;d.food-=p.food||0;p.done=0;p.progress=0;if(queued){d.queue=d.queue||[];d.queueSerial=(d.queueSerial||0)+1;d.queue.push({id:d.queueSerial,kind:projectKind,payload:clone(payload),crew:p.crew,project:p,credits:p.credits,materials:p.materials});return 'Project queued. Costs reserved; workers join when it starts.';}d[type]=p;d.defaultCrew=p.crew;return p.crew+' workers assigned. Production adjusted until they return.';}
  if(kind==='cancelQueue'){var index=(d.queue||[]).findIndex(function(q){return q.id===payload.queueId;});if(index<0)throw Error('Queued project no longer exists.');var q=d.queue.splice(index,1)[0];m.credits+=q.credits;d.materials+=q.materials;d.queueNotice='';return 'Queued project cancelled. Reserved Credits and Materials refunded.';}
  if(kind==='trade'){var resource=payload.resource;if(resource!=='food'&&resource!=='materials')throw Error('Choose Food or Materials.');if(!towns.some(function(t){return active(m,t.id);}))throw Error('Integrate and connect a village to trade.');var reserve=resource==='food'?Math.max(60,d.population*2.5):60;if(d[resource]<reserve+100)throw Error('Trade needs 100 surplus '+resource+' above the '+reserve+' reserve.');d[resource]-=100;m.credits+=50;return 'Traded 100 '+resource+' for 50 Credits. Reserve preserved.';}
  if(kind==='clear'){if(!t||!d.visible[id]||t.terrain==='water'||d.cleared[id]||!neighbors(id).some(function(k){return d.cleared[k];}))throw Error('Choose land beside your accessible territory.');d.cleared[id]=true;if(!t.town&&Math.abs(t.x*13+t.y*7)%17===0){d.materials+=10;m.credits+=50;emit(m,id,'Supply cache: +10 Materials, +50 Credits.');return d.notice;}return 'Land cleared. Connection crews clear their own route automatically.';}
  if(kind==='welcome'){var village=town(payload.town);if(!village||!d.defended[village.id]||d.welcomed[village.id]||!network(m).has(key(village.x,village.y)))throw Error('Defend and connect this village first.');if(housing(m)<d.population+4||d.food<20)throw Error('Provide 4 housing spaces and 20 Food.');d.food-=20;d.population+=4;d.welcomed[village.id]=true;emit(m,key(village.x,village.y),'+4 residents · +'+(2*stars(village.id)+(village.id===6?4:0))+' Credits/min');return village.name+' integrated. '+village.benefit+'. Staffing targets fill automatically.';}
  if(kind==='demolish'){if(id==='0,0'||!b&&!d.roads[id])throw Error('Choose a building or road.');if(d.job||d.scout||(d.queue||[]).length)throw Error('Finish or cancel construction and scouting before removing infrastructure.');if(b&&b.kind==='house'&&housing(m)-4<d.population)throw Error('Build replacement housing first.');var refund=Math.floor((b?defs[b.kind]:t.terrain==='water'?defs.bridge:defs.road).materials/2);if(b)delete d.buildings[id];else delete d.roads[id];d.materials+=refund;return 'Removed. +'+refund+' Materials returned. Staffing redistributed.';}
  if(kind==='research'){var state=researchState(m,payload.node||'tools');if(!state.ok)throw Error(state.message);var n=state.node,crew=crewCheck(m,payload.crew||d.defaultCrew||2,'study');if(!crew)throw Error('Assign researchers.');if(m.credits<n.credits||d.materials<n.materials)throw Error('Requires '+n.credits+' Credits and '+n.materials+' Materials.');m.credits-=n.credits;d.materials-=n.materials;d.study={kind:'study',node:n.id,crew:crew,path:['0,0'],target:'0,0',work:[n.work],done:0,progress:0};return n.name+' started. '+crew+' residents researching at HQ. Production adjusted until they return.';}
  throw Error('Unknown action.');
 },now);}
 function ready(m,n){var t=town(n);return !!(s(m)&&t&&s(m).visible[key(t.x,t.y)]&&!s(m).defended[n]);}
 function win(m,n){if(!ready(m,n))return false;advance(m,Date.now());s(m).defended[n]=true;var t=town(n);s(m).focus=key(t.x,t.y);emit(m,s(m).focus,'Village defended. Connect roads and welcome survivors.');return true;}
 function frontier(m){return Object.keys(tiles).filter(function(k){return s(m).visible[k]&&tile(k).terrain!=='water'&&neighbors(k).some(function(n){return !s(m).visible[n];});}).sort(function(a,b){return Math.abs(tile(a).x-5)+Math.abs(tile(a).y)-Math.abs(tile(b).x-5)-Math.abs(tile(b).y);})[0];}
 function objective(m){var d=s(m),t=towns.find(function(t){return d.visible[key(t.x,t.y)]&&!d.welcomed[t.id];});if(t){var id=key(t.x,t.y);if(d.job&&d.job.town===t.id)return {id:id,text:'Connecting '+t.name+' · crew progress on map'};if(!d.defended[t.id])return {id:id,text:'Bring '+t.name+' survivors home · defend village'};if(!network(m).has(id))return {id:id,text:'Bring survivors home · connect '+t.name};if(housing(m)<d.population+4)return {id:'0,0',text:'Build housing · 4 spaces needed for '+t.name};return {id:id,text:'Welcome 4 survivors from '+t.name};}return {id:d.scout?d.scout.target:frontier(m),text:d.scout?'Scouts exploring · manage production or build':'Discover the next village · choose a scouting frontier'};}
 root.LSCSettlement={initialize:initialize,action:action,advance:advance,tick:function(m,save,now){return transact(m,save,function(){},now);},ready:ready,win:win,objective:objective,workers:workers,housing:housing,rates:rates,income:income,connected:connected,network:network,defs:defs,tiles:tiles,tile:tile,towns:towns,town:town,stars:stars,combat:combat,storage:storage,economy:economy,knowledge:knowledge,learned:learned,researchState:researchState,researchPreview:researchPreview,placement:placement,towerArea:towerArea,plannedWorld:plannedWorld,preview:preview,eta:eta,speed:speed,remaining:remaining,rebalance:rebalance,foodMinimum:foodMinimum,capacity:capacity};
})(typeof window!=='undefined'?window:globalThis);
