(function(root){
 'use strict';
 // Keep the 204 save key and map coordinates; upgrade the rules in place.
 var old=root.LSCSettlement,tiles=old.tiles,defs=old.defs;
 defs.clear={name:'Clear Land',credits:0,materials:0,capacity:0,seconds:20};
 function jobs(m){var d=s(m);return (d.job?[d.job]:[]).concat(d.projects||[]);}
 function constructionCrew(m){return jobs(m).reduce(function(n,j){return n+j.crew;},0);}
 function addJob(m,p){var d=s(m);d.projectSerial=(d.projectSerial||0)+1;p.projectId=d.projectSerial;if(!d.job)d.job=p;else(d.projects||(d.projects=[])).push(p);}
 function blockedSite(m,id){return jobs(m).some(function(j){return j.path.slice(j.done||0).indexOf(id)>=0;});}
 defs.tower={name:'Scouting Tower',credits:180,materials:60,capacity:0,seconds:60};
 function towerArea(m,id){var t=tiles[id];if(!t)return [];return Object.keys(tiles).filter(function(k){return Math.max(Math.abs(tiles[k].x-t.x),Math.abs(tiles[k].y-t.y))<=8;});}
 function projectFinished(m,p){var d=s(m);if(p.kind==='shipping'){(d.seaRoutes||(d.seaRoutes=[])).push({from:p.origin,to:p.target,path:p.waterPath});return;}p.path.slice(p.done||0).forEach(function(k){d.cleared[k]=true;if(['connection','road','bridge'].indexOf(p.kind)>=0)d.roads[k]=true;else if(p.kind!=='clear')d.buildings[k]={kind:p.kind,workers:0};});}
 function plannedWorld(m){var copy=clone(m),d=s(copy);jobs(copy).forEach(function(p){projectFinished(copy,p);});d.job=null;d.projects=[];(d.queue||[]).forEach(function(q){projectFinished(copy,q.project);});d.queue=[];return copy;}
 function startQueue(m){var d=s(m);if(!d.queue||!d.queue.length)return;var pending=d.queue.slice();d.queueNotice='';pending.forEach(function(q){try{var p=plan(m,q.kind,Object.assign({},q.payload,{legacyClearing:q.food===undefined}));if(p.path.slice(p.done||0).some(function(k){return blockedSite(m,k);}))throw Error('Site reserved by another crew.');p.crew=crewCheck(m,q.crew,'new');if(!p.crew)throw Error('Waiting for workers.');if(p.credits>q.credits||p.materials>q.materials||(p.food||0)>(q.food||0))throw Error('Route changed. Cancel and plan this project again.');m.credits+=q.credits-p.credits;d.materials+=q.materials-p.materials;d.food+=(q.food||0)-(p.food||0);p.done=0;p.progress=0;p.batch=q.project.batch;d.queue.splice(d.queue.indexOf(q),1);addJob(m,p);emit(m,p.path[0],'Project started · '+p.crew+' workers');}catch(e){d.queueNotice=e.message;}});}
 var knowledge=[
  {id:'tools',name:'Better Tools',credits:200,materials:30,work:120,requires:[],effect:'+20% workshop Materials output'},
  {id:'survey',name:'Field Surveying',credits:100,materials:25,work:180,requires:['tools'],effect:'+25% scout work speed; surveys reveal radius 4 instead of 3'},
  {id:'logistics',name:'Organized Construction',credits:150,materials:40,work:240,requires:['tools'],effect:'+20% construction and village connection work speed'},
  {id:'stores',name:'Village Storehouses',credits:200,materials:60,work:300,requires:['logistics'],village:1,effect:'+300 Food and Materials storage capacity'}
 ];
 knowledge.forEach(function(n){n.branch=({tools:'Industry',survey:'Exploration',logistics:'Construction',stores:'Industry'})[n.id];});
 knowledge=knowledge.concat([{"id": "cultivation", "name": "Crop Rotation", "branch": "Agriculture", "credits": 100, "materials": 20, "work": 90, "requires": [], "effect": "+15% Food per farmer"}, {"id": "irrigation", "name": "Irrigation", "branch": "Agriculture", "credits": 220, "materials": 50, "work": 180, "requires": ["cultivation"], "effect": "Another +15% Food per farmer"}, {"id": "preservation", "name": "Food Preservation", "branch": "Agriculture", "credits": 260, "materials": 60, "work": 210, "requires": ["irrigation"], "effect": "Residents consume 10% less Food"}, {"id": "housing", "name": "Room Planning", "branch": "Construction", "credits": 240, "materials": 50, "work": 180, "requires": ["logistics"], "effect": "Each housing building provides 6 spaces instead of 4"}, {"id": "roads", "name": "Road Engineering", "branch": "Construction", "credits": 180, "materials": 40, "work": 150, "requires": ["logistics"], "effect": "Road and bridge construction work reduced 20%"}, {"id": "clearing", "name": "Land Management", "branch": "Construction", "credits": 120, "materials": 25, "work": 120, "requires": ["tools"], "effect": "Land clearing work reduced 25%"}, {"id": "trailcraft", "name": "Trailcraft", "branch": "Exploration", "credits": 150, "materials": 30, "work": 150, "requires": ["survey"], "effect": "Scouts work 20% faster"}, {"id": "provisions", "name": "Expedition Supplies", "branch": "Exploration", "credits": 160, "materials": 30, "work": 150, "requires": ["survey"], "effect": "Scouting costs 15 Food instead of 20"}, {"id": "optics", "name": "Survey Optics", "branch": "Exploration", "credits": 300, "materials": 70, "work": 240, "requires": ["trailcraft"], "effect": "Survey radius +1 tile; tower radius stays 8"}, {"id": "smelting", "name": "Efficient Workshops", "branch": "Industry", "credits": 240, "materials": 60, "work": 210, "requires": ["tools"], "effect": "Another +20% Materials per workshop worker"}, {"id": "barter", "name": "Trade Agreements", "branch": "Industry", "credits": 200, "materials": 40, "work": 180, "requires": ["stores"], "effect": "100 surplus resources trade for 65 Credits instead of 50"}, {"id": "drills", "name": "Defense Drills", "branch": "Defense", "credits": 180, "materials": 40, "work": 150, "requires": ["tools"], "effect": "+10% commander and turret damage in town defenses"}, {"id": "fortifications", "name": "Field Fortifications", "branch": "Defense", "credits": 220, "materials": 60, "work": 180, "requires": ["drills"], "effect": "+15% command-post health in town defenses"}, {"id": "artillery", "name": "Artillery Coordination", "branch": "Defense", "credits": 280, "materials": 70, "work": 240, "requires": ["fortifications"], "effect": "+15% ability damage in town defenses"}]);
 function learned(m,id){return id==='tools'?!!s(m).tools:!!(s(m).knowledge&&s(m).knowledge[id]);}
 function researchState(m,id){var n=knowledge.find(function(n){return n.id===id;});if(!n)return {ok:false,message:'Unknown knowledge.'};if(learned(m,id))return {ok:false,message:'Acquired'};var missing=n.requires.filter(function(k){return !learned(m,k);});if(missing.length)return {ok:false,message:'Requires '+missing.map(function(k){return knowledge.find(function(n){return n.id===k;}).name;}).join(', ')};if(n.village&&!active(m,n.village))return {ok:false,message:'Integrate and connect '+town(n.village).name};if(s(m).study)return {ok:false,readyNext:true,node:n,message:'Ready next · research slot occupied. Finish or resume the active research.'};if(s(m).population-constructionCrew(m)-(s(m).scout?s(m).scout.crew:0)-foodMinimum(m)<1)return {ok:false,message:'Assign fewer workers to existing projects to free a researcher'};if(m.credits<n.credits||s(m).materials<n.materials)return {ok:false,message:'Needs '+n.credits+' Credits and '+n.materials+' Materials'};return {ok:true,node:n};}
 var towns=[
  {id:1,x:5,y:0,name:'Brookhaven',specialty:'A safe foothold',benefit:'4 residents and +2 Credits/min'},
  {id:2,x:5,y:5,name:'Millfield',specialty:'Agriculture',benefit:'Connected farms produce 10% more Food'},
  {id:3,x:-5,y:4,name:'Ironridge',specialty:'Industry',benefit:'Connected workshops produce 10% more Materials'},
  {id:4,x:-5,y:-5,name:'Highwatch',specialty:'Exploration',benefit:'Scouting crews work 15% faster'},
  {id:5,x:10,y:0,name:'Stoneford',specialty:'Construction',benefit:'Construction crews work 10% faster'},
  {id:6,x:10,y:7,name:'Port Mercer',specialty:'Trade',benefit:'+4 extra Credits/min'}
 ];

 // Original coordinates and saves are immutable. Only the surrounding frontier grows.
 var bounds={minX:-28,maxX:32,minY:-24,maxY:24};
 for(var yy=bounds.minY;yy<=bounds.maxY;yy++)for(var xx=bounds.minX;xx<=bounds.maxX;xx++){
  var kk=key(xx,yy);if(tiles[kk])continue;
  var sea=xx===7||xx>=14&&xx<=17||yy>=15&&yy<=17&&xx>=7;
  tiles[kk]={id:kk,x:xx,y:yy,terrain:sea?'water':xx===6||xx===8||xx===13||xx===18?'bank':Math.abs(xx*3+yy*7)%9<3?'hill':'plain'};
 }
 towns=towns.concat([
  {id:7,x:-16,y:4,name:'Pineguard',stars:3,theme:'woodland'},
  {id:8,x:-18,y:-14,name:'Ashfall',stars:4,theme:'industrial'},
  {id:9,x:22,y:5,name:'Eastport',stars:4,theme:'harbor'},
  {id:10,x:25,y:-12,name:'Crown Heights',stars:5,theme:'highland'},
  {id:11,x:10,y:21,name:'Southbank',stars:4,theme:'river'},
  {id:12,x:25,y:21,name:'Golden Fields',stars:5,theme:'farmland'}
 ]);
 towns.forEach(function(t){if(t.id>6){tiles[key(t.x,t.y)].town=t.id;tiles[key(t.x,t.y)].terrain='plain';t.specialty='Regional settlement';t.benefit='4 residents and +'+(2*t.stars)+' Credits/min';}});
 defs.harbor={name:'Harbor',credits:200,materials:80,capacity:0,seconds:90};
 defs.shipping={name:'Water Route',credits:100,materials:20,capacity:0,seconds:60};
 var landmarks=[{id:'-14,2',name:'Ranger Storehouse',materials:80,food:40,credits:150},{id:'-20,-12',name:'Abandoned Foundry',materials:150,food:0,credits:200},{id:'20,3',name:'Merchant Wreck',materials:80,food:40,credits:350},{id:'23,-10',name:'Highland Granary',materials:40,food:180,credits:300},{id:'10,20',name:'River Caravan',materials:80,food:80,credits:300},{id:'23,20',name:'Harvest Reserve',materials:60,food:200,credits:400}];
 landmarks.forEach(function(l){tiles[l.id].landmark=l;tiles[l.id].terrain='plain';});
 function coastal(id){return !!tile(id)&&tile(id).terrain!=='water'&&neighbors(id).some(function(k){return tile(k).terrain==='water';});}
 function harbor(m,id){return !!(s(m).buildings[id]&&s(m).buildings[id].kind==='harbor');}
 function ports(m){return Object.keys(s(m).buildings).filter(function(k){return harbor(m,k);});}
 function waterRoute(m,from,to){var d=s(m),q=neighbors(from).filter(function(k){return tile(k).terrain==='water'&&d.visible[k];}),prev={};q.forEach(function(k){prev[k]=from;});for(var i=0;i<q.length;i++){var k=q[i];if(neighbors(k).indexOf(to)>=0){var path=[to];while(k!==from){path.unshift(k);k=prev[k];}path.unshift(from);return path;}neighbors(k).forEach(function(n){if(tile(n).terrain==='water'&&d.visible[n]&&prev[n]===undefined){prev[n]=k;q.push(n);}});}return [];}
 var themes=['woodland','farmland','industrial','highland','river','harbor'];
 function townProfile(n){var t=town(n);if(!t)return null;var theme=t.theme||themes[t.id-1],threat={woodland:'Mixed walkers and runners',farmland:'Fast runners among the horde',industrial:'More armored infected',highland:'Armored infected and fast runners',river:'Mixed waves at the river crossing',harbor:'Runner-heavy waves around the docks'}[theme];return {id:t.id,name:t.name,stars:stars(n),theme:theme,threat:threat};}
 function s(m){return m.settlement204;} function clone(v){return JSON.parse(JSON.stringify(v));}
 function key(x,y){return x+','+y;} function tile(id){return tiles[id];}
 function town(n){return towns.find(function(t){return t.id===Number(n);});}
 function neighbors(id){var t=tile(id);return t?[[1,0],[0,1],[-1,0],[0,-1]].map(function(v){return key(t.x+v[0],t.y+v[1]);}).filter(tile):[];}
 function network(m){var d=s(m),set=new Set(['0,0']),q=['0,0'];for(var i=0;i<q.length;i++){var current=q[i],next=neighbors(current).filter(function(k){return d.roads[k]||harbor(m,k);});(d.seaRoutes||[]).forEach(function(r){if(harbor(m,r.from)&&harbor(m,r.to)){if(r.from===current)next.push(r.to);if(r.to===current)next.push(r.from);}});next.forEach(function(k){if(!set.has(k)){set.add(k);q.push(k);}});}return set;}
 function connected(m,id){var net=network(m);return net.has(id)||neighbors(id).some(function(k){return net.has(k);});}
 function active(m,n){var t=town(n);return !!(s(m).welcomed[n]&&network(m).has(key(t.x,t.y)));}
 function stars(n){var t=town(n);return t&&t.stars||old.stars(n);} function combat(n){return Number(n)<=6?old.combat(n):1+(stars(n)-1)*5;}
 function houseSpaces(m){return learned(m,'housing')?6:4;} function housing(m){return 12+Object.keys(s(m).buildings).filter(function(k){return s(m).buildings[k].kind==='house';}).length*houseSpaces(m);} function storage(m){return 500+(housing(m)-12)*25+(learned(m,'stores')?300:0);}
 function capacity(m,kind){return Object.keys(s(m).buildings).reduce(function(n,k){var b=s(m).buildings[k];return n+(b.kind===kind&&connected(m,k)?defs[kind].capacity:0);},0);}
 function foodUse(m){return s(m).population*.25*(learned(m,'preservation')?.9:1);} function farmRate(m){return 3*(active(m,2)?1.1:1)*(learned(m,'cultivation')?1.15:1)*(learned(m,'irrigation')?1.15:1);} function materialRate(m){return 2*(s(m).tools?1.2:1)*(active(m,3)?1.1:1)*(learned(m,'smelting')?1.2:1);}
 function foodMinimum(m){return s(m).protectFood?Math.min(capacity(m,'farm'),Math.ceil((foodUse(m)+1)/farmRate(m))):0;}
 function workers(m){var d=s(m),assigned=Object.keys(d.buildings).reduce(function(n,k){return n+d.buildings[k].workers;},0),scouts=d.scout?d.scout.crew:0,builders=constructionCrew(m),scholars=d.study?d.study.crew:0;return {total:d.population,assigned:assigned,scouts:scouts,builders:builders,scholars:scholars,available:d.population-assigned-scouts-builders-scholars};}
 function rebalance(m){var d=s(m),free=d.population-constructionCrew(m)-(d.scout?d.scout.crew:0)-(d.study?d.study.crew:0);if(d.priority&&d.priority!=='manual'){var surplus=d.priority==='exploration'?6:d.priority==='growth'?1:3;d.targets.farm=Math.min(capacity(m,'farm'),Math.ceil((foodUse(m)+surplus)/farmRate(m)));d.targets.workshop=Math.min(capacity(m,'workshop'),Math.max(0,free-d.targets.farm-(d.priority==='exploration'?2:0)));}Object.keys(d.buildings).forEach(function(k){d.buildings[k].workers=0;});
  ['farm','workshop'].forEach(function(kind){var target=Math.min(free,Math.max(d.targets[kind]||0,kind==='farm'?foodMinimum(m):0));if(kind==='workshop'&&d.materials>=storage(m))target=0;if(kind==='farm'&&d.food>=storage(m))target=Math.min(target,Math.ceil(foodUse(m)/farmRate(m)));Object.keys(d.buildings).sort().forEach(function(k){var b=d.buildings[k];if(b.kind!==kind||!connected(m,k))return;var n=Math.min(target,defs[kind].capacity);b.workers=n;target-=n;free-=n;});});
 }
 function income(m){return 2+towns.reduce(function(n,t){return n+(active(m,t.id)?2*stars(t.id)+(t.id===6?4:0):0);},0);}
 function rates(m){var d=s(m),food=0,materials=0;Object.keys(d.buildings).forEach(function(k){var b=d.buildings[k];if(!connected(m,k))return;if(b.kind==='farm')food+=b.workers*farmRate(m);if(b.kind==='workshop')materials+=b.workers*materialRate(m);});return {food:food-foodUse(m),materials:materials,credits:income(m)};}
 function economy(m){var d=s(m),r=rates(m),cap=storage(m),consumption=foodUse(m);return {capacity:cap,foodGross:r.food+consumption,foodUse:consumption,foodNet:d.food>=cap?Math.min(0,r.food):d.food<=0?Math.max(0,r.food):r.food,materialsNet:d.materials>=cap?0:r.materials*(d.food<=0&&r.food<=0?.5:1),foodFull:d.food>=cap,materialsFull:d.materials>=cap,shortage:d.food<=0&&r.food<=0};}
 function speed(m,job){if(!job||!job.crew)return 0;return Math.pow(job.crew,.9)*(job.kind==='study'?1:job.kind==='scout'?(active(m,4)?1.15:1)*(learned(m,'survey')?1.25:1)*(learned(m,'trailcraft')?1.2:1):(active(m,5)?1.1:1)*(learned(m,'logistics')?1.2:1));}
 function remaining(job){if(!job)return 0;return job.work.slice(job.done||0).reduce(function(a,b){return a+b;},0)-(job.progress||0);}
 function eta(m,job){var v=speed(m,job);return v?Math.ceil(remaining(job)/v):null;}
 function emit(m,id,text){var d=s(m);d.notice=text;d.event={id:id,text:text,at:d.at};}
 function reveal(m,id,r){var t=tile(id),d=s(m);for(var y=-r;y<=r;y++)for(var x=-r;x<=r;x++){var k=key(t.x+x,t.y+y);if(tile(k))d.visible[k]=true;}}
 function accrue(m,seconds){var d=s(m),r=rates(m),minutes=seconds/60,fed=minutes;if(r.food<0)fed=Math.min(minutes,d.food/-r.food);else if(d.food<=0&&r.food===0)fed=0;var cap=storage(m);d.food=Math.max(0,Math.min(Math.max(cap,d.food),d.food+r.food*minutes));d.materials=Math.min(Math.max(cap,d.materials),d.materials+r.materials*(fed+(minutes-fed)*.5));var cr=(d.creditCarry||0)+r.credits*minutes;m.credits+=Math.floor(cr);d.creditCarry=cr-Math.floor(cr);}
 function finish(m,type,project){var d=s(m),j=project||d[type];if(!j)return;var index=j.done||0;
  if(type==='study'){if(j.progress+1e-6>=j.work[0]){d.knowledge=d.knowledge||{};d.knowledge[j.node]=true;if(j.node==='tools')d.tools=true;d.study=null;var n=knowledge.find(function(n){return n.id===j.node;});emit(m,'0,0',n.name+' acquired');d.notice=n.name+': '+n.effect+'. Researchers returned to the workforce.';}return;}
  if(type==='scout'){if(!j.revealed&&j.progress>=j.revealAt){var area=surveyArea(m,j.target),unseen=area.filter(function(k){return !d.visible[k];}),villages=unseen.filter(function(k){return tile(k).town;});reveal(m,j.target,surveyRadius(m));j.revealed=true;d.scouted=true;d.discovery={tiles:unseen.length,villages:villages.length,at:d.at};emit(m,j.target,'Survey: '+unseen.length+' new tiles · '+villages.length+' villages. Returning.');}if(j.progress+1e-6>=j.work[0]){d.scout=null;emit(m,j.target,'Scouts returned. Crew available for reassignment.');}}
  else if(j.progress+1e-6>=j.work[index]){if(j.kind==='shipping'){projectFinished(m,j);if(d.job===j)d.job=null;else d.projects=d.projects.filter(function(p){return p!==j;});emit(m,j.target,'Water route connected · coastal roads now supply your settlement');return;}var id=j.path[index];d.cleared[id]=true;if(j.kind==='connection'||j.kind==='road'||j.kind==='bridge')d.roads[id]=true;else if(j.kind!=='clear')d.buildings[id]={kind:j.kind,workers:0};var discovery='';if(j.kind==='clear'||tile(id).landmark){var tt=tile(id);if(tt.landmark&&!(d.claimed&&d.claimed[id])){var reward=tt.landmark;d.claimed=d.claimed||{};d.claimed[id]=true;d.materials+=reward.materials;d.food+=reward.food;m.credits+=reward.credits;discovery=reward.name+' · +'+reward.credits+' Credits · +'+reward.materials+' Materials · +'+reward.food+' Food';}else if(!tt.town&&!tt.landmark&&Math.abs(tt.x*13+tt.y*7)%17===0){d.materials+=10;m.credits+=50;discovery='+50 Credits · +10 Materials';}}var unveiled=0;if(j.kind==='tower'){towerArea(m,id).forEach(function(k){if(!d.visible[k])unveiled++;d.visible[k]=true;});}j.progress=0;j.done=index+1;if(j.done>=j.path.length){if(d.job===j)d.job=null;else d.projects=d.projects.filter(function(p){return p!==j;});emit(m,id,discovery|| (j.kind==='tower'?'Tower surveyed: '+unveiled+' new tiles':(j.kind==='connection'?'Village connection':defs[j.kind].name)+' complete. Crew released.'));}}
 }
 function advance(m,now){var d=s(m);jobs(m).forEach(function(j){if(!j.projectId){d.projectSerial=(d.projectSerial||0)+1;j.projectId=d.projectSerial;}});now=Math.max(d.at,Number(now)||d.at);var limit=Math.min(now,d.at+8*3600000);startQueue(m);rebalance(m);
  while(d.at+0.001<limit){var seconds=(limit-d.at)/1000,list=jobs(m).concat(d.scout?[d.scout]:[],d.study?[d.study]:[]);list.forEach(function(j){var v=speed(m,j);if(v){var edge=j.work[j.done||0];if(j.kind==='scout'&&!j.revealed)edge=j.revealAt;seconds=Math.min(seconds,Math.max(0,(edge-j.progress)/v));}});
   if(seconds>0){accrue(m,seconds);list.forEach(function(j){j.progress+=seconds*speed(m,j);});d.at+=seconds*1000;}
   var before=JSON.stringify(list);finish(m,'scout');jobs(m).slice().forEach(function(j){finish(m,'job',j);});finish(m,'study');if(!d.job&&(d.projects||[]).length)d.job=d.projects.shift();startQueue(m);rebalance(m);if(seconds===0&&before===JSON.stringify(jobs(m).concat(d.scout?[d.scout]:[],d.study?[d.study]:[])))break;
  }d.at=now;
 }
 function initialize(m,save,now){now=now===undefined?Date.now():now;var existed=!!s(m),snapshot=clone(m);if(!existed){var result=old.initialize(m,function(){return true;},now);if(!result.ok)return result;}
  if(s(m).version>=205)return {ok:true};var d=s(m);d.targets={farm:0,workshop:0};Object.keys(d.buildings).forEach(function(k){var b=d.buildings[k];if(d.targets[b.kind]!==undefined)d.targets[b.kind]+=b.workers||0;});if(!existed){d.targets={farm:2,workshop:4};d.priority='balanced';d.food=360;d.materials=320;}d.protectFood=true;d.defaultCrew=4;d.version=205;
  ['job','scout'].forEach(function(type){var j=d[type];if(!j)return;var seconds=Math.max(.1,(j.end-d.at)/1000);if(type==='scout')d.scout={kind:'scout',crew:2,path:['0,0',j.target],target:j.target,work:[seconds*Math.pow(2,.9)],done:0,progress:0,revealAt:seconds*Math.pow(2,.9)*.7,revealed:false};else d.job={kind:j.kind,crew:2,path:j.path,work:j.path.map(function(){return seconds*Math.pow(2,.9)/j.path.length;}),done:0,progress:0};});rebalance(m);d.notice='205: production targets distribute workers automatically. Existing resources and projects are preserved.';
  try{if(save()!==true)throw Error('save');return {ok:true};}catch(e){Object.keys(m).forEach(function(k){delete m[k];});Object.assign(m,snapshot);return {ok:false,message:'Upgrade could not save. Campaign unchanged.'};}
 }
 function transact(m,save,fn,now){var snapshot=clone(s(m)),credits=m.credits;try{advance(m,now===undefined?Date.now():now);var text=fn(s(m));startQueue(m);rebalance(m);if(text)s(m).notice=text;if(save()!==true)throw Error('Save failed. Changes were rolled back.');return {ok:true,message:text||s(m).notice};}catch(e){m.settlement204=snapshot;m.credits=credits;return {ok:false,message:e.message};}}
 // Dijkstra route: known squares only; bridge costs discourage unnecessary water crossings.
 function route(m,target,scouting){var d=s(m),net=network(m),boat=ports(m).some(function(k){return net.has(k);}),dist={},prev={},open=[];net.forEach(function(k){dist[k]=0;prev[k]=null;open.push(k);});
  while(open.length){open.sort(function(a,b){return dist[a]-dist[b];});var k=open.shift();if(k===target){var result=[];while(k!==null){result.unshift(k);k=prev[k];}return result;}
   neighbors(k).forEach(function(n){var t=tile(n);if(!d.visible[n]||scouting&&t.terrain==='water'&&!d.roads[n]&&(!boat||tile(k).terrain!=='water'&&!harbor(m,k))||!scouting&&d.buildings[n]&&!d.roads[n])return;var cost=dist[k]+(d.roads[n]?0.01:t.terrain==='water'?5:1);if(dist[n]===undefined||cost<dist[n]){dist[n]=cost;prev[n]=k;if(open.indexOf(n)<0)open.push(n);}});
  }return [];
 }
 function crewCheck(m,count,type,projectId){count=Number(count);if(!Number.isInteger(count)||count<0||count>6)throw Error('Choose 0–6 workers.');var d=s(m),reserved=constructionCrew(m)+(type!=='scout'&&d.scout?d.scout.crew:0)+(type!=='study'&&d.study?d.study.crew:0);if(type==='job'){var j=projectId?jobs(m).find(function(j){return j.projectId===projectId;}):d.job;if(j)reserved-=j.crew;}var budget=d.population-reserved-foodMinimum(m);if(count>budget)throw Error('Only '+Math.max(0,budget)+' workers available after Food protection and other crews.');return count;}
 function plan(m,kind,payload){payload=payload||{};var d=s(m),path=payload.path||[payload.id],origin='0,0',cr=0,mat=0,food=0,work=[],target=payload.id;
  if(kind==='shipping'){var from=payload.from,to=payload.id;if(!harbor(m,from)||!harbor(m,to)||from===to)throw Error('Select two completed harbors.');if(!network(m).has(from))throw Error('Connect the departure harbor to HQ first.');if((d.seaRoutes||[]).some(function(r){return r.from===from&&r.to===to||r.to===from&&r.from===to;}))throw Error('These harbors already have a water route.');var sea=waterRoute(m,from,to);if(!sea.length)throw Error('Scout a continuous water route between these harbors first.');return {kind:'shipping',path:[to],origin:from,target:to,waterPath:sea,work:[Math.max(60,(sea.length-2)*20)],credits:100,materials:20,food:20};}
  if(kind==='clear'){if(!tile(target)||!d.visible[target]||tile(target).terrain==='water'||tile(target).town||target==='0,0'||d.cleared[target]||!neighbors(target).some(function(k){return d.cleared[k];})&&!(coastal(target)&&route(m,target,true).some(function(k){return tile(k).terrain==='water'&&!d.roads[k];})))throw Error('Choose uncleared land beside your territory, or a scouted coast reachable by boat.');return {kind:'clear',path:[target],target:target,work:[(tile(target).terrain==='hill'?60:30)*(learned(m,'clearing')?.75:1)],food:tile(target).terrain==='hill'?8:4,credits:0,materials:0};}
  if(kind==='connection'){var t=town(payload.town);if(!t||!d.visible[key(t.x,t.y)])throw Error('Discover a village first.');target=key(t.x,t.y);var full=route(m,target,false);if(full.length<2)throw Error(network(m).has(target)?'Village is already connected.':'No revealed route. Scout a land route or water crossing.');origin=full[0];path=full.slice(1);if(!path.length)throw Error('Village is already connected.');}
  if(kind==='scout'){if(!tile(target)||!d.visible[target]||!neighbors(target).some(function(k){return !d.visible[k];}))throw Error('Choose a revealed tile beside unknown territory.');path=route(m,target,true);if(!path.length)throw Error('Scouts need a known route. Cross water using a bridge or embark from a connected harbor.');var travel=Math.max(1,path.length-1)*20,total=travel*2+60;return {kind:'scout',path:path,target:target,work:[total],revealAt:travel+60,food:learned(m,'provisions')?15:20,credits:0,materials:0};}
  if(!defs[kind]&&kind!=='connection')throw Error('Unknown project.');if(!path.length||path.length>60||new Set(path).size!==path.length)throw Error('Choose a valid route or site.');var roads=['connection','road','bridge'].indexOf(kind)>=0,net=network(m);
  path.forEach(function(k,i){var tt=tile(k);if(!tt||!d.visible[k])throw Error('Scout the site first.');if(roads){if((d.roads[k]||d.buildings[k])&&!(kind==='connection'&&d.roads[k]))throw Error('Route crosses an existing road or building.');if(i?neighbors(path[i-1]).indexOf(k)<0:!neighbors(k).some(function(n){return net.has(n);}))throw Error('Route must extend from your connected roads.');if(kind==='road'&&tt.terrain==='water'||kind==='bridge'&&tt.terrain!=='water')throw Error('Use Bridge for water or Connect Village for a mixed route.');var def=tt.terrain==='water'?defs.bridge:defs.road;if(d.roads[k]){work.push(.001);return;}cr+=def.credits;mat+=def.materials;if(!payload.legacyClearing&&!d.cleared[k]&&tt.terrain!=='water')food+=tt.terrain==='hill'?8:4;work.push((kind==='connection'&&payload.town===1&&!d.welcomed[1]?30:tt.terrain==='water'?150:100)*(learned(m,'roads')?.8:1));if(!d.cleared[k]&&tt.terrain!=='water')work[work.length-1]+=(tt.terrain==='hill'?60:30)*(learned(m,'clearing')?.75:1);if(i===0&&kind!=='connection')origin=neighbors(k).find(function(n){return net.has(n);});}
   else {if(path.length!==1)throw Error('Select one building site.');if(k==='0,0'||tt.town)throw Error('This square belongs to HQ or a village.');if(d.buildings[k]||d.roads[k])throw Error('A building or road already occupies this square.');if(!d.cleared[k])throw Error('Clear this tile before building here.');if(kind==='farm'&&tt.terrain!=='plain'&&tt.terrain!=='bank')throw Error('Farms need plains or riverbanks.');if(kind==='workshop'&&tt.terrain!=='hill')throw Error('Workshops need hills.');if(tt.terrain==='water')throw Error('Buildings need land. Use a bridge to cross water.');if(kind==='harbor'){if(!learned(m,'survey'))throw Error('Research Field Surveying to launch boats.');if(!coastal(k))throw Error('Harbors require land beside water.');}if(kind==='tower'){if(!learned(m,'survey'))throw Error('Research Field Surveying first.');if(tt.terrain!=='hill')throw Error('Scouting Towers require a hill.');if(d.roads[k])throw Error('This hill contains a road. Choose a hill beside the road.');if(!connected(m,k))throw Error('Connect a road beside this hill first.');}cr=defs[kind].credits;mat=defs[kind].materials;work.push(defs[kind].seconds*Math.pow(2,.9));}}
  );return {kind:kind,path:path,origin:origin,target:target,town:payload.town,work:work,credits:cr,materials:mat,food:food};
 }
 function placement(m,kind,id,path){try{if(blockedSite(m,id)||(s(m).queue||[]).some(function(q){return q.project.path.indexOf(id)>=0;}))throw Error('Site reserved by construction.');m=plannedWorld(m);if(s(m).job&&s(m).job.path.slice(s(m).job.done||0).indexOf(id)>=0)throw Error('Site reserved by construction.');var road=kind==='road'||kind==='bridge',route=road&&path&&path.length?(path.indexOf(id)>=0?path:path.concat(id)):[id];plan(m,kind,{id:id,path:route});return {ok:true};}catch(e){return {ok:false,message:e.message};}}
 function researchPreview(m,id,count){try{var state=researchState(m,id);if(!state.ok)return state;var crew=crewCheck(m,count,'study');if(!crew)throw Error('Assign at least one researcher.');var copy=clone(m);s(copy).study={crew:crew};rebalance(copy);return {ok:true,seconds:Math.ceil(state.node.work/Math.pow(crew,.9)),before:economy(m),after:economy(copy)};}catch(e){return {ok:false,message:e.message};}}
 function preview(m,kind,payload,count){try{var actual=m,wait=false;if(kind!=='scout'&&(payload.path||[payload.id]).some(function(k){return blockedSite(m,k)||(s(m).queue||[]).some(function(q){return q.project.path.indexOf(k)>=0;});}))throw Error('Site reserved by construction.');if(kind!=='scout'){try{var test=plan(m,kind,payload);if(test.path.some(function(k){return blockedSite(m,k);}))throw Error('Site reserved');crewCheck(m,count,'new');}catch(e){wait=true;m=plannedWorld(m);}}var p=plan(m,kind,payload),crew=crewCheck(m,count,kind==='scout'?'scout':'new');if(!crew)throw Error('Assign at least one worker to start.');p.crew=crew;p.done=0;p.progress=0;var copy=clone(m),before=rates(m);if(kind==='scout')s(copy).scout=p;else addJob(copy,p);rebalance(copy);var after=rates(copy);return {ok:true,waiting:wait,project:p,seconds:eta(copy,p),before:before,after:after,available:workers(m).available};}catch(e){return {ok:false,message:e.message};}}
 function action(m,save,kind,payload,now){payload=payload||{};return transact(m,save,function(d){var id=payload.id,t=tile(id),b=d.buildings[id];
  if(kind==='quickRoad'){
   if(payload.type!=='road'&&payload.type!=='bridge')throw Error('Choose Road or Bridge.');var forecast=plannedWorld(m),piece=plan(forecast,payload.type,{id:id,path:[id]});if(blockedSite(m,id)||(d.queue||[]).some(function(q){return q.project.path.indexOf(id)>=0;}))throw Error('Tile already has a construction order.');
   var pending=(d.queue||[]).find(function(q){return q.project.batch===payload.batch&&payload.batch;}),existing=jobs(m).find(function(j){return j.batch===payload.batch&&payload.batch;}),batchProject=existing||(pending&&pending.project);
   if(batchProject&&batchProject.path.length<60&&batchProject.kind===payload.type&&batchProject.crew===payload.crew&&neighbors(batchProject.path[batchProject.path.length-1]).indexOf(id)>=0){if(m.credits<piece.credits||d.materials<piece.materials||d.food<(piece.food||0))throw Error('Not enough resources for this road tile.');m.credits-=piece.credits;d.materials-=piece.materials;d.food-=piece.food||0;batchProject.path.push(id);batchProject.work.push(piece.work[0]);if(pending){pending.payload.path=batchProject.path.slice();pending.credits+=piece.credits;pending.materials+=piece.materials;pending.food=(pending.food||0)+(piece.food||0);}d.lastRoadBatch=batchProject.batch;return 'Road section ordered · '+batchProject.path.length+' sections · '+batchProject.crew+' workers';}
   d.roadSerial=(d.roadSerial||0)+1;payload=Object.assign({},payload,{path:[id],batch:d.roadSerial});kind='build';
  }
  if(kind==='priority'){if(['balanced','growth','exploration','manual'].indexOf(payload.value)<0)throw Error('Choose a settlement priority.');d.priority=payload.value;return 'Priority saved. Crews keep their orders; production adjusts automatically.';}
  if(kind==='target'){if(['farm','workshop'].indexOf(payload.kind)<0)throw Error('Unknown production target.');var n=Number(payload.count);if(!Number.isInteger(n)||n<0||n>d.population)throw Error('Target must be between zero and population.');d.priority='manual';d.targets[payload.kind]=n;return 'Staffing target saved. Available crews fill production automatically.';}
  if(kind==='protect'){d.protectFood=!!payload.enabled;return 'Food protection '+(d.protectFood?'enabled.':'disabled. Watch your Food balance.');}
  if(kind==='crew'){var type=payload.type;var j=type==='job'?(payload.projectId?jobs(m).find(function(j){return j.projectId===payload.projectId;}):d.job):d[type];if(['job','scout','study'].indexOf(type)<0||!j)throw Error('No active crew.');j.crew=crewCheck(m,payload.count,type,payload.projectId);d.defaultCrew=Math.max(1,j.crew);return j.crew?'Crew reassigned; production adjusted.':'Crew recalled. Work is paused and progress preserved.';}
  if(kind==='build'||kind==='connection'||kind==='scout'||kind==='clear'){var type=kind==='scout'?'scout':'job',projectKind=kind==='build'?payload.type:kind,count=payload.crew||d.defaultCrew||2,source=m,queued=false,p;
   if(type==='scout'&&d.scout)throw Error('Finish or resume the existing expedition.');
   try{p=plan(m,projectKind,payload);if(type==='job'&&p.path.slice(p.done||0).some(function(k){return blockedSite(m,k);}))throw Error('Site reserved');p.crew=crewCheck(m,count,type==='job'?'new':'scout');}catch(e){if(type==='scout')throw e;source=plannedWorld(m);if((payload.path||[payload.id]).some(function(k){return blockedSite(m,k)||(d.queue||[]).some(function(q){return q.project.path.indexOf(k)>=0;});}))throw Error('Site reserved by construction.');p=plan(source,projectKind,payload);p.crew=crewCheck(source,count,'new');queued=true;}
   if(queued&&(d.queue||[]).length>=12)throw Error('Queue full. Finish or cancel a waiting project.');if(!p.crew)throw Error('Assign workers.');if(m.credits<p.credits||d.materials<p.materials||d.food<(p.food||0))throw Error('Not enough resources: '+p.credits+' Credits, '+p.materials+' Materials, '+(p.food||0)+' Food required.');m.credits-=p.credits;d.materials-=p.materials;d.food-=p.food||0;p.done=0;p.progress=0;p.batch=payload.batch||null;if(p.batch)d.lastRoadBatch=p.batch;
   if(queued){d.queue=d.queue||[];d.queueSerial=(d.queueSerial||0)+1;d.queue.push({id:d.queueSerial,kind:projectKind,payload:clone(payload),crew:p.crew,project:p,credits:p.credits,materials:p.materials,food:p.food||0});return 'Project queued until its route and workers are available. Costs reserved.';}if(type==='job')addJob(m,p);else d.scout=p;d.defaultCrew=p.crew;return p.crew+' workers assigned. Other crews continue their projects.';}
  if(kind==='cancelQueue'){var index=(d.queue||[]).findIndex(function(q){return q.id===payload.queueId;});if(index<0)throw Error('Queued project no longer exists.');var q=d.queue.splice(index,1)[0];m.credits+=q.credits;d.materials+=q.materials;d.food+=q.food||0;d.queueNotice='';return 'Queued project cancelled. Reserved resources refunded.';}
  if(kind==='trade'){var resource=payload.resource;if(resource!=='food'&&resource!=='materials')throw Error('Choose Food or Materials.');if(!towns.some(function(t){return active(m,t.id);}))throw Error('Integrate and connect a village to trade.');var reserve=resource==='food'?Math.max(60,d.population*2.5):60;if(d[resource]<reserve+100)throw Error('Trade needs 100 surplus '+resource+' above the '+reserve+' reserve.');d[resource]-=100;var gain=learned(m,'barter')?65:50;m.credits+=gain;return 'Traded 100 '+resource+' for '+gain+' Credits. Reserve preserved.';}
  if(kind==='welcome'){var village=town(payload.town);if(!village||!d.defended[village.id]||d.welcomed[village.id]||!network(m).has(key(village.x,village.y)))throw Error('Defend and connect this village first.');if(housing(m)<d.population+4||d.food<20)throw Error('Provide 4 housing spaces and 20 Food.');d.food-=20;d.population+=4;d.welcomed[village.id]=true;emit(m,key(village.x,village.y),'+4 residents · +'+(2*stars(village.id)+(village.id===6?4:0))+' Credits/min');return village.name+' integrated. '+village.benefit+'. Staffing targets fill automatically.';}
  if(kind==='demolish'){if(id==='0,0'||!b&&!d.roads[id])throw Error('Choose a building or road.');if(jobs(m).length||d.scout||(d.queue||[]).length)throw Error('Finish or cancel construction and scouting before removing infrastructure.');if(b&&b.kind==='house'&&housing(m)-houseSpaces(m)<d.population)throw Error('Build replacement housing first.');var refund=Math.floor((b?defs[b.kind]:t.terrain==='water'?defs.bridge:defs.road).materials/2);if(b)delete d.buildings[id];else delete d.roads[id];d.materials+=refund;return 'Removed. +'+refund+' Materials returned. Staffing redistributed.';}
  if(kind==='research'){var state=researchState(m,payload.node||'tools');if(!state.ok)throw Error(state.message);var n=state.node,crew=crewCheck(m,payload.crew||d.defaultCrew||2,'study');if(!crew)throw Error('Assign researchers.');if(m.credits<n.credits||d.materials<n.materials)throw Error('Requires '+n.credits+' Credits and '+n.materials+' Materials.');m.credits-=n.credits;d.materials-=n.materials;d.study={kind:'study',node:n.id,crew:crew,path:['0,0'],target:'0,0',work:[n.work],done:0,progress:0};return n.name+' started. '+crew+' residents researching at HQ. Production adjusted until they return.';}
  throw Error('Unknown action.');
 },now);}
 function ready(m,n){var t=town(n);return !!(s(m)&&t&&s(m).visible[key(t.x,t.y)]&&!s(m).defended[n]);}
 function win(m,n){if(!ready(m,n))return false;advance(m,Date.now());s(m).defended[n]=true;var t=town(n);s(m).focus=key(t.x,t.y);emit(m,s(m).focus,'Village defended. Connect roads and welcome survivors.');return true;}
 function frontier(m){return Object.keys(tiles).filter(function(k){return s(m).visible[k]&&tile(k).terrain!=='water'&&neighbors(k).some(function(n){return !s(m).visible[n];});}).sort(function(a,b){return Math.abs(tile(a).x-5)+Math.abs(tile(a).y)-Math.abs(tile(b).x-5)-Math.abs(tile(b).y);})[0];}
 function surveyRadius(m){return (learned(m,'survey')?4:3)+(learned(m,'optics')?1:0);}
 function surveyArea(m,id){var t=tile(id);return !t?[]:Object.keys(tiles).filter(function(k){return Math.max(Math.abs(tile(k).x-t.x),Math.abs(tile(k).y-t.y))<=surveyRadius(m);});}
 function scoutStatus(m){var j=s(m).scout;if(!j)return 'No expedition';return !j.crew?'Paused':j.progress>=j.revealAt?'Returning':j.progress>=Math.max(1,j.path.length-1)*20?'Surveying':'Traveling';}
 function defenseBonuses(m){return {damage:learned(m,'drills')?.1:0,hq:learned(m,'fortifications')?.15:0,artillery:learned(m,'artillery')?.15:0};}
 function resume(m,save,now){now=now===undefined?Date.now():now;var d=s(m),elapsed=Math.max(0,now-d.at),before={food:d.food,materials:d.materials,credits:m.credits,cleared:Object.keys(d.cleared).length,visible:Object.keys(d.visible).length,knowledge:knowledge.filter(function(n){return learned(m,n.id);}).length,buildings:Object.keys(d.buildings).length};return transact(m,save,function(d){if(elapsed<60000)return '';d.returnReport={minutes:Math.floor(Math.min(elapsed,28800000)/60000),food:Math.floor(d.food-before.food),materials:Math.floor(d.materials-before.materials),credits:Math.floor(m.credits-before.credits),cleared:Object.keys(d.cleared).length-before.cleared,visible:Object.keys(d.visible).length-before.visible,knowledge:knowledge.filter(function(n){return learned(m,n.id);}).length-before.knowledge,buildings:Object.keys(d.buildings).length-before.buildings};return 'Settlement updated while you were away.';},now);}
 function objective(m){var d=s(m);if(d.food<20&&rates(m).food<=0)return {id:'1,0',text:'Food shortage · staff or connect farms'};var t=towns.find(function(t){return d.visible[key(t.x,t.y)]&&!d.welcomed[t.id];});if(t){var id=key(t.x,t.y);if(jobs(m).some(function(j){return j.town===t.id;}))return {id:id,text:'Connecting '+t.name+' · crew progress on map'};if(!d.defended[t.id])return {id:id,text:'Bring '+t.name+' survivors home · defend village'};if(!network(m).has(id))return {id:id,text:'Bring survivors home · connect '+t.name};if(housing(m)<d.population+4)return {id:'0,0',text:'Build housing · 4 spaces needed for '+t.name};return {id:id,text:'Welcome 4 survivors from '+t.name};}return {id:d.scout?d.scout.target:frontier(m),text:d.scout?'Scouts exploring · manage production or build':'Discover the next village · choose a scouting frontier'};}
 root.LSCSettlement={bounds:bounds,coastal:coastal,ports:ports,waterRoute:waterRoute,townProfile:townProfile,landmarks:landmarks,resume:resume,surveyArea:surveyArea,surveyRadius:surveyRadius,scoutStatus:scoutStatus,defenseBonuses:defenseBonuses,houseSpaces:houseSpaces,farmRate:farmRate,materialRate:materialRate,foodUse:foodUse,jobs:jobs,blockedSite:blockedSite,initialize:initialize,action:action,advance:advance,tick:function(m,save,now){return transact(m,save,function(){},now);},ready:ready,win:win,objective:objective,workers:workers,housing:housing,rates:rates,income:income,connected:connected,network:network,defs:defs,tiles:tiles,tile:tile,towns:towns,town:town,stars:stars,combat:combat,storage:storage,economy:economy,knowledge:knowledge,learned:learned,researchState:researchState,researchPreview:researchPreview,placement:placement,towerArea:towerArea,plannedWorld:plannedWorld,preview:preview,eta:eta,speed:speed,remaining:remaining,rebalance:rebalance,foodMinimum:foodMinimum,capacity:capacity};
})(typeof window!=='undefined'?window:globalThis);
