(function(root){
 'use strict';
 var api=root.LSCSettlement;
 function paint(ctx,m,view,camera,selected,route){api=root.LSCSettlement;var d=m.settlement204,scale=camera.scale;ctx.fillStyle='#000000';ctx.fillRect(0,0,view.w,view.h);Object.keys(api.tiles).forEach(function(id){var t=api.tile(id),x=(t.x-camera.x)*scale+view.w/2,y=(t.y-camera.y)*scale+view.h/2;if(x+scale/2<0||y+scale/2<0||x-scale/2>view.w||y-scale/2>view.h)return;ctx.save();ctx.translate(x-scale/2,y-scale/2);ctx.beginPath();ctx.rect(0,0,scale,scale);ctx.clip();ctx.scale(scale/64,scale/64);if(!d.visible[id]){ctx.fillStyle='#000000';ctx.fillRect(0,0,64,64);ctx.restore();return;}var colored=d.cleared[id]||d.roads[id],palette={plain:'#78ac50',hill:'#91a081',bank:'#d1bd75',water:'#258fb9'};ctx.fillStyle=colored?palette[t.terrain]:'#62686b';ctx.fillRect(0,0,64,64);ctx.strokeStyle=colored?'#b4c7a340':'#a6b4ae40';ctx.lineWidth=1;ctx.strokeRect(.5,.5,63,63);var b=d.buildings[id];for(var dot=0;dot<9;dot++){var seed=Math.abs(t.x*71+t.y*43+dot*137);ctx.fillStyle=colored?'#e3ef972e':'#a8b0b018';ctx.fillRect(3+seed%56,3+Math.floor(seed/7)%56,2,2);}
 if(t.terrain==='water'){ctx.strokeStyle=colored?'#8fd7e5':'#798480';for(var w=12;w<60;w+=14){ctx.beginPath();ctx.moveTo(10,w);ctx.quadraticCurveTo(27,w-5,49,w);ctx.stroke();}}
 if(!b&&!t.town&&id!=='0,0'&&!d.roads[id]){if(t.terrain==='hill'){ctx.fillStyle=colored?'#c2bea2':'#939b92';ctx.beginPath();ctx.moveTo(9,47);ctx.lineTo(24,14);ctx.lineTo(36,29);ctx.lineTo(44,19);ctx.lineTo(56,48);ctx.closePath();ctx.fill();ctx.fillStyle=colored?'#58695d':'#454d50';ctx.beginPath();ctx.moveTo(24,14);ctx.lineTo(26,44);ctx.lineTo(36,29);ctx.lineTo(44,19);ctx.lineTo(43,48);ctx.lineTo(56,48);ctx.lineTo(44,19);ctx.closePath();ctx.fill();}else if(t.terrain==='plain'&&Math.abs(t.x*11+t.y*3)%4!==0){for(var i=0;i<3;i++){var tx=15+i*16,ty=25+(i%2)*12;ctx.fillStyle=colored?'#28643a':'#344b40';ctx.fillRect(tx-1,ty+4,3,12);ctx.beginPath();ctx.moveTo(tx,ty-11);ctx.lineTo(tx-9,ty+9);ctx.lineTo(tx+9,ty+9);ctx.fill();ctx.fillStyle=colored?'#5c9e43':'#627269';ctx.beginPath();ctx.moveTo(tx,ty-11);ctx.lineTo(tx-9,ty+9);ctx.lineTo(tx,ty+5);ctx.fill();}}}
 if(d.roads[id]){ctx.strokeStyle=t.terrain==='water'?'#c3a67a':'#c2b58d';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(32,32);ctx.lineTo(32.1,32);[[1,0],[-1,0],[0,1],[0,-1]].forEach(function(v){if(d.roads[(t.x+v[0])+','+(t.y+v[1])]){ctx.moveTo(32,32);ctx.lineTo(32+v[0]*32,32+v[1]*32);}});ctx.stroke();}
 function house(x,y,w,h){ctx.fillStyle='#2c383459';ctx.fillRect(x+2,y+3,w,h);ctx.fillStyle='#dfd2ac';ctx.fillRect(x,y,w,h);ctx.fillStyle='#9a6749';ctx.beginPath();ctx.moveTo(x-2,y);ctx.lineTo(x+w/2,y-9);ctx.lineTo(x+w+2,y);ctx.fill();ctx.fillStyle='#28413d';ctx.fillRect(x+w/2-3,y+h-8,6,8);}
 if(id==='0,0'){house(12,25,40,25);ctx.fillStyle='#f4dfa2';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText('HQ',32,18);}
 if(t.town){house(8,22,19,17);house(36,19,19,19);house(23,42,21,14);ctx.fillStyle=d.welcomed[t.town]?'#78dba1':d.defended[t.town]?'#acd5e0':'#e7ba70';ctx.fillRect(49,5,9,6);ctx.fillStyle='#142c2b';if(scale>=40)ctx.fillRect(4,52,56,11);ctx.fillStyle='#fff0c1';ctx.font='bold 9px sans-serif';ctx.textAlign='center';if(scale>=55||selected===id)ctx.fillText(t.town===1?'BROOKHAVEN':'TOWN '+t.town,32,61);}
 if(b){if(b.kind==='harbor'){ctx.fillStyle='#bc925c';ctx.fillRect(8,35,48,16);ctx.fillStyle='#376e84';ctx.fillRect(8,10,48,22);ctx.strokeStyle='#ead9a8';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(32,13);ctx.lineTo(32,40);ctx.moveTo(23,23);ctx.lineTo(41,23);ctx.moveTo(20,32);ctx.quadraticCurveTo(32,49,44,32);ctx.stroke();}else if(b.kind==='tower'){ctx.fillStyle='#384844';ctx.fillRect(13,47,38,6);ctx.strokeStyle='#ead399';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(19,48);ctx.lineTo(25,17);ctx.lineTo(39,17);ctx.lineTo(45,48);ctx.moveTo(23,34);ctx.lineTo(42,34);ctx.moveTo(23,34);ctx.lineTo(39,20);ctx.stroke();ctx.fillStyle='#b89c63';ctx.fillRect(18,14,28,9);ctx.fillStyle='#416666';ctx.fillRect(21,8,22,9);ctx.fillStyle='#eedb98';ctx.fillRect(30,2,3,10);}else if(b.kind==='farm'){ctx.fillStyle='#7d653b';ctx.fillRect(6,7,51,47);for(var row=12;row<49;row+=8){ctx.fillStyle='#eed15e';ctx.fillRect(9,row,45,3);}house(36,38,20,16);}else if(b.kind==='workshop'){house(10,25,41,28);ctx.fillStyle='#5c6159';ctx.fillRect(42,9,9,20);ctx.fillStyle='#e8b459';ctx.fillRect(17,34,11,10);}else house(12,24,40,30);ctx.fillStyle='#102929e0';if(scale>=40)ctx.fillRect(5,53,54,10);ctx.fillStyle='#f6edcf';ctx.font='bold 8px sans-serif';ctx.textAlign='center';if(scale>=55||selected===id)ctx.fillText(b.kind==='tower'?'TOWER':api.defs[b.kind].name.toUpperCase(),32,61);if(scale>=40&&b.kind!=='house'&&b.kind!=='tower'&&b.kind!=='harbor'){ctx.fillStyle=api.connected(m,id)?'#edf4c3':'#f0ad78';ctx.font='bold 10px sans-serif';ctx.fillText(b.workers+'/'+api.defs[b.kind].capacity,32,13);}}
 if(d.job&&d.job.path.indexOf(id)>=0){ctx.fillStyle='#ddb94b66';ctx.fillRect(2,2,60,60);ctx.fillStyle='#fff0b2';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText('BUILDING',32,34);}
 if(route&&route.indexOf(id)>=0){ctx.fillStyle='#80dfc16b';ctx.fillRect(2,2,60,60);}
 if(selected===id){ctx.strokeStyle='#ffe7a7';ctx.lineWidth=3;ctx.strokeRect(2,2,60,60);}ctx.restore();});}
 function mount(panel,m,save,refresh,navigate,deploy,power){var init=api.initialize(m,save);if(!init.ok){panel.textContent=init.message;return function(){};}var el=document.createElement('section');el.id='settlement-world';el.style.cssText='position:fixed;inset:0;z-index:30500;background:#071a1d;color:#ecf0df;display:flex;flex-direction:column;padding-top:env(safe-area-inset-top);font:14px system-ui';
 el.innerHTML='<header style="padding:8px 12px"><div style="display:flex;justify-content:space-between;align-items:center"><b>LAST STAND · SETTLEMENT</b><button data-menu aria-label="Menu">☰</button></div><div data-resources></div><div data-workers></div><button data-objective style="width:100%;text-align:left"></button></header><main style="position:relative;flex:1;min-height:150px;overflow:hidden"><canvas style="width:100%;height:100%;touch-action:none"></canvas><div style="position:absolute;right:8px;top:8px"><button data-minus>−</button><button data-plus>+</button><button data-home>HQ</button></div></main><div data-sheet style="padding:0 12px;max-height:40vh;overflow:auto;background:#112d30"></div><div data-notice role="status" style="padding:6px 12px;font-size:12px;color:#ecd49b"></div><nav style="display:flex;gap:4px;padding:6px 8px max(6px,env(safe-area-inset-bottom))"><button data-world>WORLD</button><button data-build>BUILD</button><button data-people>PEOPLE</button><button data-research>RESEARCH</button></nav>';
 var style=document.createElement('style');style.textContent='#settlement-world button{min-height:44px;padding:9px;margin:2px;border:1px solid #6a958b;border-radius:7px;background:#234945;color:#f5edcf;font:bold 12px system-ui}#settlement-world button:disabled{opacity:.45}#settlement-world nav button{flex:1;padding:8px 2px}#settlement-world p{margin:8px 0;line-height:1.4}#settlement-world h3{margin:10px 0}#settlement-world [data-resources]{font-size:14px;font-weight:700;padding:5px 0}#settlement-world [data-workers]{font-size:12px;color:#b4d2c4}';el.appendChild(style);document.body.appendChild(el);panel.innerHTML='';
 var canvas=el.querySelector('canvas'),ctx=canvas.getContext('2d'),sheet=el.querySelector('[data-sheet]'),camera=Object.assign({},m.settlement204.camera||{x:1,y:0,scale:48}),view={w:390,h:500},selected=null,mode='world',tool=null,path=[],dead=false,pointers=new Map(),gesture=null;
 function tell(text){el.querySelector('[data-notice]').textContent=text||'';}
 function button(text,fn,disabled){var b=document.createElement('button');b.textContent=text;b.disabled=!!disabled;b.onclick=fn;sheet.appendChild(b);return b;}
 function line(text,title){var p=document.createElement(title?'h3':'p');p.textContent=text;sheet.appendChild(p);}
 function execute(kind,payload){var r=api.action(m,save,kind,payload);tell(r.message);refresh();update();return r.ok;}
 function draw(){if(!dead)paint(ctx,m,view,camera,selected,path);}
 function header(){var d=m.settlement204,w=api.workers(m),r=api.rates(m);el.querySelector('[data-resources]').textContent='FOOD '+Math.floor(d.food)+' · MAT '+Math.floor(d.materials)+' · CR '+Math.floor(m.credits);el.querySelector('[data-workers]').textContent=w.available+'/'+w.total+' workers available · '+w.assigned+' assigned · '+w.scouts+' scouting · '+w.builders+' building';el.querySelector('[data-objective]').textContent=api.objective(m).text;}
 function inspect(){var d=m.settlement204,t=api.tile(selected),b=d.buildings[selected];if(!t)return;line(!d.visible[selected]?'Unknown territory':t.town?(t.town===1?'Brookhaven':'Town '+t.town)+' · '+api.stars(t.town)+' star':b?api.defs[b.kind].name:t.terrain.toUpperCase(),true);if(!d.visible[selected]){line('Send scouts from a revealed frontier tile to see this land.');return;}
 if(b){line(api.connected(m,selected)?'Connected to HQ.':'Disconnected: construct a road beside this building.');if(api.defs[b.kind].capacity){line('Workers '+b.workers+'/'+api.defs[b.kind].capacity+' · '+(b.kind==='farm'?'3 Food per worker/min':'2 Materials per worker/min'));button('− WORKER',function(){execute('assign',{id:selected,count:b.workers-1});},b.workers===0);button('+ WORKER',function(){execute('assign',{id:selected,count:b.workers+1});},b.workers>=api.defs[b.kind].capacity||api.workers(m).available<=0);}else line('Housing: '+d.population+'/'+api.housing(m)+' occupied.');}
 if(t.town){var link=api.network(m).has(selected),defended=!!d.defended[t.town],joined=!!d.welcomed[t.town];line('Defense: '+(defended?'secured':'required')+' · Road: '+(link?'connected':'missing')+' · Survivors: '+(joined?'welcomed':'4 waiting'));if(!defended)button('DEFENSE BRIEFING',function(){mode='brief';update();});else if(!joined){line('Welcome cost: 20 Food and 4 free housing spaces.');button('WELCOME 4 SURVIVORS',function(){execute('welcome',{town:t.town});});}else line('Town contributes income while its road remains connected.');}
 if(!d.cleared[selected]&&t.terrain!=='water')button('CLEAR LAND · FREE',function(){execute('clear',{id:selected});});
 if(!d.scout&&Object.keys(api.tiles).some(function(k){var n=api.tile(k);return Math.abs(n.x-t.x)+Math.abs(n.y-t.y)===1&&!d.visible[k];}))button('SCOUT · 2 WORKERS · 20 FOOD',function(){execute('scout',{id:selected});});
 if(d.cleared[selected]&&!b&&!t.town)button('BUILD HERE',function(){mode='build';update();});
 if(b||d.roads[selected]&&selected!=='0,0')button('DEMOLISH…',function(){sheet.innerHTML='';line('Remove '+(b?api.defs[b.kind].name:'road')+'? Return 50% of its Material cost; no Credit refund. Workers return. Connections may stop producing.');button('CONFIRM DEMOLITION',function(){execute('demolish',{id:selected});});button('CANCEL',update);});}
 function update(){header();sheet.innerHTML='';var d=m.settlement204;
 if(mode==='people'){var w=api.workers(m);line('People · '+w.total+' residents',true);line(w.available+' available · '+w.assigned+' production · '+w.scouts+' scouts · '+w.builders+' builders');line('Housing '+d.population+'/'+api.housing(m)+' · Food balance '+api.rates(m).food.toFixed(1)+'/min. Shortages halve Materials output; nobody is lost.');Object.keys(d.buildings).forEach(function(id){var b=d.buildings[id];for(var dot=0;dot<9;dot++){var seed=Math.abs(t.x*71+t.y*43+dot*137);ctx.fillStyle=colored?'#e3ef972e':'#a8b0b018';ctx.fillRect(3+seed%56,3+Math.floor(seed/7)%56,2,2);}button(api.defs[b.kind].name+' ('+id+') · '+b.workers+' workers',function(){selected=id;camera.x=api.tile(id).x;camera.y=api.tile(id).y;mode='world';update();});});if(d.scout)line('Scouts return in '+Math.max(0,Math.ceil((d.scout.end-Date.now())/1000))+' seconds.');if(d.job)line('Builders finish in '+Math.max(0,Math.ceil((d.job.end-Date.now())/1000))+' seconds.');}
 else if(mode==='build'){line('Choose a project',true);Object.keys(api.defs).forEach(function(k){var def=api.defs[k];button(def.name+' · '+def.materials+' MAT / '+def.credits+' CR',function(){tool=k;path=[];mode='place';tell(k==='road'||k==='bridge'?'Trace adjacent squares from a connected road. Confirm before spending.':'Tap an empty cleared site. Farm: plain/bank; Workshop: hill; Housing: land.');update();});});}
 else if(mode==='place'){line('Place '+api.defs[tool].name,true);line('2 builders · '+api.defs[tool].seconds+' seconds · '+path.length+' tile'+(path.length===1?'':'s'));line('Total '+api.defs[tool].materials*path.length+' Materials + '+api.defs[tool].credits*path.length+' Credits');button('CONFIRM BUILD',function(){if(execute('build',{id:path[0],type:tool,path:path})){path=[];tool=null;mode='world';update();}},!path.length);button('CANCEL',function(){path=[];tool=null;mode='world';update();});}
 else if(mode==='research'){line('Settlement research',true);line('Better Tools: workshop output +20%. Costs 30 Materials and 200 Credits.');button(d.tools?'RESEARCHED':'RESEARCH BETTER TOOLS',function(){execute('research');},d.tools);}
 else if(mode==='menu'){line('Settlement menu',true);[['Campaigns / HQ','hq'],['Commander','commander'],['Equipment','inventory'],['Special Operations','operations']].forEach(function(item){button(item[0],function(){navigate(item[1]);});});}
 else if(mode==='brief'){var t=api.tile(selected);line('Town defense',true);line(power(api.combat(t.town)));line('Costs 1 energy. Victory secures the town; connect its road and provide housing to welcome 4 survivors. Defeat preserves people and buildings.');button('DEPLOY · 1 ENERGY',function(){remember();var error=deploy(t.town,api.combat(t.town));if(error)tell(error);});button('BACK',function(){mode='world';update();});}
 else if(selected)inspect();draw();}
 function remember(){var old=m.settlement204.camera;m.settlement204.camera={x:camera.x,y:camera.y,scale:camera.scale};if(save()!==true)m.settlement204.camera=old;}
 function focus(id){if(!id)return;var t=api.tile(id);selected=id;camera.x=t.x;camera.y=t.y;mode='world';path=[];update();}
 el.querySelector('[data-objective]').onclick=function(){focus(api.objective(m).id);};el.querySelector('[data-home]').onclick=function(){camera.x=0;camera.y=0;selected=null;update();};el.querySelector('[data-menu]').onclick=function(){mode='menu';path=[];update();};['world','build','people','research'].forEach(function(k){el.querySelector('[data-'+k+']').onclick=function(){mode=k;selected=k==='world'?null:selected;path=[];tool=null;update();};});el.querySelector('[data-minus]').onclick=function(){camera.scale=Math.max(24,camera.scale/1.2);draw();};el.querySelector('[data-plus]').onclick=function(){camera.scale=Math.min(84,camera.scale*1.2);draw();};
 function hit(e){var box=canvas.getBoundingClientRect();return Math.round((e.clientX-box.left-view.w/2)/camera.scale+camera.x)+','+Math.round((e.clientY-box.top-view.h/2)/camera.scale+camera.y);}
 canvas.onpointerdown=function(e){if(e.button!==0)return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);gesture=pointers.size===1?{x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y,moved:false}:null;if(mode==='place'&&pointers.size===1){var id=hit(e);if(api.tile(id)){if(tool==='road'||tool==='bridge'){path=[id];}else path=[id];selected=id;update();}}};
 canvas.onpointermove=function(e){if(!pointers.has(e.pointerId))return;var before=Array.from(pointers.values());pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){gesture=null;var after=Array.from(pointers.values()),dist=function(p){return Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);};camera.scale=Math.max(24,Math.min(84,camera.scale*dist(after)/Math.max(1,dist(before))));draw();return;}if(!gesture)return;var dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)>8)gesture.moved=true;if(mode==='place'&&(tool==='road'||tool==='bridge')){var id=hit(e),t=api.tile(id),last=api.tile(path[path.length-1]);if(t&&last&&Math.abs(t.x-last.x)+Math.abs(t.y-last.y)===1&&path.indexOf(id)<0){path.push(id);update();}}else if(gesture.moved){camera.x=gesture.cx-dx/camera.scale;camera.y=gesture.cy-dy/camera.scale;draw();}};
 canvas.onpointerup=function(e){if(gesture&&!gesture.moved&&mode!=='place'){var id=hit(e);if(api.tile(id)){selected=id;mode='world';update();}}pointers.delete(e.pointerId);gesture=null;};function cancel(e){pointers.delete(e.pointerId);gesture=null;}canvas.onpointercancel=cancel;canvas.onlostpointercapture=cancel;canvas.oncontextmenu=function(e){e.preventDefault();};
 function resize(){var box=canvas.getBoundingClientRect(),ratio=Math.min(2,root.devicePixelRatio||1);view={w:box.width,h:box.height};canvas.width=box.width*ratio;canvas.height=box.height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);draw();}root.addEventListener('resize',resize);var ro=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;if(ro)ro.observe(canvas.parentElement);var timer=setInterval(function(){var d=m.settlement204,now=Date.now();if(now-d.at>=15000||d.job&&d.job.end<=now||d.scout&&d.scout.end<=now){var r=api.tick(m,save,now);tell(r.message);header();draw();if(mode==='people'||!pointers.size&&mode==='world')update();}else header();},1000);resize();update();tell(m.settlement204.notice);
 return function(){remember();dead=true;clearInterval(timer);root.removeEventListener('resize',resize);if(ro)ro.disconnect();el.remove();};
 }
 root.LSCSettlementView={mount:mount,paint:paint};
})(typeof window!=='undefined'?window:globalThis);
