(function(root){
 'use strict';
 var api=root.LSCSettlement,basePaint=root.LSCSettlementView.paint;
 function duration(n){return n===null?'Paused':n<60?Math.ceil(n)+'s':Math.floor(n/60)+'m '+Math.ceil(n%60)+'s';}
 function paint(ctx,m,view,camera,selected,path,now){var display=Object.assign({},m,{settlement204:Object.assign({},m.settlement204,{job:null})}),d=m.settlement204;ctx.save();ctx.filter='grayscale(1)';basePaint(ctx,display,view,camera,selected,path);ctx.restore();ctx.save();ctx.beginPath();Object.keys(d.cleared).forEach(function(id){var t=api.tile(id);if(t)ctx.rect((t.x-camera.x)*camera.scale+view.w/2-camera.scale/2,(t.y-camera.y)*camera.scale+view.h/2-camera.scale/2,camera.scale,camera.scale);});ctx.clip();basePaint(ctx,display,view,camera,selected,path);ctx.restore();now=now||Date.now();
  function at(id){var t=api.tile(id);return t?{x:(t.x-camera.x)*camera.scale+view.w/2,y:(t.y-camera.y)*camera.scale+view.h/2}:null;}
  function label(id,text,color){var p=at(id);if(!p)return;ctx.font='bold 12px sans-serif';ctx.textAlign='center';var width=Math.min(250,ctx.measureText(text).width+14);ctx.fillStyle='#092327ee';ctx.fillRect(p.x-width/2,p.y-camera.scale/2-21,width,20);ctx.fillStyle=color||'#ffdfa0';ctx.fillText(text,p.x,p.y-camera.scale/2-7);}
  function crewDot(p,count,color){for(var i=0;i<Math.min(count,6);i++){var x=p.x+(i%3-1)*7,y=p.y+Math.floor(i/3)*9;ctx.fillStyle='#142522';ctx.fillRect(x-3,y+2,6,7);ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}}
  ['job','scout'].forEach(function(type){var j=d[type];if(!j)return;var extra=Math.max(0,(now-d.at)/1000)*api.speed(m,j),progress=Math.min(j.work[j.done||0],j.progress+extra),total=j.work[j.done||0],index=j.done||0,id=type==='job'?j.path[index]:j.target,p=at(id);if(!p)return;
   if(type==='job'){j.path.slice(index+1).forEach(function(k){var q=at(k);if(q){ctx.strokeStyle='#d9bd7888';ctx.lineWidth=1;ctx.strokeRect(q.x-camera.scale/2+3,q.y-camera.scale/2+3,camera.scale-6,camera.scale-6);}});ctx.save();ctx.beginPath();ctx.rect(p.x-camera.scale/2,p.y-camera.scale/2,camera.scale,camera.scale);ctx.clip();ctx.strokeStyle='#e3c28a';ctx.lineWidth=2;for(var x=-.3;x<=.31;x+=.3){ctx.beginPath();ctx.moveTo(p.x+x*camera.scale,p.y-camera.scale*.35);ctx.lineTo(p.x+x*camera.scale,p.y+camera.scale*.32);ctx.stroke();}ctx.beginPath();ctx.moveTo(p.x-camera.scale*.32,p.y);ctx.lineTo(p.x+camera.scale*.32,p.y);ctx.stroke();ctx.fillStyle='#092327';ctx.fillRect(p.x-camera.scale*.4,p.y+camera.scale*.34,camera.scale*.8,6);ctx.fillStyle='#efcd7b';ctx.fillRect(p.x-camera.scale*.4,p.y+camera.scale*.34,camera.scale*.8*progress/total,6);ctx.restore();var from=at(index?j.path[index-1]:j.origin||j.path[0])||p,phase=Math.min(1,progress/Math.max(1,total*.2));crewDot({x:from.x+(p.x-from.x)*phase,y:from.y+(p.y-from.y)*phase+Math.sin(now/180)*1.5},j.crew,'#edbf6a');label(id,j.crew?j.crew+' builders · '+duration(api.eta(m,j)):'Construction paused');}
   else {var outbound=Math.max(1,j.path.length-1)*20,returning=progress>=j.revealAt,ratio=returning?1-(progress-j.revealAt)/Math.max(1,total-j.revealAt):Math.min(1,progress/outbound);ratio=Math.max(0,Math.min(1,ratio));var pos=ratio*Math.max(0,j.path.length-1),lo=Math.floor(pos),hi=Math.min(j.path.length-1,lo+1),a=at(j.path[lo]),b=at(j.path[hi]);if(a&&b)crewDot({x:a.x+(b.x-a.x)*(pos-lo),y:a.y+(b.y-a.y)*(pos-lo)},j.crew,'#8ae3e1');ctx.strokeStyle='#80d8d5';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,camera.scale*.32,0,Math.PI*2);ctx.stroke();label(id,!j.crew?'Scouting paused':(returning?'Returning':progress>=outbound?'Surveying':'Traveling')+' · '+j.crew+' scouts · '+duration(api.eta(m,j)),'#9aeee2');}
  });
  Object.keys(d.buildings).forEach(function(id){var b=d.buildings[id],p=at(id);if(!p||b.kind==='house')return;if(!api.connected(m,id))label(id,'Disconnected','#f3aa80');else if((b.kind==='workshop'?d.materials:d.food)>=api.storage(m))label(id,b.kind==='workshop'?'Full · crew available':'Full · feeding residents','#ecd4a0');else if(!b.workers)label(id,'Unstaffed','#ced3c1');else {ctx.fillStyle='#d8e5a2';ctx.beginPath();ctx.arc(p.x+camera.scale*.25,p.y+Math.sin(now/350)*3,2,0,Math.PI*2);ctx.fill();}});
  api.towns.forEach(function(t){var id=t.x+','+t.y,p=at(id);if(!p||!d.visible[id])return;ctx.fillStyle='#112b29';ctx.fillRect(p.x-camera.scale*.44,p.y+camera.scale*.31,camera.scale*.88,camera.scale*.18);ctx.fillStyle='#eee3b8';ctx.font='bold '+Math.max(8,Math.min(12,camera.scale*.14))+'px sans-serif';ctx.textAlign='center';ctx.fillText(t.name.toUpperCase(),p.x,p.y+camera.scale*.46,camera.scale*.84);});
  if(d.event&&now-d.event.at<5500){var p=at(d.event.id);if(p){ctx.textAlign='center';ctx.font='bold 13px sans-serif';ctx.fillStyle='#d4f1ac';ctx.fillText(d.event.text,p.x,p.y-25-Math.max(0,now-d.event.at)/250,Math.min(330,view.w-16));}}
 }
 function mount(panel,m,save,refresh,navigate,deploy,power){var init=api.initialize(m,save);if(!init.ok){panel.textContent=init.message;return function(){};}var el=document.createElement('section');el.id='settlement-world';el.style.cssText='position:fixed;inset:0;z-index:30500;background:#071a1d;color:#edf1df;display:flex;flex-direction:column;box-sizing:border-box;padding-top:env(safe-area-inset-top);font:15px system-ui';
  el.innerHTML='<header><div class="settle-title"><b>LAST STAND · SETTLEMENT</b><button data-menu aria-label="Settlement menu">☰</button></div><div data-resources></div><button data-workers></button><button data-objective></button></header><main><canvas></canvas><div class="map-controls"><button data-minus aria-label="Zoom out">−</button><button data-plus aria-label="Zoom in">+</button><button data-home>HQ</button></div></main><div data-sheet></div><div data-notice role="status"></div><nav><button data-world>WORLD</button><button data-build>BUILD</button><button data-people>PEOPLE</button><button data-research>KNOWLEDGE</button></nav>';
  var style=document.createElement('style');style.textContent='#settlement-world header{padding:6px 10px}#settlement-world .settle-title{display:flex;align-items:center;justify-content:space-between;font-size:13px}#settlement-world button{min-height:44px;padding:9px 11px;margin:2px;border:1px solid #729a8c;border-radius:8px;background:#244a44;color:#fff3d4;font:bold 13px system-ui}#settlement-world button:disabled{opacity:.48}#settlement-world [data-objective],#settlement-world [data-workers]{display:block;width:100%;text-align:left;margin:3px 0}#settlement-world [data-workers]{font-size:13px;min-height:36px;background:transparent}#settlement-world [data-resources]{font-size:15px;font-weight:700}#settlement-world main{position:relative;flex:1;min-height:140px;overflow:hidden}#settlement-world canvas{width:100%;height:100%;touch-action:none}#settlement-world .map-controls{position:absolute;right:6px;top:6px}#settlement-world [data-sheet]{padding:0 12px;max-height:43vh;overflow:auto;background:#112d30}#settlement-world [data-sheet] h3{margin:10px 0;font-size:18px}#settlement-world p{margin:8px 0;line-height:1.4}#settlement-world nav{display:flex;gap:3px;padding:5px 6px max(6px,env(safe-area-inset-bottom))}#settlement-world nav button{flex:1;padding:8px 2px;font-size:12px}#settlement-world [data-notice]{padding:5px 10px;font-size:12px;color:#e8ce90;max-height:36px;overflow:hidden}#settlement-world .crew-row{display:flex;align-items:center;gap:6px;flex-wrap:wrap}';el.appendChild(style);document.body.appendChild(el);panel.innerHTML='';
  var canvas=el.querySelector('canvas'),ctx=canvas.getContext('2d'),sheet=el.querySelector('[data-sheet]'),camera=Object.assign({},m.settlement204.camera||{x:1,y:0,scale:60}),view={w:390,h:500},selected=m.settlement204.focus||null,mode='world',tool=null,path=[],count=m.settlement204.defaultCrew||4,dead=false,pointers=new Map(),gesture=null,frame=null,lastFrame=0;
  if(selected&&api.tile(selected)){camera.x=api.tile(selected).x;camera.y=api.tile(selected).y;}
  function tell(text){el.querySelector('[data-notice]').textContent=text||'';}
  function button(text,fn,disabled){var b=document.createElement('button');b.textContent=text;b.disabled=!!disabled;b.onclick=fn;sheet.appendChild(b);return b;}
  function line(text,title){var p=document.createElement(title?'h3':'p');p.textContent=text;sheet.appendChild(p);return p;}
  function execute(kind,payload){var r=api.action(m,save,kind,payload);tell(r.message);refresh();update();return r.ok;}
  function draw(){if(!dead)paint(ctx,m,view,camera,selected,path,Date.now());}
  function header(){var d=m.settlement204,w=api.workers(m);el.querySelector('[data-resources]').textContent='Food '+Math.floor(d.food)+' · Materials '+Math.floor(d.materials)+' · Credits '+Math.floor(m.credits);el.querySelector('[data-workers]').textContent=w.available+'/'+w.total+' available · '+w.assigned+' in production · '+(w.scouts+w.builders)+' on projects';el.querySelector('[data-objective]').textContent=api.objective(m).text;}
  function chooser(value,change){button('−',function(){change(Math.max(1,value-1));},value<=1);button(value+' WORKERS',function(){},true);button('+',function(){change(Math.min(6,value+1));},value>=6);}
  function preview(kind,payload){var p=api.preview(m,kind,payload,count);chooser(count,function(n){count=n;update();});if(!p.ok){line(p.message);return;}if(kind==='connection')path=p.project.path;line(p.project.path.length+(kind==='scout'?' route squares':' tiles')+' · '+duration(p.seconds)+' · '+p.project.materials+' Materials · '+p.project.credits+' Credits'+(p.project.food?' · '+p.project.food+' Food':''));line('Food balance '+p.before.food.toFixed(1)+' → '+p.after.food.toFixed(1)+'/min; Materials '+p.before.materials.toFixed(1)+' → '+p.after.materials.toFixed(1)+'/min. Idle workers are used first, then production is adjusted.');if(kind==='connection'&&payload.town===1&&!m.settlement204.welcomed[1])line('First-village crew training: this introductory route builds faster.');var occupied=m.settlement204[kind==='scout'?'scout':'job'];button(occupied?'CREW ALREADY ON A PROJECT':'CONFIRM '+(kind==='scout'?'SCOUTING':kind==='connection'?'CONNECTION':'BUILD'),function(){payload=Object.assign({},payload,{crew:count});if(execute(kind==='scout'?'scout':kind==='connection'?'connection':'build',payload)){mode='world';path=[];update();}},!!occupied);}
  function crewPanel(type){var j=m.settlement204[type];if(!j)return;line(type==='job'?'Construction crew':'Scouting crew',true);var timer=line('');timer.dataset.crewTimer=type;timer.textContent=duration(api.eta(m,j))+' remaining · '+j.crew+' workers';if(type==='job')line((j.done||0)+'/'+j.path.length+' sections complete.');button('VIEW CREW',function(){focus(type==='job'?j.path[j.done||0]:j.target);});button('− WORKER',function(){execute('crew',{type:type,count:j.crew-1});},j.crew<=0);button('+ WORKER',function(){execute('crew',{type:type,count:j.crew+1});},j.crew>=6);button(j.crew?'RECALL / PAUSE':'RESUME WITH '+count, function(){execute('crew',{type:type,count:j.crew?0:count});});}
  function inspect(){var d=m.settlement204,t=api.tile(selected),b=d.buildings[selected];if(!t)return;var v=t.town?api.town(t.town):null;line(!d.visible[selected]?'Unknown territory':v?v.name+' · '+api.stars(v.id)+' star':selected==='0,0'?'Settlement HQ':b?api.defs[b.kind].name:t.terrain.toUpperCase(),true);
   if(!d.visible[selected]){line('Send a scouting crew from a revealed frontier. They travel, survey, then return.');return;}
   if(selected==='0,0'){line('Housing '+d.population+'/'+api.housing(m)+' · Storage '+api.storage(m)+' Food / Materials.');button('BUILD HOUSING',function(){tool='house';mode='place';path=[];update();});button('PEOPLE & CREWS',function(){mode='people';update();});button('SAVED CAMPAIGNS',function(){navigate('campaigns');});button('EQUIPMENT',function(){navigate('inventory');});}
   if(b){line(api.connected(m,selected)?'Connected to the settlement.':'Disconnected: build a road beside this site.');if(api.defs[b.kind].capacity){line(b.workers+'/'+api.defs[b.kind].capacity+' workers · assigned automatically from your production target.');button('MANAGE PRODUCTION',function(){mode='people';update();});}else line('Four housing spaces. Residents '+d.population+'/'+api.housing(m)+'.');}
   if(v){var linked=api.network(m).has(selected),defended=!!d.defended[v.id],joined=!!d.welcomed[v.id];line(v.specialty+' · '+v.benefit+'.');line('4 residents · +'+(2*api.stars(v.id)+(v.id===6?4:0))+' Credits/min after integration.');line((defended?'✓ Defended':'○ Needs defense')+' · '+(linked?'✓ Connected':'○ Needs road')+' · '+(joined?'✓ Integrated':'○ Survivors waiting'));if(!linked)button('CONNECT VILLAGE',function(){mode='connect';path=[];update();});if(!defended)button('DEFENSE BRIEFING',function(){mode='brief';update();});else if(!joined){line('Welcome requirements: connected road, 4 free housing spaces, 20 Food.');button('WELCOME 4 SURVIVORS',function(){execute('welcome',{town:v.id});});}else line(linked?'Income and village specialty are active.':'Reconnect its road to restore income and its specialty.');}
   if(d.job&&d.job.path.indexOf(selected)>=0)crewPanel('job');if(d.scout&&d.scout.target===selected)crewPanel('scout');
   if(!d.cleared[selected]&&t.terrain!=='water'&&!v)button('CLEAR LAND · FREE',function(){execute('clear',{id:selected});});
   if(!d.scout&&Object.keys(api.tiles).some(function(k){var n=api.tile(k);return Math.abs(n.x-t.x)+Math.abs(n.y-t.y)===1&&!d.visible[k];}))button('PLAN SCOUTING',function(){mode='scout';path=[];update();});
   if(d.cleared[selected]&&!b&&!v&&selected!=='0,0')button('BUILD HERE',function(){mode='build';update();});
   if(b||d.roads[selected]&&selected!=='0,0')button('DEMOLISH…',function(){mode='demolish';update();});
  }
  function update(){header();sheet.innerHTML='';var d=m.settlement204;
   if(mode==='people'){line('People · '+d.population+' residents',true);line('Housing '+d.population+'/'+api.housing(m)+' · Storage '+api.storage(m)+' each. Existing excess stock is preserved; production pauses above capacity.');['farm','workshop'].forEach(function(k){line((k==='farm'?'Food':'Materials')+' target: '+d.targets[k]+' · capacity '+api.capacity(m,k),true);button('− '+(k==='farm'?'FOOD':'MATERIALS'),function(){execute('target',{kind:k,count:d.targets[k]-1});},d.targets[k]<=0);button('+ '+(k==='farm'?'FOOD':'MATERIALS'),function(){execute('target',{kind:k,count:d.targets[k]+1});},d.targets[k]>=d.population);});var e=api.economy(m);line('Actual stock change: Food '+e.foodNet.toFixed(1)+'/min · Materials '+e.materialsNet.toFixed(1)+'/min.');line('Farms supply '+e.foodGross.toFixed(1)+' Food/min; residents consume '+e.foodUse.toFixed(1)+'/min.');if(e.foodFull)line('Food storage full. Farms maintain residents; surplus is not stored. Existing stock is preserved.');if(e.materialsFull)line('Materials storage full. Workshop workers are available for projects. Your target is retained and resumes automatically after spending Materials.');if(e.shortage)line('Food shortage: Materials production is halved. Assign farmers or connect another farm.');line('Food funds expeditions and welcomes survivors. Materials build roads, bridges, housing and production sites. Credits pay for construction and combat upgrades.');button('PROTECT FOOD: '+(d.protectFood?'ON':'OFF'),function(){execute('protect',{enabled:!d.protectFood});});line('Targets refill when crews return or residents arrive. Food protection reserves '+api.foodMinimum(m)+' farmers; build connected farms if capacity is short.');crewPanel('job');crewPanel('scout');if(!d.job&&!d.scout)line('No active projects. Select a village to connect or a frontier to scout.');}
   else if(mode==='build'){line('Choose a project',true);Object.keys(api.defs).forEach(function(k){var def=api.defs[k];button(def.name+' · '+def.materials+' Materials / '+def.credits+' Credits',function(){tool=k;path=[];mode='place';update();});});line('For village routes, tap the village and choose Connect Village. Its crew clears and builds the route.');}
   else if(mode==='place'){line('Place '+api.defs[tool].name,true);line(tool==='road'||tool==='bridge'?'Trace adjacent squares from a connected road.':'Tap cleared land: farms on plains/banks, workshops on hills, housing on land.');if(path.length)preview(tool,{type:tool,id:path[0],path:path});button('CANCEL',function(){mode='world';path=[];update();});}
   else if(mode==='connect'){var v=api.town(api.tile(selected).town);line('Connect '+v.name,true);line('Distance sets the workload. Extra workers reduce time; Materials cost stays fixed. Progress is preserved when paused.');preview('connection',{town:v.id});button('CANCEL',function(){mode='world';path=[];update();});}
   else if(mode==='scout'){line('Send a scouting crew',true);preview('scout',{id:selected});button('CANCEL',function(){mode='world';path=[];update();});}
   else if(mode==='research'){line('Village Knowledge',true);line('Connected villages share practical specialties. The expanded scholar research tree is planned for Build 207.');api.towns.filter(function(t){return d.visible[t.x+','+t.y];}).forEach(function(t){line(t.name+' · '+t.specialty,true);line(t.benefit+' · '+(d.welcomed[t.id]&&api.network(m).has(t.x+','+t.y)?'ACTIVE':'Integrate and connect to activate'));button('VIEW '+t.name.toUpperCase(),function(){focus(t.x+','+t.y);});});line('Existing workshop improvement: +20% Materials, 30 Materials + 200 Credits.');button(d.tools?'BETTER TOOLS ACQUIRED':'ACQUIRE BETTER TOOLS',function(){execute('research');},d.tools);}
   else if(mode==='menu'){line('Settlement',true);[['Saved campaigns','campaigns'],['Equipment','inventory'],['Combat commander','commander'],['HQ upgrades','hq'],['Special Operations','operations']].forEach(function(item){button(item[0],function(){navigate(item[1]);});});}
   else if(mode==='brief'){var v=api.town(api.tile(selected).town);line('Defend '+v.name,true);line(power(api.combat(v.id)));line('1 Energy. Defend and connect the village, then provide housing and Food to welcome its residents. Defeat preserves settlement progress.');button('DEPLOY · 1 ENERGY',function(){remember();var error=deploy(v.id,api.combat(v.id));if(error)tell(error);});button('BACK',function(){mode='world';update();});}
   else if(mode==='demolish'){line('Remove this structure?',true);line('Return 50% of its Materials cost. Connections may stop producing. Occupied housing is protected.');button('CONFIRM DEMOLITION',function(){if(execute('demolish',{id:selected})){mode='world';update();}});button('CANCEL',function(){mode='world';update();});}
   else if(selected)inspect();draw();
  }
  function remember(){var d=m.settlement204,oldCamera=d.camera,oldFocus=d.focus;d.camera=Object.assign({},camera);d.focus=selected;if(save()!==true){d.camera=oldCamera;d.focus=oldFocus;}}
  function focus(id){var t=api.tile(id);if(!t)return;selected=id;camera.x=t.x;camera.y=t.y;mode='world';path=[];update();}
  el.querySelector('[data-objective]').onclick=function(){focus(api.objective(m).id);};el.querySelector('[data-home]').onclick=function(){focus('0,0');};el.querySelector('[data-menu]').onclick=function(){mode='menu';path=[];update();};el.querySelector('[data-workers]').onclick=function(){mode='people';update();};['world','build','people','research'].forEach(function(k){el.querySelector('[data-'+k+']').onclick=function(){mode=k;path=[];tool=null;if(k==='world')selected=null;update();};});el.querySelector('[data-minus]').onclick=function(){camera.scale=Math.max(28,camera.scale/1.2);draw();};el.querySelector('[data-plus]').onclick=function(){camera.scale=Math.min(90,camera.scale*1.2);draw();};
  function hit(e){var box=canvas.getBoundingClientRect();return Math.round((e.clientX-box.left-view.w/2)/camera.scale+camera.x)+','+Math.round((e.clientY-box.top-view.h/2)/camera.scale+camera.y);}
  canvas.onpointerdown=function(e){if(e.button!==0)return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);gesture=pointers.size===1?{x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y,moved:false}:null;if(mode==='place'&&pointers.size===1){var id=hit(e);if(api.tile(id)){path=[id];selected=id;update();}}};
  canvas.onpointermove=function(e){if(!pointers.has(e.pointerId))return;var before=Array.from(pointers.values());pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){gesture=null;var after=Array.from(pointers.values()),dist=function(p){return Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);};camera.scale=Math.max(28,Math.min(90,camera.scale*dist(after)/Math.max(1,dist(before))));draw();return;}if(!gesture)return;var dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)>8)gesture.moved=true;if(mode==='place'&&(tool==='road'||tool==='bridge')){var id=hit(e),t=api.tile(id),last=api.tile(path[path.length-1]);if(t&&last&&Math.abs(t.x-last.x)+Math.abs(t.y-last.y)===1&&path.indexOf(id)<0){path.push(id);update();}}else if(gesture.moved){camera.x=gesture.cx-dx/camera.scale;camera.y=gesture.cy-dy/camera.scale;draw();}};
  canvas.onpointerup=function(e){if(gesture&&!gesture.moved&&mode!=='place'){var id=hit(e);if(api.tile(id)){selected=id;mode='world';path=[];update();}}pointers.delete(e.pointerId);gesture=null;};function cancel(e){pointers.delete(e.pointerId);gesture=null;}canvas.onpointercancel=cancel;canvas.onlostpointercapture=cancel;canvas.oncontextmenu=function(e){e.preventDefault();};
  function resize(){var box=canvas.getBoundingClientRect(),ratio=Math.min(2,root.devicePixelRatio||1);view={w:box.width,h:box.height};canvas.width=box.width*ratio;canvas.height=box.height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);draw();}root.addEventListener('resize',resize);var ro=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;if(ro)ro.observe(canvas.parentElement);
  function animate(now){if(dead)return;if(now-lastFrame>=100&&!document.hidden){draw();lastFrame=now;}frame=root.requestAnimationFrame(animate);}if(root.requestAnimationFrame)frame=root.requestAnimationFrame(animate);
  var timer=setInterval(function(){var d=m.settlement204,now=Date.now();if(now-d.at>=(d.job||d.scout?5000:15000)){var before=JSON.stringify([d.job&&d.job.done,!!d.scout,d.notice]),r=api.tick(m,save,now);if(!r.ok)tell(r.message);else if(before!==JSON.stringify([m.settlement204.job&&m.settlement204.job.done,!!m.settlement204.scout,m.settlement204.notice])){tell(r.message);if(!pointers.size&&['world','people'].indexOf(mode)>=0)update();}}header();Array.prototype.forEach.call(sheet.querySelectorAll('[data-crew-timer]'),function(p){var j=m.settlement204[p.dataset.crewTimer];if(j)p.textContent=duration(api.eta(m,j))+' remaining · '+j.crew+' workers';});draw();},1000);
  resize();update();tell(m.settlement204.notice);return function(){if(dead)return;try{remember();}catch(e){console.warn('Could not save map position',e);}dead=true;clearInterval(timer);if(frame!==null&&root.cancelAnimationFrame)root.cancelAnimationFrame(frame);root.removeEventListener('resize',resize);if(ro)ro.disconnect();el.remove();};
 }
 root.LSCSettlementView={mount:mount,paint:paint};
})(typeof window!=='undefined'?window:globalThis);
