(function(root){
 'use strict';
 var api=root.LSCSettlement,basePaint=root.LSCSettlementView.paint;
 function signed(n){return (n>=0?'+':'')+n;}
 function duration(n){return n===null?'Paused':n<60?Math.ceil(n)+'s':Math.floor(n/60)+'m '+Math.ceil(n%60)+'s';}
 function paint(ctx,m,view,camera,selected,path,now){var display=Object.assign({},m,{settlement204:Object.assign({},m.settlement204,{job:null})}),d=m.settlement204;ctx.save();ctx.filter='grayscale(1)';basePaint(ctx,display,view,camera,selected,path);ctx.restore();ctx.save();ctx.beginPath();Object.keys(d.cleared).forEach(function(id){var t=api.tile(id);if(t)ctx.rect((t.x-camera.x)*camera.scale+view.w/2-camera.scale/2,(t.y-camera.y)*camera.scale+view.h/2-camera.scale/2,camera.scale,camera.scale);});ctx.clip();basePaint(ctx,display,view,camera,selected,path);ctx.restore();var edgeY=(api.bounds.minY-.5-camera.y)*camera.scale+view.h/2;if(edgeY>18&&edgeY<view.h){ctx.fillStyle='#bfd5cf';ctx.font='11px sans-serif';ctx.textAlign='center';ctx.fillText('REGION BOUNDARY',view.w/2,edgeY-8);}now=now||Date.now();(d.queue||[]).forEach(function(q){q.project.path.forEach(function(id){var t=api.tile(id);if(t){ctx.strokeStyle='#eac574';ctx.lineWidth=2;ctx.strokeRect((t.x-camera.x)*camera.scale+view.w/2-camera.scale/2+4,(t.y-camera.y)*camera.scale+view.h/2-camera.scale/2+4,camera.scale-8,camera.scale-8);}});});
  function at(id){var t=api.tile(id);return t?{x:(t.x-camera.x)*camera.scale+view.w/2,y:(t.y-camera.y)*camera.scale+view.h/2}:null;}
  function label(id,text,color){var p=at(id);if(!p)return;if(id!==selected&&id!=='0,0'&&(d.buildings[id]||camera.scale<48)){ctx.fillStyle=color||'#ecd4a0';ctx.beginPath();ctx.arc(p.x+camera.scale*.3,p.y-camera.scale*.3,4,0,Math.PI*2);ctx.fill();return;}ctx.font='bold 12px sans-serif';ctx.textAlign='center';var width=Math.min(250,ctx.measureText(text).width+14);ctx.fillStyle='#092327ee';ctx.fillRect(p.x-width/2,p.y-camera.scale/2-21,width,20);ctx.fillStyle=color||'#ffdfa0';ctx.fillText(text,p.x,p.y-camera.scale/2-7);}
  function crewDot(p,count,color){for(var i=0;i<Math.min(count,6);i++){var x=p.x+(i%3-1)*7,y=p.y+Math.floor(i/3)*9;ctx.fillStyle='#142522';ctx.fillRect(x-3,y+2,6,7);ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}}
  api.jobs(m).map(function(j){return {type:'job',j:j};}).concat(d.scout?[{type:'scout',j:d.scout}]:[]).forEach(function(entry){var type=entry.type,j=entry.j;if(!j)return;var extra=Math.max(0,(now-d.at)/1000)*api.speed(m,j),progress=Math.min(j.work[j.done||0],j.progress+extra),total=j.work[j.done||0],index=j.done||0,id=type==='job'?j.path[index]:j.target,p=at(id);if(!p)return;
   if(type==='job'){j.path.slice(index+1).forEach(function(k){var q=at(k);if(q){ctx.strokeStyle='#d9bd7888';ctx.lineWidth=1;ctx.strokeRect(q.x-camera.scale/2+3,q.y-camera.scale/2+3,camera.scale-6,camera.scale-6);}});ctx.save();ctx.beginPath();ctx.rect(p.x-camera.scale/2,p.y-camera.scale/2,camera.scale,camera.scale);ctx.clip();ctx.strokeStyle='#e3c28a';ctx.lineWidth=2;for(var x=-.3;x<=.31;x+=.3){ctx.beginPath();ctx.moveTo(p.x+x*camera.scale,p.y-camera.scale*.35);ctx.lineTo(p.x+x*camera.scale,p.y+camera.scale*.32);ctx.stroke();}ctx.beginPath();ctx.moveTo(p.x-camera.scale*.32,p.y);ctx.lineTo(p.x+camera.scale*.32,p.y);ctx.stroke();ctx.fillStyle='#092327';ctx.fillRect(p.x-camera.scale*.4,p.y+camera.scale*.34,camera.scale*.8,6);ctx.fillStyle='#efcd7b';ctx.fillRect(p.x-camera.scale*.4,p.y+camera.scale*.34,camera.scale*.8*progress/total,6);ctx.restore();var from=at(index?j.path[index-1]:j.origin||j.path[0])||p,phase=Math.min(1,progress/Math.max(1,total*.2));crewDot({x:from.x+(p.x-from.x)*phase,y:from.y+(p.y-from.y)*phase+Math.sin(now/180)*1.5},j.crew,'#edbf6a');label(id,j.crew?j.crew+' builders · '+duration(api.eta(m,j)):'Construction paused');}
   else {var outbound=Math.max(1,j.path.length-1)*20,returning=progress>=j.revealAt,ratio=returning?1-(progress-j.revealAt)/Math.max(1,total-j.revealAt):Math.min(1,progress/outbound);ratio=Math.max(0,Math.min(1,ratio));var pos=ratio*Math.max(0,j.path.length-1),lo=Math.floor(pos),hi=Math.min(j.path.length-1,lo+1),a=at(j.path[lo]),b=at(j.path[hi]);if(a&&b)crewDot({x:a.x+(b.x-a.x)*(pos-lo),y:a.y+(b.y-a.y)*(pos-lo)},j.crew,'#8ae3e1');ctx.strokeStyle='#80d8d5';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,camera.scale*.32,0,Math.PI*2);ctx.stroke();label(id,!j.crew?'Scouting paused':(returning?'Returning':progress>=outbound?'Surveying':'Traveling')+' · '+j.crew+' scouts · '+duration(api.eta(m,j)),'#9aeee2');}
  });
  Object.keys(d.buildings).forEach(function(id){var b=d.buildings[id],p=at(id);if(!p||b.kind==='house'||b.kind==='tower'||b.kind==='harbor')return;if(!api.connected(m,id))label(id,'Disconnected','#f3aa80');else if((b.kind==='workshop'?d.materials:d.food)>=api.storage(m))label(id,b.kind==='workshop'?'Full · crew available':'Full · feeding residents','#ecd4a0');else if(!b.workers)label(id,api.workers(m).available===0?'Workers on other duties':b.kind==='farm'?'Food staffing target filled':'Materials staffing target filled','#ced3c1');else {ctx.fillStyle='#d8e5a2';ctx.beginPath();ctx.arc(p.x+camera.scale*.25,p.y+Math.sin(now/350)*3,2,0,Math.PI*2);ctx.fill();}});
  (d.seaRoutes||[]).forEach(function(r){var linked=api.network(m).has(r.from)&&api.network(m).has(r.to);ctx.save();ctx.strokeStyle=linked?'#6adeee':'#81969a';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();(r.path||[]).forEach(function(id,i){var p=at(id);if(p){if(!i)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);}});ctx.stroke();ctx.restore();});
  api.landmarks.forEach(function(l){if(!d.visible[l.id]||d.claimed&&d.claimed[l.id])return;var p=at(l.id);ctx.fillStyle=d.cleared[l.id]?'#ffe18a':'#d8ded8';ctx.font='bold '+Math.max(12,camera.scale*.4)+'px sans-serif';ctx.textAlign='center';ctx.fillText('◆',p.x,p.y+camera.scale*.12);});
  if(d.study)label('0,0',d.study.crew?d.study.crew+' researching · '+duration(api.eta(m,d.study)):'Research paused','#9aeee2');
  api.towns.forEach(function(t){var id=t.x+','+t.y,p=at(id);if(!p||!d.visible[id]||camera.scale<55&&id!==selected)return;ctx.fillStyle='#112b29';ctx.fillRect(p.x-camera.scale*.44,p.y+camera.scale*.31,camera.scale*.88,camera.scale*.18);ctx.fillStyle='#eee3b8';ctx.font='bold '+Math.max(8,Math.min(12,camera.scale*.14))+'px sans-serif';ctx.textAlign='center';ctx.fillText(t.name.toUpperCase(),p.x,p.y+camera.scale*.46,camera.scale*.84);});
  if(d.event&&now-d.event.at<5500){var p=at(d.event.id);if(p){ctx.textAlign='center';ctx.font='bold 13px sans-serif';ctx.fillStyle='#d4f1ac';ctx.fillText(d.event.text,p.x,p.y-25-Math.max(0,now-d.event.at)/250,Math.min(330,view.w-16));}}
 }
 function mount(panel,m,save,refresh,navigate,deploy,power){var init=api.initialize(m,save);if(!init.ok){panel.textContent=init.message;return function(){};}var away=Date.now()-m.settlement204.at,resumed=api.resume(m,save);var el=document.createElement('section');el.id='settlement-world';el.style.cssText='position:fixed;inset:0;z-index:30500;background:#071a1d;color:#edf1df;display:flex;flex-direction:column;box-sizing:border-box;padding-top:env(safe-area-inset-top);font:15px system-ui';
  el.innerHTML='<header><div class="settle-title"><b>LAST STAND · SETTLEMENT</b><button data-menu aria-label="Settlement menu">☰</button></div><div data-resources></div><button data-workers></button><button data-objective></button></header><main><canvas></canvas><div class="map-controls"><button data-minus aria-label="Zoom out">−</button><button data-plus aria-label="Zoom in">+</button><button data-home>HQ</button><button data-expedition>⌖ SCOUTING</button></div></main><div data-sheet></div><div data-notice role="status"></div><nav><button data-world>WORLD</button><button data-build>BUILD</button><button data-people>PEOPLE</button><button data-research>KNOWLEDGE</button></nav>';
  var style=document.createElement('style');style.textContent='#settlement-world header{padding:6px 10px}#settlement-world .settle-title{display:flex;align-items:center;justify-content:space-between;font-size:13px}#settlement-world button{min-height:44px;padding:9px 11px;margin:2px;border:1px solid #729a8c;border-radius:8px;background:#244a44;color:#fff3d4;font:bold 13px system-ui}#settlement-world button:disabled{opacity:.48}#settlement-world [data-objective],#settlement-world [data-workers]{display:block;width:100%;text-align:left;margin:3px 0}#settlement-world [data-workers]{font-size:13px;min-height:36px;background:transparent}#settlement-world [data-resources]{font-size:15px;font-weight:700}#settlement-world main{position:relative;flex:1;min-height:140px;overflow:hidden}#settlement-world canvas{width:100%;height:100%;touch-action:none}#settlement-world .map-controls{position:absolute;right:6px;top:6px}#settlement-world [data-sheet]{padding:0 12px;max-height:43vh;overflow:auto;background:#112d30}#settlement-world [data-sheet] h3{margin:10px 0;font-size:18px}#settlement-world p{margin:8px 0;line-height:1.4}#settlement-world nav{display:flex;gap:3px;padding:5px 6px max(6px,env(safe-area-inset-bottom))}#settlement-world nav button{flex:1;padding:8px 2px;font-size:12px}#settlement-world [data-notice]{padding:5px 10px;font-size:12px;color:#e8ce90;max-height:36px;overflow:hidden}#settlement-world .crew-row{display:flex;align-items:center;gap:6px;flex-wrap:wrap}';style.textContent+='#settlement-world [data-sheet]{max-height:38vh;padding:0 8px}#settlement-world .tile-icon{width:68px;height:64px;padding:3px;font-size:11px;vertical-align:top}#settlement-world .tile-icon span{display:block;font-size:25px;line-height:30px}#settlement-world .tile-icon.locked{border-color:#b79e68}#settlement-world [data-sheet] h3{font-size:15px;margin:6px 0}#settlement-world [data-sheet] p{font-size:13px}#settlement-world [data-workers]{min-height:28px;font-size:11px;padding:3px}#settlement-world [data-objective]{min-height:32px;font-size:12px;padding:5px}#settlement-world [data-resources]{font-size:12px}#settlement-world [data-notice]:empty{display:none}';style.textContent+='#settlement-world [data-sheet].expanded-panel{max-height:none;flex:1;padding:10px 14px}#settlement-world main.minimap{flex:0;height:72px;min-height:72px}#settlement-world .research-card{padding:9px;margin:6px 0;border:1px solid #537a73;border-radius:9px;background:#173b3b}#settlement-world .research-card.completed{border-color:#73bf8c;background:#173f31}#settlement-world .research-card progress{width:100%;accent-color:#e5c462}#settlement-world [data-expedition]{display:block;margin-left:auto;font-size:11px}';el.appendChild(style);document.body.appendChild(el);panel.innerHTML='';
  var canvas=el.querySelector('canvas'),ctx=canvas.getContext('2d'),sheet=el.querySelector('[data-sheet]'),camera=Object.assign({},m.settlement204.camera||{x:1,y:0,scale:36}),view={w:390,h:500},selected=m.settlement204.focus||null,mode='world',tool=null,path=[],placementSites={},count=m.settlement204.defaultCrew||4,dead=false,pointers=new Map(),gesture=null,pinch=null,frame=null,lastFrame=0,researchNode=null,noticeUntil=0,pendingUpdate=false,expanded=false,rejected=null,roadBatch=null,showCompleted=false,shippingFrom=null;
  if(away>=60000&&resumed.ok&&m.settlement204.returnReport)mode='report';
  if(m.settlement204.mapUI!==210)camera.scale=36;
  if(selected&&api.tile(selected)){camera.x=api.tile(selected).x;camera.y=api.tile(selected).y;}
  function tell(text){el.querySelector('[data-notice]').textContent=text||'';noticeUntil=text?Date.now()+8000:0;}
  function button(text,fn,disabled){var b=document.createElement('button');b.textContent=text;b.disabled=!!disabled;b.onclick=function(){tell('');fn();};sheet.appendChild(b);return b;}
  function line(text,title){var p=document.createElement(title?'h3':'p');p.textContent=text;sheet.appendChild(p);return p;}
  function execute(kind,payload){var r=api.action(m,save,kind,payload);tell(r.message);refresh();update();return r.ok;}
  function draw(){if(dead)return;var box=canvas.getBoundingClientRect();if(box.width!==view.w||box.height!==view.h){var ratio=Math.min(2,root.devicePixelRatio||1);view={w:box.width,h:box.height};canvas.width=box.width*ratio;canvas.height=box.height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);}paint(ctx,m,view,camera,selected,path,Date.now());if(rejected&&Date.now()<rejected.until&&api.tile(rejected.id)){var t=api.tile(rejected.id),x=(t.x-camera.x)*camera.scale+view.w/2,y=(t.y-camera.y)*camera.scale+view.h/2;ctx.strokeStyle='#ff6c65';ctx.lineWidth=4;ctx.strokeRect(x-camera.scale/2+2+Math.sin(Date.now()/35)*2,y-camera.scale/2+2,camera.scale-4,camera.scale-4);}if(mode==='place'){Object.keys(placementSites).forEach(function(id){var t=api.tile(id),x=(t.x-camera.x)*camera.scale+view.w/2-camera.scale/2,y=(t.y-camera.y)*camera.scale+view.h/2-camera.scale/2;if(x+camera.scale<0||x>view.w||y+camera.scale<0||y>view.h)return;ctx.fillStyle=placementSites[id].ok?'#83e1a029':'#00000088';ctx.fillRect(x,y,camera.scale,camera.scale);if(placementSites[id].ok){ctx.strokeStyle='#8ff0a6';ctx.lineWidth=2;ctx.strokeRect(x+2,y+2,camera.scale-4,camera.scale-4);}});if(tool==='tower'&&path.length){api.towerArea(m,path[0]).forEach(function(id){var t=api.tile(id),x=(t.x-camera.x)*camera.scale+view.w/2-camera.scale/2,y=(t.y-camera.y)*camera.scale+view.h/2-camera.scale/2;ctx.strokeStyle='#83e5ef';ctx.lineWidth=1;ctx.strokeRect(x+3,y+3,camera.scale-6,camera.scale-6);});}}}
  function chooseBuild(k){tool=k;mode='place';path=[];expanded=false;roadBatch=null;if(selected&&k!=='road'&&k!=='bridge'){var site=api.placement(m,k,selected,[]);if(site.ok)path=[selected];else tell(site.message);}update();}
  function header(){var d=m.settlement204,w=api.workers(m);el.querySelector('[data-resources]').textContent='Food '+Math.floor(d.food)+' · Materials '+Math.floor(d.materials)+' · Credits '+Math.floor(m.credits);el.querySelector('[data-workers]').textContent=w.available+'/'+w.total+' available · '+w.assigned+' in production · '+(w.scouts+w.builders)+' on projects · '+w.scholars+' researching';el.querySelector('[data-objective]').textContent=api.objective(m).text;var scout=el.querySelector('[data-expedition]');scout.textContent=d.scout?'⌖ '+api.scoutStatus(m)+' · '+duration(api.eta(m,d.scout)):'⌖ SCOUT';}
  function chooser(value,change){button('−',function(){change(Math.max(1,value-1));},value<=1);button(value+' WORKERS',function(){},true);button('+',function(){change(Math.min(6,value+1));},value>=6);}
  function preview(kind,payload){var p=api.preview(m,kind,payload,count);chooser(count,function(n){count=n;update();});if(!p.ok){line(p.message);return;}if(kind==='connection')path=p.project.path;line(p.project.path.length+(kind==='scout'?' route squares':' tiles')+' · '+duration(p.seconds)+' · '+p.project.materials+' Materials · '+p.project.credits+' Credits'+(p.project.food?' · '+p.project.food+' Food':''));if(expanded)line('Food balance '+p.before.food.toFixed(1)+' → '+p.after.food.toFixed(1)+'/min; Materials '+p.before.materials.toFixed(1)+' → '+p.after.materials.toFixed(1)+'/min. Idle workers are used first, then production is adjusted.');if(kind==='connection'&&payload.town===1&&!m.settlement204.welcomed[1])line('First-village crew training: this introductory route builds faster.');var occupied=m.settlement204[kind==='scout'?'scout':'job'],queueing=kind!=='scout'&&p.waiting;if(queueing)line('Waiting for workers or prerequisite construction. Estimate excludes waiting time. Costs reserved now; workers assigned at start.');button(queueing?'ADD TO QUEUE':kind==='scout'&&occupied?'CREW ALREADY ON A PROJECT':'CONFIRM '+(kind==='scout'?'SCOUTING':kind==='connection'?'CONNECTION':'BUILD'),function(){payload=Object.assign({},payload,{crew:count});if(execute(kind==='scout'?'scout':kind==='connection'?'connection':'build',payload)){mode='world';path=[];update();}},kind==='scout'?!!occupied:(m.settlement204.queue||[]).length>=12);}
  function queuePanel(){var d=m.settlement204;if(!(d.queue||[]).length)return;line('Construction queue · '+d.queue.length+'/12',true);if(d.queueNotice)line('Waiting: '+d.queueNotice);d.queue.forEach(function(q,i){line((i+1)+'. '+(q.kind==='connection'?'Village connection':api.defs[q.kind].name)+' · '+q.crew+' workers · '+q.credits+' Credits / '+q.materials+' Materials reserved');button('CANCEL QUEUED '+q.id,function(){execute('cancelQueue',{queueId:q.id});});});}
  function crewPanel(type,project){var j=project||m.settlement204[type];if(!j)return;line(type==='study'?'Researchers · '+api.knowledge.find(function(n){return n.id===j.node;}).name:type==='job'?(j.kind==='connection'?'Connection':api.defs[j.kind].name)+' · '+j.path[0]:'Scouting crew',true);var timer=line('');timer.dataset.crewTimer=type;timer.dataset.projectId=j.projectId||'';timer.textContent=duration(api.eta(m,j))+' remaining · '+j.crew+' workers';if(type==='job')line((j.done||0)+'/'+j.path.length+' sections complete.');button('VIEW CREW',function(){focus(type==='job'?j.path[j.done||0]:j.target);});button('− WORKER',function(){execute('crew',{type:type,projectId:j.projectId,count:j.crew-1});},j.crew<=0);button('+ WORKER',function(){execute('crew',{type:type,projectId:j.projectId,count:j.crew+1});},j.crew>=6);button(j.crew?'RECALL / PAUSE':'RESUME WITH '+count, function(){execute('crew',{type:type,projectId:j.projectId,count:j.crew?0:count});});}
  var icons={farm:'🌾',house:'⌂',workshop:'⚒',tower:'♜',harbor:'⚓',road:'━',bridge:'≋',clear:'⛏',scout:'⌖'};
  function icon(k,label,fn,reason){var b=button('',fn);b.className='tile-icon'+(reason?' locked':'');var pic=document.createElement('span');pic.textContent=icons[k]||'◇';b.appendChild(pic);var name=document.createElement('small');name.textContent=label+(reason?' 🔒':'');b.appendChild(name);b.setAttribute('aria-label',label+(reason?': '+reason:''));return b;}
  function contextual(){var d=m.settlement204,t=api.tile(selected);if(!t)return;var b=d.buildings[selected];line(!d.visible[selected]?'Unknown territory':t.town?api.town(t.town).name:b?api.defs[b.kind].name:t.terrain.toUpperCase(),true);button(expanded?'⌄ LESS':'⌃ DETAILS',function(){expanded=!expanded;update();});if(d.scout)icon('scout','Scouting',function(){mode='expedition';update();});if(expanded){inspect();return;}if(!d.visible[selected]){line('Scout from a visible frontier to reveal this tile.');return;}
   if(api.blockedSite(m,selected)){icon('workshop','Crew',function(){expanded=true;update();});return;}
   if(t.town||b||d.roads[selected]||selected==='0,0'){icon('house',t.town?'Village':'Manage',function(){expanded=true;update();});}
   if(!b&&!t.town&&selected!=='0,0'&&!d.roads[selected]){var choices=t.terrain==='water'?['bridge']:!d.cleared[selected]?['clear','road']:t.terrain==='hill'?['workshop','tower','house','road']:['farm','house','road'];if(d.cleared[selected]&&api.coastal(selected))choices.push('harbor');choices.forEach(function(k){var site=api.placement(m,k,selected,[]);icon(k,api.defs[k].name.replace('Scouting ','').replace(' Land',''),function(){if(!site.ok){tell(site.message);return;}chooseBuild(k);},site.ok?'':site.message);});}
   var scout=api.preview(m,'scout',{id:selected},1);if(scout.ok&&!d.scout)icon('scout','Scout',function(){mode='scout';update();});
  }
  function roadPanel(){line(icons[tool]+' '+api.defs[tool].name+' · QUICK TOOL ACTIVE',true);line('Green outlines show where this route can extend. Tap to order; drag to move. Clearing included.');chooser(count,function(n){count=n;roadBatch=null;update();});line('Per tile: '+api.defs[tool].credits+' Credits · '+api.defs[tool].materials+' Materials · clearing 0–8 Food');button('DONE',function(){tool=null;mode='world';path=[];roadBatch=null;update();});}
  function inspect(){var d=m.settlement204,t=api.tile(selected),b=d.buildings[selected];if(!t)return;var v=t.town?api.town(t.town):null;line(!d.visible[selected]?'Unknown territory':v?v.name+' · '+api.stars(v.id)+' star':selected==='0,0'?'Settlement HQ':b?api.defs[b.kind].name:t.terrain.toUpperCase(),true);
   if(!d.visible[selected]){line('Send a scouting crew from a revealed frontier. They travel, survey, then return.');return;}
   if(t.landmark)line(t.landmark.name+(d.claimed&&d.claimed[selected]?' · recovered':' · clear to recover '+t.landmark.credits+' Credits, '+t.landmark.materials+' Materials and '+t.landmark.food+' Food.'));
   if(selected==='0,0'){line('Housing '+d.population+'/'+api.housing(m)+' · Storage '+api.storage(m)+' Food / Materials.');button('BUILD HOUSING',function(){chooseBuild('house');});button('PEOPLE & CREWS',function(){mode='people';update();});button('SAVED CAMPAIGNS',function(){navigate('campaigns');});button('EQUIPMENT',function(){navigate('inventory');});}
   if(b){line(api.connected(m,selected)?'Connected to the settlement.':'Disconnected: build a road beside this site.');if(api.defs[b.kind].capacity){line(b.workers+'/'+api.defs[b.kind].capacity+' workers · '+(api.connected(m,selected)?(b.workers*(b.kind==='farm'?api.farmRate(m):api.materialRate(m))).toFixed(1):'0')+' '+(b.kind==='farm'?'Food':'Materials')+'/min before storage limits.');button('MANAGE PRODUCTION',function(){mode='people';update();});}else if(b.kind==='harbor'){line('Boats let scouts cross revealed water and land on known shores. Link two harbors to carry your road network across water. No permanent workers required.');var net=api.network(m),routes=d.seaRoutes||[];api.ports(m).filter(function(k){return k!==selected;}).forEach(function(k){var exists=routes.some(function(r){return r.from===selected&&r.to===k||r.to===selected&&r.from===k;});if(exists)line('✓ Water route to '+k+(net.has(selected)&&net.has(k)?' · ACTIVE':' · reconnect harbor to HQ'));else if(net.has(k)||net.has(selected))button('LINK HARBOR '+k,function(){shippingFrom=net.has(selected)?selected:k;selected=shippingFrom===selected?k:selected;mode='shipping';update();});});if(api.ports(m).length<2)line('Next: scout the far shore, clear coastal land, then build a second harbor.');}else if(b.kind==='tower')line('Survey complete · radius 8 tiles. Revealed land stays known. '+(api.towerArea(m,selected).length<289?'Coverage reaches this region’s boundary. ':'')+'No permanent workers required.');else line(api.houseSpaces(m)+' housing spaces. Residents '+d.population+'/'+api.housing(m)+'.');}
   if(v){var linked=api.network(m).has(selected),defended=!!d.defended[v.id],joined=!!d.welcomed[v.id];line(v.specialty+' · '+v.benefit+'.');line('4 residents · +'+(2*api.stars(v.id)+(v.id===6?4:0))+' Credits/min after integration.');line((defended?'✓ Defended':'○ Needs defense')+' · '+(linked?'✓ Connected':'○ Needs road')+' · '+(joined?'✓ Integrated':'○ Survivors waiting'));if(!linked)button('CONNECT VILLAGE',function(){mode='connect';path=[];update();});if(!defended)button('DEFENSE BRIEFING',function(){mode='brief';update();});else if(!joined){line('Welcome requirements: connected road, 4 free housing spaces, 20 Food.');button('WELCOME 4 SURVIVORS',function(){execute('welcome',{town:v.id});},!linked||api.housing(m)<d.population+4||d.food<20);}else line(linked?'Income and village specialty are active.':'Reconnect its road to restore income and its specialty.');}
   api.jobs(m).filter(function(j){return j.path.indexOf(selected)>=0;}).forEach(function(j){crewPanel('job',j);});if(d.scout&&d.scout.target===selected)crewPanel('scout');
   if(!d.cleared[selected]&&t.terrain!=='water'&&!v)button('CLEAR LAND',function(){chooseBuild('clear');});
   if(!d.scout&&Object.keys(api.tiles).some(function(k){var n=api.tile(k);return Math.abs(n.x-t.x)+Math.abs(n.y-t.y)===1&&!d.visible[k];}))button('PLAN SCOUTING',function(){mode='scout';path=[];update();});
   if(d.cleared[selected]&&!b&&!v&&selected!=='0,0')button('BUILD HERE',function(){mode='build';update();});
   if(b||d.roads[selected]&&selected!=='0,0')button('DEMOLISH…',function(){mode='demolish';update();});
  }
  function update(){resetTouches();header();sheet.innerHTML='';var large=['research','researchDetail','people','specialties','report','economy'].indexOf(mode)>=0;sheet.className=large?'expanded-panel':'';el.querySelector('main').className=large?'minimap':'';var d=m.settlement204;if(mode==='connect'&&selected&&api.network(m).has(selected)){mode='world';path=[];}placementSites={};if(mode==='place'&&(tool==='road'||tool==='bridge')){var forecast=api.plannedWorld(m),fd=forecast.settlement204,net=api.network(forecast);Object.keys(d.visible).forEach(function(id){var t=api.tile(id);if(!t)return;placementSites[id]={ok:!fd.roads[id]&&!fd.buildings[id]&&(tool==='bridge')===(t.terrain==='water')&&[[1,0],[-1,0],[0,1],[0,-1]].some(function(v){return net.has((t.x+v[0])+','+(t.y+v[1]));})};});}else if(mode==='place')Object.keys(d.visible).forEach(function(id){if(api.tile(id))placementSites[id]=api.placement(m,tool,id,path);});

   if(mode==='people'){line('People · '+d.population+' residents',true);if(api.economy(m).foodFull||api.economy(m).materialsFull)line('STORAGE FULL · surplus workers released for projects',true);line('Priority: '+(d.priority||'manual').toUpperCase());['balanced','growth','exploration'].forEach(function(k){button(k.toUpperCase(),function(){execute('priority',{value:k});},d.priority===k);});line('Balanced: steady Food and Materials. Growth: more Materials. Exploration: extra Food and up to 2 workers held available. Manual target changes switch to Custom. Priorities never spend or start projects.');button('RESOURCE OVERVIEW',function(){mode='economy';update();});button('TRADE SURPLUS',function(){mode='trade';update();});line('Housing '+d.population+'/'+api.housing(m)+' · Storage '+api.storage(m)+' each. Existing excess stock is preserved; production pauses above capacity.');['farm','workshop'].forEach(function(k){line((k==='farm'?'Farmers':'Workshop workers')+' · '+Object.keys(d.buildings).reduce(function(n,id){return n+(d.buildings[id].kind===k?d.buildings[id].workers:0);},0)+' working / '+d.targets[k]+' target · '+api.capacity(m,k)+' jobs',true);button('− '+(k==='farm'?'FOOD':'MATERIALS'),function(){execute('target',{kind:k,count:d.targets[k]-1});},d.targets[k]<=0);button('+ '+(k==='farm'?'FOOD':'MATERIALS'),function(){execute('target',{kind:k,count:d.targets[k]+1});},d.targets[k]>=d.population);});var e=api.economy(m);line('Actual stock change: Food '+e.foodNet.toFixed(1)+'/min · Materials '+e.materialsNet.toFixed(1)+'/min.');line('Farms supply '+e.foodGross.toFixed(1)+' Food/min; residents consume '+e.foodUse.toFixed(1)+'/min.');if(e.foodFull)line('Food storage full. Farms maintain residents; surplus is not stored. Existing stock is preserved.');if(e.materialsFull)line('Materials storage full. Workshop workers are available for projects. Your target is retained and resumes automatically after spending Materials.');if(e.shortage)line('Food shortage: Materials production is halved. Assign farmers or connect another farm.');line('Food funds expeditions and welcomes survivors. Materials build roads, bridges, housing and production sites. Credits pay for construction and combat upgrades.');button('PROTECT FOOD: '+(d.protectFood?'ON':'OFF'),function(){execute('protect',{enabled:!d.protectFood});});line('Targets refill when crews return or residents arrive. Food protection reserves '+api.foodMinimum(m)+' farmers; build connected farms if capacity is short.');api.jobs(m).forEach(function(j){crewPanel('job',j);});queuePanel();crewPanel('scout');crewPanel('study');if(!d.job&&!d.scout&&!d.study&&!(d.queue||[]).length)line('No active projects. Select a village to connect or a frontier to scout.');}
   else if(mode==='expedition'){line('Scouting',true);line('Explore 12 towns across a 61 × 49 frontier. Build a harbor beside water to launch scouts; connect two harbors to extend supplies. Only space beyond the outer boundary is unavailable.');if(d.scout){line(api.scoutStatus(m)+' · destination '+d.scout.target);crewPanel('scout');}else{line('No expedition in progress. Select a visible land tile beside black unexplored territory.');button('FIND SCOUTING FRONTIER',function(){var target=Object.keys(api.tiles).find(function(k){return api.preview(m,'scout',{id:k},1).ok;});if(target){focus(target);count=1;mode='scout';update();}else tell('No reachable frontier or no free crew. Check People; this region has a fixed boundary.');});}if(d.discovery)line('Latest survey: '+d.discovery.tiles+' new tiles · '+d.discovery.villages+' villages discovered.');button('BACK TO WORLD',function(){mode='world';update();});}
   else if(mode==='economy'){var e=api.economy(m);line('Settlement resources',true);line('FOOD · '+Math.floor(d.food)+' / '+e.capacity,true);line('Farms +'+e.foodGross.toFixed(1)+'/min · residents −'+e.foodUse.toFixed(1)+'/min · actual stock change '+e.foodNet.toFixed(1)+'/min.');line('Pays for expeditions, clearing and welcoming residents. '+(e.shortage?'SHORTAGE: staff a connected farm. Materials output is halved.':e.foodFull?'Storage full: excess production is not saved.':''));line('MATERIALS · '+Math.floor(d.materials)+' / '+e.capacity,true);line('Actual stock change +'+e.materialsNet.toFixed(1)+'/min. Pays for buildings, roads and research. '+(e.materialsFull?'Storage full: workshop workers are released until Materials are spent.':''));line('CREDITS · '+Math.floor(m.credits),true);line('Base income +2/min; connected integrated villages +'+(api.income(m)-2)+'/min. Pays for construction, research, and combat upgrades.');line('POPULATION · '+d.population+' / '+api.housing(m)+' housing',true);line('Each integrated village adds 4 residents. Defend it, connect a road, provide housing and 20 Food.');button('MANAGE PEOPLE',function(){mode='people';update();});button('TRADE SURPLUS',function(){mode='trade';update();});button('BACK TO WORLD',function(){mode='world';update();});}
   else if(mode==='report'){line('While you were away',true);var r=d.returnReport;if(r){line(r.minutes+' minutes simulated · maximum 8 hours');line('Food '+signed(r.food)+' · Materials '+signed(r.materials)+' · Credits '+signed(r.credits));line(r.buildings+' buildings completed · '+r.cleared+' tiles reclaimed · '+r.visible+' tiles revealed · '+r.knowledge+' technologies completed.');}button('CONTINUE',function(){mode='world';update();});button('REVIEW PEOPLE',function(){mode='people';update();});}
   else if(mode==='trade'){line('Village trade',true);line('100 Food or Materials → '+(api.learned(m,'barter')?65:50)+' Credits. Requires an integrated, connected village. Food reserve: '+Math.max(60,d.population*2.5)+' (at least 10 minutes of consumption); Materials reserve: 60.');button('SELL 100 FOOD · +'+(api.learned(m,'barter')?65:50)+' CREDITS',function(){execute('trade',{resource:'food'});});button('SELL 100 MATERIALS · +'+(api.learned(m,'barter')?65:50)+' CREDITS',function(){execute('trade',{resource:'materials'});});button('BACK TO PEOPLE',function(){mode='people';update();});}
   else if(mode==='build'){line('Choose a project',true);if(d.job){line('Construction active · '+duration(api.eta(m,d.job))+' · '+(d.queue||[]).length+'/12 queued. Independent projects can start with another crew.');button('VIEW ACTIVE CREW',function(){focus(d.job.path[d.job.done||0]);});}Object.keys(api.defs).filter(function(k){return k!=='shipping';}).forEach(function(k){var def=api.defs[k];button(def.name+' · '+def.materials+' Materials / '+def.credits+' Credits',function(){chooseBuild(k);},(d.queue||[]).length>=12||(k==='tower'||k==='harbor')&&!api.learned(m,'survey'));if((k==='tower'||k==='harbor')&&!api.learned(m,'survey'))line(def.name+' requires Field Surveying.');});queuePanel();line('For village routes, tap the village and choose Connect Village. Its crew clears and builds the route.');}
   else if(mode==='place'&&(tool==='road'||tool==='bridge'))roadPanel();
   else if(mode==='place'){line('Place '+api.defs[tool].name,true);button(expanded?'LESS':'DETAILS',function(){expanded=!expanded;update();});if(expanded)line('Green outlined squares are valid sites. Dim squares cannot accept this project.');if(expanded)line(tool==='road'||tool==='bridge'?'Trace adjacent squares from a connected or planned road.':tool==='tower'?'Select a cleared hill beside a connected or planned road.':tool==='harbor'?'Select cleared land directly beside water.':tool==='farm'?'Select cleared plains or a riverbank.':tool==='workshop'?'Select a cleared hill.':'Select cleared land for housing.');if(tool==='tower'){line('Cleared hill beside a connected road · survey radius 8. Cyan outlines show coverage, not hidden contents.');if(path.length){var area=api.towerArea(m,path[0]),unseen=area.filter(function(k){return !d.visible[k];}).length;line(unseen+' unknown tiles will be revealed on completion.');if(area.length<289)line('Map boundary: coverage is clipped at the edge of this region.');if(!unseen)line('No new territory here. Choose a hill near unexplored land.');}}line(({harbor:'Launch scouting boats. Connect two completed harbors over revealed water to supply coastal towns.',farm:'Up to 4 farmers produce Food for residents and expeditions.',workshop:'Up to 4 workers produce construction Materials.',house:'Adds '+api.houseSpaces(m)+' housing spaces.',clear:'Crew clears this tile for construction. Hills cost 8 Food; other land costs 4.',tower:'Reveals nearby territory when construction finishes.'})[tool]||'');if(path.length)preview(tool,{type:tool,id:path[0],path:path});button('CANCEL',function(){mode='world';path=[];update();});}
   else if(mode==='connect'){var v=api.town(api.tile(selected).town);line('Connect '+v.name,true);line('Distance sets the workload. Extra workers reduce time; Materials cost stays fixed. Progress is preserved when paused.');preview('connection',{town:v.id});button('CANCEL',function(){mode='world';path=[];update();});}
   else if(mode==='shipping'){line('Establish water route',true);line('Harbor '+shippingFrom+' → '+selected+'. A completed route connects their road networks.');preview('shipping',{type:'shipping',id:selected,from:shippingFrom});button('CANCEL',function(){mode='world';update();});}
   else if(mode==='scout'){line('Send a scouting crew',true);var area=api.surveyArea(m,selected),unknown=area.filter(function(k){return !d.visible[k];}).length;line(unknown+' unknown tiles within survey coverage.');if(area.length<Math.pow(api.surveyRadius(m)*2+1,2))line('Region boundary: coverage stops at the edge. Black space outside this region is not explorable.');preview('scout',{id:selected});button('CANCEL',function(){mode='world';path=[];update();});}
   else if(mode==='research'){line('Village Knowledge',true);var completed=api.knowledge.filter(function(n){return api.learned(m,n.id);}),available=api.knowledge.filter(function(n){return api.researchState(m,n.id).ok;});line(completed.length+' of '+api.knowledge.length+' technologies completed · '+(d.study?'1 research in progress':'No research in progress'));if(d.study){var n=api.knowledge.find(function(n){return n.id===d.study.node;});line('IN PROGRESS · '+n.name,true);var bar=document.createElement('progress');bar.dataset.researchProgress='true';bar.max=d.study.work[0];bar.value=d.study.progress;sheet.appendChild(bar);crewPanel('study');}var readyNext=api.knowledge.filter(function(n){return (!d.study||d.study.node!==n.id)&&api.researchState(m,n.id).readyNext;});line(available.length+' available now'+(d.study?' · '+readyNext.length+' ready next (research slot occupied)':''));['Agriculture','Construction','Exploration','Industry','Defense'].forEach(function(branch){var nodes=api.knowledge.filter(function(n){return n.branch===branch&&!api.learned(m,n.id)&&(!d.study||d.study.node!==n.id);});if(!nodes.length)return;line(branch,true);nodes.forEach(function(n){var state=api.researchState(m,n.id);button((state.ok?'RESEARCH · ':state.readyNext?'READY NEXT · ':'🔒 ')+n.name,function(){researchNode=n.id;mode='researchDetail';update();});line(n.effect);line(state.ok?n.credits+' Credits · '+n.materials+' Materials · '+duration(Math.ceil(n.work/Math.pow(count,.9)))+' with '+count+' workers':state.message);});});button((showCompleted?'HIDE':'VIEW')+' COMPLETED ('+completed.length+')',function(){showCompleted=!showCompleted;update();});if(showCompleted)completed.forEach(function(n){var row=line('✓ '+n.name+' · COMPLETED — BONUS ACTIVE',true);row.className='research-card completed';line(n.effect);});if(completed.length===api.knowledge.length)line('All available technologies completed. All bonuses are active.');button('VILLAGE SPECIALTIES',function(){mode='specialties';update();});}
   else if(mode==='researchDetail'){var n=api.knowledge.find(function(n){return n.id===researchNode;});line(n.name,true);line(n.effect+'.');if(n.id==='survey')line('Also unlocks hilltop Scouting Towers (radius 8) and coastal Harbors for boat expeditions and water supply routes.');if(api.learned(m,n.id))line('✓ COMPLETED — BONUS ACTIVE');else if(d.study&&d.study.node===n.id)crewPanel('study');else{var state=api.researchState(m,n.id);line(n.materials+' Materials · '+n.credits+' Credits');if(!state.ok)line(state.message);else{chooser(count,function(v){count=v;update();});var p=api.researchPreview(m,n.id,count);line(p.ok?duration(p.seconds)+' · Food '+p.after.foodNet.toFixed(1)+'/min · Materials '+p.after.materialsNet.toFixed(1)+'/min while researching':p.message);button('RESEARCH '+n.name.toUpperCase(),function(){execute('research',{node:n.id,crew:count});},!p.ok||m.credits<n.credits||d.materials<n.materials);}}button('BACK TO KNOWLEDGE',function(){mode='research';update();});}
   else if(mode==='specialties'){line('Village specialties',true);api.towns.filter(function(t){return d.visible[t.x+','+t.y];}).forEach(function(t){line(t.name,true);line(t.benefit+' · '+(d.welcomed[t.id]&&api.network(m).has(t.x+','+t.y)?'ACTIVE':'Integrate and connect'));});button('BACK TO KNOWLEDGE',function(){mode='research';update();});}
   else if(mode==='menu'){line('Settlement',true);[['Saved campaigns','campaigns'],['Equipment','inventory'],['Combat commander','commander'],['HQ upgrades','hq'],['Special Operations','operations']].forEach(function(item){button(item[0],function(){navigate(item[1]);});});}
   else if(mode==='brief'){var v=api.town(api.tile(selected).town);line('Defend '+v.name+' · '+'★'.repeat(api.stars(v.id)),true);line(api.townProfile(v.id).threat+'.');line(power(api.combat(v.id)));var bonus=api.defenseBonuses(m);line('Knowledge bonuses: damage +'+Math.round(bonus.damage*100)+'% · command-post health +'+Math.round(bonus.hq*100)+'% · abilities +'+Math.round(bonus.artillery*100)+'%.');line('1 Energy. Defend and connect the village, then provide housing and Food to welcome its residents. Defeat preserves settlement progress.');button('DEPLOY · 1 ENERGY',function(){remember();var error=deploy(v.id,api.combat(v.id));if(error)tell(error);});button('BACK',function(){mode='world';update();});}
   else if(mode==='demolish'){line('Remove this structure?',true);line('Return 50% of its Materials cost. Connections may stop producing. Occupied housing is protected.');button('CONFIRM DEMOLITION',function(){if(execute('demolish',{id:selected})){mode='world';update();}});button('CANCEL',function(){mode='world';update();});}
   else if(selected)contextual();draw();
  }
  function remember(){var d=m.settlement204;d.mapUI=210;var oldCamera=d.camera,oldFocus=d.focus;d.camera=Object.assign({},camera);d.focus=selected;if(save()!==true){d.camera=oldCamera;d.focus=oldFocus;}}
  function focus(id){tell('');var t=api.tile(id);if(!t)return;selected=id;camera.x=t.x;camera.y=t.y;mode='world';path=[];update();}
  el.querySelector('[data-expedition]').onclick=function(){mode='expedition';update();};el.querySelector('[data-resources]').onclick=function(){mode='economy';update();};
  el.querySelector('[data-objective]').onclick=function(){focus(api.objective(m).id);};el.querySelector('[data-home]').onclick=function(){focus('0,0');};el.querySelector('[data-menu]').onclick=function(){tell('');mode='menu';path=[];update();};el.querySelector('[data-workers]').onclick=function(){tell('');mode='people';update();};['world','build','people','research'].forEach(function(k){el.querySelector('[data-'+k+']').onclick=function(){tell('');mode=k;path=[];tool=null;if(k==='world')selected=null;update();};});el.querySelector('[data-minus]').onclick=function(){camera.scale=Math.max(28,camera.scale/1.2);draw();};el.querySelector('[data-plus]').onclick=function(){camera.scale=Math.min(90,camera.scale*1.2);draw();};
  function hit(e){var box=canvas.getBoundingClientRect();return Math.round((e.clientX-box.left-view.w/2)/camera.scale+camera.x)+','+Math.round((e.clientY-box.top-view.h/2)/camera.scale+camera.y);}
  function reject(id,message){rejected={id:id,until:Date.now()+650};tell(message);draw();}
  function resetTouches(){var ids=Array.from(pointers.keys());pointers.clear();gesture=null;pinch=null;ids.forEach(function(id){try{if(canvas.hasPointerCapture&&canvas.hasPointerCapture(id))canvas.releasePointerCapture(id);}catch(e){}});}
  function beginGesture(noTap){var points=Array.from(pointers.values());pinch=null;
   if(points.length===1){var p=points[0];gesture={x:p.x,y:p.y,cx:camera.x,cy:camera.y,moved:!!noTap};}
   else if(points.length===2){gesture=null;var a=points[0],b=points[1],box=canvas.getBoundingClientRect(),mx=(a.x+b.x)/2-box.left-view.w/2,my=(a.y+b.y)/2-box.top-view.h/2;pinch={distance:Math.max(8,Math.hypot(a.x-b.x,a.y-b.y)),scale:camera.scale,worldX:camera.x+mx/camera.scale,worldY:camera.y+my/camera.scale};}
   else gesture=null;
  }
  canvas.onpointerdown=function(e){if(e.button!==0)return;e.preventDefault();
   // A new primary touch begins a new sequence, even if a prior end was missed.
   if(e.isPrimary===true&&!pointers.has(e.pointerId))resetTouches();
   if(pointers.size>=2&&!pointers.has(e.pointerId))return;
   pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});beginGesture(false);
   try{canvas.setPointerCapture(e.pointerId);}catch(error){/* Window end listeners still release the gesture. */}
  };
  canvas.onpointermove=function(e){if(!pointers.has(e.pointerId))return;e.preventDefault();
   if(e.pointerType==='mouse'&&e.buttons===0){endTouch(e,false);return;}
   pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
   if(pointers.size===2&&pinch){var points=Array.from(pointers.values()),a=points[0],b=points[1],box=canvas.getBoundingClientRect();camera.scale=Math.max(24,Math.min(90,pinch.scale*Math.hypot(a.x-b.x,a.y-b.y)/pinch.distance));camera.x=pinch.worldX-((a.x+b.x)/2-box.left-view.w/2)/camera.scale;camera.y=pinch.worldY-((a.y+b.y)/2-box.top-view.h/2)/camera.scale;draw();return;}
   if(!gesture)return;var dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)>8)gesture.moved=true;
   if(gesture.moved){camera.x=gesture.cx-dx/camera.scale;camera.y=gesture.cy-dy/camera.scale;draw();}
  };
  function endTouch(e,allowTap){if(!pointers.has(e.pointerId))return;
   var tap=allowTap&&pointers.size===1&&gesture&&!gesture.moved&&Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)<=8;
   // Release tracking before rendering or running an action, including exceptions.
   pointers.delete(e.pointerId);beginGesture(true);
   try{if(canvas.hasPointerCapture&&canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}catch(error){}
   if(!tap)return;
   var id=hit(e);if(!api.tile(id)){reject(null,'Edge of this region.');}else if(mode==='place'){var site=api.placement(m,tool,id,[]);if(!site.ok)reject(id,site.message);else if(tool==='road'||tool==='bridge'){var r=api.action(m,save,'quickRoad',{id:id,type:tool,crew:count,batch:roadBatch});if(r.ok){roadBatch=m.settlement204.lastRoadBatch;selected=id;path=[];tell(r.message);refresh();update();}else reject(id,r.message);}else{path=[id];selected=id;update();}}else{tell('');selected=id;mode='world';expanded=false;path=[];update();}
  }
  function pointerUp(e){endTouch(e,true);}function cancel(e){endTouch(e,false);}
  function hidden(){if(document.hidden)resetTouches();}
  canvas.onpointerup=pointerUp;canvas.onpointercancel=cancel;canvas.onlostpointercapture=cancel;canvas.oncontextmenu=function(e){e.preventDefault();};
  root.addEventListener('pointerup',pointerUp,true);root.addEventListener('pointercancel',cancel,true);root.addEventListener('blur',resetTouches);root.addEventListener('pagehide',resetTouches);root.addEventListener('visibilitychange',hidden);
  function resize(){resetTouches();var box=canvas.getBoundingClientRect(),ratio=Math.min(2,root.devicePixelRatio||1);view={w:box.width,h:box.height};canvas.width=box.width*ratio;canvas.height=box.height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);draw();}root.addEventListener('resize',resize);var ro=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;if(ro)ro.observe(canvas.parentElement);
  function animate(now){if(dead)return;if(now-lastFrame>=100&&!document.hidden){draw();lastFrame=now;}frame=root.requestAnimationFrame(animate);}if(root.requestAnimationFrame)frame=root.requestAnimationFrame(animate);
  var timer=setInterval(function(){var d=m.settlement204,now=Date.now();if(now-d.at>=(d.job||d.scout||d.study?5000:15000)){var before=JSON.stringify([api.jobs(m).map(function(j){return [j.kind,j.path,j.done,j.crew];}),!!d.scout,!!d.study,d.queue,d.queueNotice,d.notice]),r=api.tick(m,save,now);if(!r.ok)tell(r.message);else if(before!==JSON.stringify([api.jobs(m).map(function(j){return [j.kind,j.path,j.done,j.crew];}),!!m.settlement204.scout,!!m.settlement204.study,m.settlement204.queue,m.settlement204.queueNotice,m.settlement204.notice])){tell(r.message);pendingUpdate=true;}}if(['people','economy','research'].indexOf(mode)>=0&&now-m.settlement204.at<1100)pendingUpdate=true;if(pendingUpdate&&!pointers.size){pendingUpdate=false;var scroll=sheet.scrollTop,oldMode=mode;update();sheet.scrollTop=oldMode===mode?scroll:0;}if(noticeUntil&&now>=noticeUntil)tell('');header();Array.prototype.forEach.call(sheet.querySelectorAll('[data-research-progress]'),function(p){var j=m.settlement204.study;if(j)p.value=Math.min(j.work[0],j.progress+Math.max(0,(now-m.settlement204.at)/1000)*api.speed(m,j));});Array.prototype.forEach.call(sheet.querySelectorAll('[data-crew-timer]'),function(p){var j=p.dataset.crewTimer==='job'?api.jobs(m).find(function(j){return String(j.projectId||'')===p.dataset.projectId;}):m.settlement204[p.dataset.crewTimer];if(j)p.textContent=duration(api.eta(m,j))+' remaining · '+j.crew+' workers';});draw();},1000);
  resize();update();tell('');return function(){if(dead)return;try{remember();}catch(e){console.warn('Could not save map position',e);}dead=true;resetTouches();root.removeEventListener('pointerup',pointerUp,true);root.removeEventListener('pointercancel',cancel,true);root.removeEventListener('blur',resetTouches);root.removeEventListener('pagehide',resetTouches);root.removeEventListener('visibilitychange',hidden);clearInterval(timer);if(frame!==null&&root.cancelAnimationFrame)root.cancelAnimationFrame(frame);root.removeEventListener('resize',resize);if(ro)ro.disconnect();el.remove();};
 }
 root.LSCSettlementView={mount:mount,paint:paint};
})(typeof window!=='undefined'?window:globalThis);
