(function(root){
 'use strict';
 var total=81,tiles={},zones=[],memo=null,memoState=null;
 function setup(){if(zones.length)return;for(var n=1;n<=total;n++){var z=root.LSCReclamation.zone(n);zones.push(z);z.tiles.forEach(function(t){tiles[t.id]=t;});}}
 function stars(n){setup();var z=zones[n-1],ring=Math.max(Math.abs(z.x),Math.abs(z.y))/7;return n===1?1:Math.min(5,Math.max(1,Math.floor(ring)+(n%3===0?1:0)));}
 function combat(n){return 1+(stars(n)-1)*5;}
 function state(m){return m.starTowns;}
 function complete(m,t){return t&&Number(state(m).progress[t.id])>=t.actions;}
 function network(m){setup();if(memoState===state(m))return memo;var connected=new Set(['0,0']),queue=['0,0'],visible=new Set();
  for(var i=0;i<queue.length;i++){var xy=queue[i].split(',').map(Number);[[1,0],[-1,0],[0,1],[0,-1]].forEach(function(d){var id=(xy[0]+d[0])+','+(xy[1]+d[1]);if(!connected.has(id)&&complete(m,tiles[id])){connected.add(id);queue.push(id);}});}
  function reveal(id,r){var xy=id.split(',').map(Number);for(var y=-r;y<=r;y++)for(var x=-r;x<=r;x++)visible.add((xy[0]+x)+','+(xy[1]+y));}
  reveal('0,0',2);connected.forEach(function(id){reveal(id,state(m).towers[id]?8:1);});
  Object.keys(state(m).progress).forEach(function(id){if(state(m).progress[id]>0)visible.add(id);});
  memoState=state(m);return memo={connected:connected,visible:visible};
 }
 function adjacent(m,t){return [[1,0],[-1,0],[0,1],[0,-1]].some(function(d){return network(m).connected.has((t.x+d[0])+','+(t.y+d[1]));});}
 function status(m,t){if(!t||!network(m).visible.has(t.id))return 'fog';return complete(m,t)?'reclaimed':adjacent(m,t)?'available':'locked';}
 function rate(m){return 2+zones.reduce(function(sum,z){return sum+(state(m).secured[z.number]&&network(m).connected.has(z.town)?stars(z.number)*2:0);},0);}
 function earned(m,now){return Math.min(480,Math.max(0,Math.floor(((now||Date.now())-state(m).incomeAt)/60000)))*rate(m);}
 function transact(m,save,fn){var old=state(m),credits=m.credits,parts=m.parts;m.starTowns=JSON.parse(JSON.stringify(old));try{fn(m.starTowns);if(save()!==true)throw Error('Save failed');return {ok:true};}catch(e){m.starTowns=old;m.credits=credits;m.parts=parts;return {ok:false,message:e.message};}}
 function initialize(m,save){setup();if(state(m))return {ok:true};if((m.bestPhase||0)>total)return {ok:false,message:'This first star world supports 81 towns. Your existing campaign remains saved; use New Campaign to try it.'};var old=m.starTowns,oldCredits=m.credits;var s={version:201,progress:Object.assign({},m.reclamation&&m.reclamation.progress),secured:{},towers:Object.assign({},m.reclamation&&m.reclamation.towers),incomeAt:Date.now()};
  // Preserve held towns and their historical supply network without revealing new districts.
  var best=Math.min(total,Math.max(0,m.bestPhase||0));for(var n=1;n<=best;n++){s.secured[n]=true;zones[n-1].route.forEach(function(id){s.progress[id]=tiles[id].actions;});var t=tiles[zones[n-1].town];s.progress[t.id]=t.actions;}
  if(best)root.LSCReclamation.supply({bestPhase:best-1}).forEach(function(id){if(tiles[id])s.progress[id]=tiles[id].actions;});
  if(best){var z=zones[best-1],x=z.x,y=z.y;while(x||y){var id=x+','+y;if(tiles[id])s.progress[id]=tiles[id].actions;if(x)x-=Math.sign(x);else y-=Math.sign(y);}}
  m.credits+=root.LSCReclamation.income(m).credits;m.starTowns=s;try{if(save()!==true)throw Error('Save failed');return {ok:true};}catch(e){m.credits=oldCredits;if(old===undefined)delete m.starTowns;else m.starTowns=old;return {ok:false,message:'Migration could not be saved. Existing campaign is unchanged.'};}
 }
 function ready(m,n){setup();var z=zones[n-1];return !!z&&!state(m).secured[n]&&network(m).connected.has(z.town);}
 function restore(m,id,save){var t=tiles[id];if(status(m,t)!=='available')return {ok:false,message:'Restore a connected neighbor first.'};if(m.credits<t.cost)return {ok:false,message:'Not enough Credits.'};var final=(state(m).progress[id]||0)+1>=t.actions;return transact(m,save,function(s){m.credits-=t.cost;s.progress[id]=(s.progress[id]||0)+1;if(final&&id!==zones[t.zone-1].town){m.credits+=t.credits;m.parts+=t.parts;}});}
 function scouting(m,t){var count=0;Object.keys(tiles).forEach(function(id){var other=tiles[id];if(Math.max(Math.abs(t.x-other.x),Math.abs(t.y-other.y))<=8&&!network(m).visible.has(id))count++;});return count;}
 function tower(m,id,save){var t=tiles[id];if(!t||t.site!=='hill'||!network(m).connected.has(id)||state(m).towers[id]||!scouting(m,t))return {ok:false,message:'Tower has no new terrain to reveal, or this hill is not connected.'};if(m.credits<75)return {ok:false,message:'Tower requires 75 Credits.'};return transact(m,save,function(s){m.credits-=75;s.towers[id]=true;});}
 function bonuses(m,n){var b={damage:0,hq:0,artillery:0};zones[n-1].tiles.forEach(function(t){if(network(m).connected.has(t.id)){if(t.site==='armory')b.damage=.1;if(t.site==='medical')b.hq=.1;if(t.site==='artillery')b.artillery=.15;}});return b;}
 function win(m,n){if(!ready(m,n))return false;var s=JSON.parse(JSON.stringify(state(m)));m.credits+=earned(m);s.incomeAt=Date.now();s.secured[n]=true;m.starTowns=s;return true;}
 function held(m){return state(m)?Object.keys(state(m).secured).length:0;}
 function mount(panel,m,save,refresh,back,deploy,power){var init=initialize(m,save);if(!init.ok){panel.textContent=init.message;return function(){};}var selected=tiles['1,0'],camera={x:0,y:0,scale:56},dead=false,hold=null,repeater=null,pointer=null;
  var el=document.createElement('section');el.id='star-world';el.style.cssText='position:fixed;inset:0;z-index:30500;background:#07191d;color:#edf2df;display:flex;flex-direction:column;padding-top:env(safe-area-inset-top);font:13px system-ui';
  el.innerHTML='<header style="padding:10px 14px"><b>FRONTIER · STAR TOWNS</b><button data-base>BASE</button><div data-wallet></div></header><div style="position:relative;flex:1;min-height:100px;overflow:hidden"><canvas style="width:100%;height:100%;touch-action:none"></canvas><div style="position:absolute;top:8px;right:8px"><button data-minus>−</button><button data-plus>+</button><button data-home>HQ</button><button data-towns>TOWNS</button></div></div><footer style="padding:10px 14px max(10px,env(safe-area-inset-bottom));background:#102a2d"><b data-title></b><p data-copy></p><div data-brief></div><button data-range>SCOUTING RANGE</button><button data-action>RESTORE</button><button data-collect>COLLECT</button><p data-message role="status">Explore from HQ. Connect a town, then win its defense to earn income.</p></footer>';
  var style=document.createElement('style');style.textContent='#star-world button{font:bold 11px system-ui;color:#f2edda;background:#214a48;border:1px solid #719e88;border-radius:8px;padding:10px;margin:3px;min-height:44px}#star-world button:disabled{opacity:.45}#star-world [data-base]{float:right}#star-world p{font-size:12px;line-height:1.4;margin:6px 0}';el.appendChild(style);document.body.appendChild(el);panel.innerHTML='';
  var canvas=el.querySelector('canvas'),ctx=canvas.getContext('2d'),view={w:1,h:1},hits=[],action=el.querySelector('[data-action]');
  function msg(s){el.querySelector('[data-message]').textContent=s;}
  var adapter={phase:function(){return total;},zone:function(n){return zones[n-1];},find:function(m,id){return tiles[id];},state:status,supply:function(){return new Set(['0,0']);},progress:function(m,t){return Math.min(t.actions,state(m).progress[t.id]||0);},isSecured:function(m,n){return !!state(m).secured[n];},stars:function(n){return stars(n);}};
  function draw(){if(dead)return;hits=root.LSCWorldArt.draw(ctx,Object.assign({},m,{reclamation:state(m)}),view,camera,adapter,selected);if(selected.site==='hill'&&status(m,selected)!=='fog'&&!state(m).towers[selected.id]){ctx.save();ctx.strokeStyle='#82d7de';ctx.lineWidth=2;ctx.strokeRect((selected.x-camera.x-8.5)*camera.scale+view.w/2,(selected.y-camera.y-8.5)*camera.scale+view.h/2,camera.scale*17,camera.scale*17);ctx.restore();}}
  function wallet(){el.querySelector('[data-wallet]').textContent=Math.floor(m.credits)+' CREDITS · '+held(m)+' SECURED · +'+rate(m)+'/MIN';el.querySelector('[data-collect]').textContent='COLLECT '+earned(m);}
  function update(){wallet();el.querySelector('[data-range]').style.display=selected.site==='hill'&&status(m,selected)!=='fog'?'inline-block':'none';var t=selected,z=zones[t.zone-1],town=t.id===z.town,s=status(m,t),linked=network(m).connected.has(t.id);el.querySelector('[data-title]').textContent=s==='fog'?'UNKNOWN TERRITORY':town?'TOWN '+t.zone+' · '+'★'.repeat(stars(t.zone)):t.site?t.site.toUpperCase():t.kind.toUpperCase();
   el.querySelector('[data-copy]').textContent=s==='fog'?'Explore adjacent land or build a useful scouting tower.':town?(state(m).secured[t.zone]?'SECURED · '+(linked?'+'+stars(t.zone)*2+' Credits/min':'Connect to HQ to activate income'):linked?'CONNECTED · Win the defense to start +'+stars(t.zone)*2+' Credits/min.':'DISCOVERED · Restore a route to HQ. No income yet.'):t.site==='hill'?'Scouting: '+scouting(m,t)+' unseen tiles · Tower costs 75 Credits.':t.site==='armory'?'Connected support: +10% weapon damage for this town.':t.site==='medical'?'Connected support: +10% command-post health for this town.':t.site==='artillery'?'Connected support: +15% artillery damage for this town.':'Restore connected ground to extend your frontier. '+((t.actions-(state(m).progress[t.id]||0))*t.cost)+' Credits remaining.';
   action.disabled=true;action.textContent='RESTORED';if(s==='available'){action.disabled=m.credits<t.cost;action.textContent='RESTORE · '+t.cost+'/STEP';}else if(town&&ready(m,t.zone)){action.disabled=false;action.textContent='REVIEW DEFENSE';}else if(t.site==='hill'&&linked&&!state(m).towers[t.id]){action.disabled=!scouting(m,t)||m.credits<75;action.textContent=scouting(m,t)?'BUILD TOWER · 75':'NO NEW TERRAIN';}else if(s==='fog'||s==='locked')action.textContent='CONNECT A NEIGHBOR';draw();
  }
  function resize(){var box=canvas.getBoundingClientRect(),d=Math.min(2,root.devicePixelRatio||1);view={w:box.width,h:box.height};canvas.width=box.width*d;canvas.height=box.height*d;ctx.setTransform(d,0,0,d,0,0);draw();}
  function stop(){clearTimeout(hold);clearTimeout(repeater);hold=repeater=null;}
  function spend(){var oldCredits=m.credits,oldParts=m.parts;var result=restore(m,selected.id,save);msg(result.ok?(complete(m,selected)?(selected.id===zones[selected.zone-1].town?'Town connected. Win its defense to activate income.':selected.site?'Support connected for Town '+selected.zone+'.':(m.credits-oldCredits+selected.cost>0?'+'+(m.credits-oldCredits+selected.cost)+' Credits. ':'' )+(m.parts>oldParts?'+'+(m.parts-oldParts)+' Tech Parts. ':'')+'Tile restored.'):'Restoration saved.'):result.message);refresh();update();return result.ok&&status(m,selected)==='available';}
  action.onclick=function(){stop();var t=selected;if(ready(m,t.zone)&&t.id===zones[t.zone-1].town){var phase=combat(t.zone),b=bonuses(m,t.zone),box=el.querySelector('[data-brief]');box.innerHTML='';var copy=document.createElement('p');copy.textContent='TOWN '+t.zone+' · '+'★'.repeat(stars(t.zone))+' · '+power(phase)+' · Costs 1 energy. Support: weapon '+b.damage*100+'%, health '+b.hq*100+'%, artillery '+b.artillery*100+'%. Victory pays the combat reward and activates income. Defeat preserves territory.';box.appendChild(copy);var button=document.createElement('button');button.textContent='DEPLOY DEFENSE · 1 ENERGY';button.onclick=function(){if(ready(m,t.zone)){var error=deploy(t.zone,phase);if(error)msg(error);}};box.appendChild(button);}else if(t.site==='hill'&&complete(m,t)){var result=tower(m,t.id,save);msg(result.ok?'Tower online. New terrain revealed.':result.message);update();}else spend();};
  el.querySelector('[data-collect]').onclick=function(){var credits=earned(m);if(!credits){msg('Income accrues each minute; up to 8 hours stored.');return;}var result=transact(m,save,function(s){m.credits+=credits;s.incomeAt=Date.now();});msg(result.ok?'+'+credits+' Credits collected.':result.message);update();refresh();};
  el.querySelector('[data-range]').onclick=function(){stop();camera.x=selected.x;camera.y=selected.y;camera.scale=Math.max(8,Math.min(view.w,view.h)/18);draw();};
  el.querySelector('[data-towns]').onclick=function(){stop();var box=el.querySelector('[data-brief]');box.innerHTML='';box.style.maxHeight='180px';box.style.overflow='auto';var seen=zones.filter(function(z){return network(m).visible.has(z.town);});if(!seen.length)box.textContent='No towns discovered. Explore outward from HQ.';seen.forEach(function(z){var button=document.createElement('button');button.textContent='TOWN '+z.number+' · '+'★'.repeat(stars(z.number))+' · '+(state(m).secured[z.number]?'SECURED':ready(m,z.number)?'CONNECTED':'DISCOVERED');button.onclick=function(){selected=tiles[z.town];camera.x=selected.x;camera.y=selected.y;box.innerHTML='';update();};box.appendChild(button);});};
  el.querySelector('[data-base]').onclick=back;el.querySelector('[data-home]').onclick=function(){camera.x=0;camera.y=0;draw();};el.querySelector('[data-minus]').onclick=function(){camera.scale=Math.max(12,camera.scale/1.25);draw();};el.querySelector('[data-plus]').onclick=function(){camera.scale=Math.min(100,camera.scale*1.25);draw();};
  var pointers=new Map();canvas.onpointerdown=function(e){if(e.button!==0)return;e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});stop();if(pointers.size!==1){pointer=null;return;}canvas.setPointerCapture(e.pointerId);var box=canvas.getBoundingClientRect(),x=e.clientX-box.left,y=e.clientY-box.top,h=hits.find(function(h){return Math.abs(h.x-x)<camera.scale/2&&Math.abs(h.y-y)<camera.scale/2;});pointer={x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y};if(h){selected=h.t;el.querySelector('[data-brief]').innerHTML='';update();hold=setTimeout(function work(){if(pointer&&spend())repeater=setTimeout(work,150);},450);}};
  canvas.onpointermove=function(e){if(!pointers.has(e.pointerId))return;var before=Array.from(pointers.values());pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){stop();var after=Array.from(pointers.values()),distance=function(p){return Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);};camera.scale=Math.max(12,Math.min(100,camera.scale*distance(after)/Math.max(1,distance(before))));draw();return;}if(!pointer||pointers.size!==1)return;var dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(pointer.moved||Math.hypot(dx,dy)>10){pointer.moved=true;stop();camera.x=pointer.cx-dx/camera.scale;camera.y=pointer.cy-dy/camera.scale;draw();}};
  function end(e){stop();pointers.delete(e.pointerId);pointer=null;}canvas.onpointerup=end;canvas.onpointercancel=end;canvas.onlostpointercapture=end;canvas.oncontextmenu=function(e){e.preventDefault();};
  function suspend(){stop();pointer=null;pointers.clear();}root.addEventListener('blur',suspend);document.addEventListener('visibilitychange',suspend);root.addEventListener('resize',resize);var ro=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;if(ro)ro.observe(canvas.parentElement);var timer=setInterval(wallet,1000);resize();update();
  return function(){dead=true;stop();clearInterval(timer);if(ro)ro.disconnect();root.removeEventListener('blur',suspend);document.removeEventListener('visibilitychange',suspend);root.removeEventListener('resize',resize);el.remove();};
 }
 root.LSCStarTowns={initialize:initialize,ready:ready,restore:restore,tower:tower,scouting:scouting,stars:stars,combat:combat,win:win,held:held,rate:rate,earned:earned,bonuses:bonuses,network:network,status:status,mount:mount,tile:function(id){setup();return tiles[id];},zone:function(n){setup();return zones[n-1];}};
})(typeof window!=='undefined'?window:globalThis);
