(function(root){
 'use strict';
 var definitions={farm:{name:'Farm',credits:200,food:0,metal:0,output:'2 Food/min',description:'Meadow or riverbank. Food supplies expeditions and foundry construction.'},foundry:{name:'Foundry',credits:300,food:5,metal:0,output:'1 Metal/min',description:'Highland. Metal builds bridges and harbors or converts to Tech Parts.'},harbor:{name:'Harbor',credits:350,food:0,metal:5,output:'4 Credits/min',description:'Water beside land. Trade income and scouting of nearby water.'},road:{name:'Road',credits:25,food:0,metal:0,output:'Connects production',description:'Connect roads to HQ or an existing restored approach road.'},bridge:{name:'Bridge',credits:80,food:0,metal:2,output:'Road across water',description:'Connects the road network across a water tile.'}};
 function state(m){return m.starTowns;}
 function data(m){return state(m).construction||{buildings:{},roads:{},food:10,metal:10,at:Date.now()};}
 function ensure(m){if(!state(m).construction)state(m).construction={buildings:{},roads:{},food:10,metal:10,at:Date.now()};return state(m).construction;}
 function neighbors(t){return [[1,0],[-1,0],[0,1],[0,-1]].map(function(d){return (t.x+d[0])+','+(t.y+d[1]);});}
 function terrain(t){return root.LSCWorldArt.terrain(t);}
 function transport(m,api){var d=data(m),connected=new Set(['0,0']),queue=['0,0'];for(var i=0;i<queue.length;i++){var xy=queue[i].split(',').map(Number);neighbors({x:xy[0],y:xy[1]}).forEach(function(id){var t=api.tile(id);if(t&&!connected.has(id)&&api.status(m,t)==='reclaimed'&&(t.required||d.roads[id])){connected.add(id);queue.push(id);}});}return connected;}
 function linked(m,t,api,roads){return (roads||transport(m,api)).has(t.id)||neighbors(t).some(function(id){return (roads||transport(m,api)).has(id);});}
 function rates(m,api){var d=data(m),roads=transport(m,api),r={food:0,metal:0,credits:0};Object.keys(d.buildings).forEach(function(id){var t=api.tile(id),kind=d.buildings[id];if(!t||!linked(m,t,api,roads))return;if(kind==='farm')r.food+=2;if(kind==='foundry')r.metal+=1;if(kind==='harbor')r.credits+=4;});return r;}
 function accrued(m,api,now){var d=data(m),minutes=Math.min(480,Math.max(0,((now===undefined?Date.now():now)-d.at)/60000)),r=rates(m,api),carry=d.carry||{};return {food:(carry.food||0)+r.food*minutes,metal:(carry.metal||0)+r.metal*minutes,credits:(carry.credits||0)+r.credits*minutes};}
 function pending(m,api,now){var p=accrued(m,api,now);return {food:Math.floor(p.food),metal:Math.floor(p.metal),credits:Math.floor(p.credits)};}
 function collect(m,api){var a=accrued(m,api),p={food:Math.floor(a.food),metal:Math.floor(a.metal),credits:Math.floor(a.credits)},d=ensure(m);d.food+=p.food;d.metal+=p.metal;m.credits+=p.credits;d.carry={food:a.food-p.food,metal:a.metal-p.metal,credits:a.credits-p.credits};d.at=Date.now();return p;}
 function options(m,t,api){if(!t||api.status(m,t)!=='reclaimed')return [];var d=data(m),type=terrain(t),special=t.site||t.required||t.kind!=='grove',out=[];if(!t.required&&!d.roads[t.id])out.push(type==='water'?'bridge':'road');if(!special&&!d.buildings[t.id]){if(type==='meadow'||type==='bank')out.push('farm');if(type==='highland')out.push('foundry');if(type==='water'&&neighbors(t).some(function(id){var n=api.tile(id);return id==='0,0'||n&&terrain(n)!=='water';}))out.push('harbor');}return out;}
 function transact(m,save,fn){var old=m.starTowns,credits=m.credits,parts=m.parts;m.starTowns=JSON.parse(JSON.stringify(old));try{ensure(m);var result=fn();m.starTowns=JSON.parse(JSON.stringify(m.starTowns));if(save()!==true)throw Error('Save failed. Construction unchanged.');return {ok:true,message:result};}catch(e){m.starTowns=old;m.credits=credits;m.parts=parts;return {ok:false,message:e.message};}}
 function build(m,t,kind,api,save){if(options(m,t,api).indexOf(kind)<0)return {ok:false,message:'This structure needs a suitable restored tile.'};var def=definitions[kind],d=data(m);if(m.credits<def.credits||d.food<def.food||d.metal<def.metal)return {ok:false,message:'Need '+def.credits+' Credits, '+def.food+' Food and '+def.metal+' Metal. Collect production or find supplies.'};return transact(m,save,function(){collect(m,api);var d=ensure(m);m.credits-=def.credits;d.food-=def.food;d.metal-=def.metal;if(kind==='road'||kind==='bridge')d.roads[t.id]=kind;else d.buildings[t.id]=kind;return def.name+' built. '+(linked(m,t,api)?def.output+'.':'Connect a road to HQ to start production.');});}
 function exchange(m,recipe,api,save){var d=data(m);if(recipe!=='supplies'&&recipe!=='parts')return {ok:false,message:'Unknown recipe.'};if(recipe==='supplies'&&d.food<10||recipe==='parts'&&d.metal<5)return {ok:false,message:recipe==='supplies'?'Requires 10 collected Food.':'Requires 5 collected Metal.'};return transact(m,save,function(){var d=ensure(m);if(recipe==='supplies'){d.food-=10;m.credits+=80;return '+80 expedition Credits.';}d.metal-=5;m.parts+=1;return '+1 Tech Part.';});}
 function guide(m,api){var d=data(m),roads=transport(m,api),ids=Object.keys(d.buildings),offline=ids.find(function(id){return !linked(m,api.tile(id),api,roads);});
  if(offline){var queue=[offline],seen=new Set(queue),parent={};for(var i=0;i<queue.length;i++){var t=api.tile(queue[i]);if(neighbors(t).indexOf('0,0')>=0&&!roads.has(t.id))return {tile:t,text:'Connect production · build a road beside HQ.'};if(roads.has(t.id)){var next=api.tile(parent[t.id]);return {tile:next,text:'Connect production · restore and build a road on this route tile.'};}neighbors(t).forEach(function(id){var other=api.tile(id);if(other&&!seen.has(id)&&api.status(m,other)!=='fog'){seen.add(id);parent[id]=t.id;queue.push(id);}});}return {tile:api.tile(offline),text:'Connect your building to HQ with roads.'};}
  var kind=['farm','foundry','harbor'].find(function(k){return !ids.some(function(id){return d.buildings[id]===k;});});if(!kind)return {tile:null,text:'Grow your settlement · explore building sites, expand roads, or defend a discovered town.'};
  var sites=[];for(var n=1;n<=81;n++)api.zone(n).tiles.forEach(function(t){if(t.site||t.required||t.kind!=='grove'||d.buildings[t.id]||api.status(m,t)==='fog')return;var type=terrain(t);if(kind==='farm'&&(type==='meadow'||type==='bank')||kind==='foundry'&&type==='highland'||kind==='harbor'&&type==='water'&&neighbors(t).some(function(id){var o=api.tile(id);return o&&terrain(o)!=='water';}))sites.push(t);});
  sites.sort(function(a,b){return Math.abs(a.x)+Math.abs(a.y)-Math.abs(b.x)-Math.abs(b.y);});return sites.length?{tile:sites[0],text:'Build your first '+definitions[kind].name+' · restore the site, then tap BUILD.'}:null;
 }
 function overview(m,api){var d=data(m),r=rates(m,api),count=Object.keys(d.buildings).length;return d.food+' FOOD · '+d.metal+' METAL · '+count+' BUILDINGS · production '+r.food+' Food / '+r.metal+' Metal / '+r.credits+' Credits per min';}
 function hint(m,t,api){var d=data(m),kind=d.buildings[t.id];if(kind)return definitions[kind].name+' · '+(linked(m,t,api)?definitions[kind].output:'No production: connect an adjacent road to HQ.');if(api.status(m,t)!=='reclaimed')return 'Restore this tile to inspect building choices.';var choices=options(m,t,api);return choices.some(function(k){return k!=='road'&&k!=='bridge';})?'Choose a building below. Production requires a road connection to HQ.':'Farms need meadow/bank; foundries need highland; harbors need shoreline water. Existing sites stay intact.';}
 root.LSCWorldBuilding={definitions:definitions,guide:guide,data:data,ensure:ensure,transport:transport,linked:linked,rates:rates,pending:pending,collect:collect,options:options,build:build,exchange:exchange,overview:overview,hint:hint};
})(typeof window!=='undefined'?window:globalThis);
